### PR TITLE
Update Travis scripts to use yarn

### PR DESCRIPTION
**Pull request by eatyourgreens**
# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Travis build is failing with `Error: Cannot find module '@zooniverse/react-components'` in the project app.

**Comment by eatyourgreens** [comment]
@roger I think this is working now.

**Comment by rogerhutchings** [comment]
The build steps for `react-components` and `classifier` have been taken out, so the files pointed to in the `package.json` files weren't there.

**Comment by eatyourgreens** [comment]
👍 seems to be working now.

**Comment by eatyourgreens** [comment]
Failing tests are broken on the parent branch too, so I think this can be merged.

**Comment by rogerhutchings** [comment]
Cool. I'm going to push a commit to remove the old travis script files first. The build process has simplified, so we can ditch them.

**Comment by eatyourgreens** [comment]
Looks good. Runs locally for me. I'd forgotten to trash everything before testing CI on Friday.

SocialAnchor tests are broken in ZRC, which is a separate issue.

**Pull request merged**
