### PR TITLE
Add survey task characteristics property validation

### PR DESCRIPTION
**Pull request by mcbouslog**
Package: lib-classifier

Iteration on #1935.
Towards #1987. 

Describe your changes:
- adds survey task model characteristics property validation

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by ErikOstlund — CHANGES_REQUESTED** [review]
Please add a detailed way to test this to ensure the `Characteristics` type is correct.

**Comment by srallen** [comment]
@ErikOstlund, I've taken over updating this PR. I've added several unit tests to test for cases where the survey task characteristics are malformed. The test suite already included a success test case, so we just needed to add failure test cases.

**Review by ErikOstlund — APPROVED** [review]
Looks good. Units test pass and make sense. 👍🏽

**Comment by mcbouslog** [comment]
thank you @ErikOstlund and @srallen !

**Pull request merged**
