### PR TITLE
Fix broken images in Recent Subjects stories

### PR DESCRIPTION
**Pull request by eatyourgreens**
Preview images are broken for recent Talk subjects and recent classification subjects in the project storybook.
https://zooniverse.github.io/front-end-monorepo/@zooniverse/fe-project/index.html?path=/story/project-app-screens-project-home-recent-subjects--plain
https://zooniverse.github.io/front-end-monorepo/@zooniverse/fe-project/index.html?path=/story/project-app-screens-classify-recent-subjects--plain&knob-Dark%20theme=true&knob-User%20logged%20in=true

This PR converts both components to use CSF and fixes the broken image URLs.
Screenshot of the Recent Classifications story, with images of antelopes and giraffes from Snapshot Serengeti.

Package:
app-project

Towards #2370.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by goplayoutside3 — COMMENTED** [review]
Looks good! I noticed the Shared / Subject Preview image is similarly broken like the old Recent Subjects stories. Is the fix you used for Recent Subjects stories easily applied to Subject Preview in this PR too?

**Comment by eatyourgreens** [comment]
Oh, good catch. That probably is exactly the same problem. It might be using an image URL that doesn’t work any more. For this PR, I took some new URLs at random from Snapshot Serengeti Talk.

**Comment by eatyourgreens** [comment]
I’ll add that story to this PR.

**Review by goplayoutside3 — APPROVED** [review]
Looks good!

**Pull request merged**
