### PR TITLE
Run npm audit

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-grommet-theme, lib-async-states, lib-panoptes-js, and the parent package.json

Describe your changes:
Runs npm audit fix on these packages. There's an upstream fix for the vulnerability in the lerna dependencies that's just awaiting publishing.

I'm not sure what to do about react-components, the classifier, and the app-project. Running npm audit errors because of the symlinking (says linked package can't be found). How should we handle this?

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
This might be the point to start using directory references instead of symlinking...

**Comment by srallen** [comment]
Yeah, not being able to quickly do security updates is a big issue for me.

**Comment by rogerhutchings** [comment]
This can be merged, if you're okay with addressing the linking issue in another PR

**Comment by srallen** [comment]
Sure let's merge it. I was also waiting for the upstream fix for the lerna vulnerability, but that can update separately later too.

**Pull request merged**
