### PR TITLE
Build libraries with 'npm prepare'

### PR DESCRIPTION
**Pull request by eatyourgreens**
Use `prepare` to build both `@zooniverse/react-components` and `@zooniverse/classifier` during installation. Build both ESM and CJS modules so that the tests run. Switch the bootstrap script to use `yarn install` during local builds.

## Package
lib-react-components
lib-classifier

## How to Review
```sh
# clean installed packages and builds
yarn panic
# install and build from scratch
yarn bootstrap
# test the project app on eg. https://local.zooniverse.org:3000/projects/zooniverse/gravity-spy
cd packages/app-project
yarn start
# test the content pages app on eg. https://local.zooniverse.org:3000/about/publications
cd ../app-content-pages
yarn start
```

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Maintenance
- [x] If not from dependabot, the PR creator has described the update (major, minor, or patch version, changelog)

### CODE REVIEW

**Comment by mcbouslog** [comment]
I think I'm making a mistake or misunderstanding, but if I run `yarn start` for app-project or app-content-pages with these changes the local server doesn't run and there's no error message. Is that expected? 

If I run `yarn dev` for app-project or app-content-pages with these changes a local dev server runs and the apps work as expected.

**Comment by eatyourgreens** [comment]
I’m a bit confused. The PR checklist says you can load a project and submit a classification, but that’s only possible if you start a server with `yarn start`.

**Comment by eatyourgreens** [comment]
This worked fine for me when I opened it a couple of months ago. I’ll have to revisit it to see what has changed since. 

The changes here don’t touch the start scripts for either app, so that’s unexpected that they suddenly don’t work.

**Comment by eatyourgreens** [comment]
Both apps start for me.

`app-project`
Console output for the project app start command, showing the app running on port 3000.

`app-content-pages`
Console output for the content pages app start command, showing the app running on port 3000.

**Comment by eatyourgreens** [comment]
No problems running both apps with `npx next start` either, so I can't find any problems here.

**Comment by mcbouslog** [comment]
> I’m a bit confused. The PR checklist says you can load a project and submit a classification, but that’s only possible if you start a server with `yarn start`.

I did so with `yarn dev`.

**Review by mcbouslog — APPROVED** [review]

**Comment by mcbouslog** [comment]
> No problems running both apps with `npx next start` either, so I can't find any problems here.

Cleared local caches (related to this PR, `yarn` cache) and works as expected. 

http://local.zooniverse.org:3000/about/team and https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess?env=production&demo=true works as expected.

**Comment by eatyourgreens** [comment]
Don’t test in development mode, by the way. We’ve accidentally deployed broken production builds in the past, because we tested in dev mode. Development mode turns off some production features, in order to enable fast refresh and HMR.

**Pull request merged**
