### PR TITLE
Render link lists as ul in footer

### PR DESCRIPTION
**Pull request by rogerhutchings**
Package: lib-react-components

cc #667 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
The failing test needs to be fixed, but I think that might not be related to this PR.

**Comment by eatyourgreens** [comment]
Here's the test that's blocking this from merging.
```
1) Subjects Helpers
       buildQueuedSubjectResource
         should return a mocked subject with a random id > 0 and <= 100:
     AssertionError: expected 0 to be within 1..100
      at Context.<anonymous> (src/resources/subjects/helpers.spec.js:13:40)
```
I guess that test is going to fail ~1% of the time and just happened to fail by chance on this PR.

**Comment by eatyourgreens** [comment]
Rerunning the Travis build generated a valid, random subject ID this time.

**Comment by srallen** [comment]
Thanks for catching that test failure. I'd like to copy or move the rosie factory setup that I've started to use in the lib-classifier to lib-panoptes-js.

**Pull request merged**
