### PR TITLE
ZRC: Fix modal default colours

### LINKED ISSUE #1785: Default modal heading styles have been removed
**Package**
lib-classifier

**Describe the bug**
The default modal heading style is now grey text on a white background.

Screenshot of the Add To Collections modal showing that the heading has lost its styling and now uses default text colours.

**Expected behavior**
Default styling should be white text (`neutral-6`) on a teal background (`brand`).

**Additional context**
Default modal heading colours were changed to empty strings in #1683. Removing those defaults fixes the text and background colours, but doesn't seem to change the colour of the close button icon.
https://github.com/zooniverse/front-end-monorepo/blob/c8d588b82dd4bb5bcacf7154d02195fd7347d846/packages/lib-react-components/src/Modal/Modal.js#L24-L34

### PR DESCRIPTION
**Pull request by eatyourgreens**
Package:
lib-classifier
lib-react-components

Closes #1785.

Describe your changes:
Remove the default heading colours from the `Modal` component, so that the defaults in `ModalHeading` are used.
Fixes padding around the content in `ModalBody` too.
Adds a few tests to check default props, where styles are passed as props.

TODO:
- [ ] Fix the colour of the close button so that it matches the heading text.

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [x] Is the documentation up to date?

## Components
- [x] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Here's 'Add To Collection' on this branch. I'm not sure if the padding around the title is correct, and the close button still needs to be fixed.
Screenshot of the Add To Collection modal with white text on a teal background.

**Comment by eatyourgreens** [comment]
This should be checked against the field guide, the popup tutorial, the sign-in form and the registration form, in case I've introduced regressions for the styles of those. Maybe also the drawing tools task pop-ups?

**Comment by beckyrother** [comment]
Here's a link to the modal design on the Design System Manager: https://projects.invisionapp.com/dsm/zooniverse/primary-brand/asset/components/5ea995ce07156c97c3cd7985

**Comment by eatyourgreens** [comment]
Thanks @beckyrother, that's really useful. Comparing with the modal on this branch, it looks to me like either the vertical spacing is off in the heading, or maybe the vertical alignment of the text.

Screenshot showing the expected layout and spacing for a modal header.

Screenshot of the Add To Collection modal, showing the actual spacing.

**Comment by eatyourgreens** [comment]
I've added a `color` prop to the close button, but can't check whether the `ConsensusPopup` still works because the storybook is broken (#1789.)

**Comment by eatyourgreens** [comment]
@beckyrother how does this look? I removed vertical margins and set the line-height to 0.

Storybook screenshot of the Modal story, with a reduced header size.

**Comment by eatyourgreens** [comment]
I've added some fixes for the `MovableModal` component, so I think this is ready for review now.

**Comment by eatyourgreens** [comment]
@beckyrother here's the Add To Collections popup with my latest changes.

Project storybook screenshot, showing the Collections Button story with the popup open.

**Review by beckyrother — COMMENTED** [review]
The bar looks great! It might be because the rest of the modal has a lot of white space, but there should just be 20px between the bottom of the bar and the rest of the content

**Comment by eatyourgreens** [comment]
@beckyrother you're right. The whitespace in the storybook looks too large too. (https://github.com/zooniverse/front-end-monorepo/pull/1786#issuecomment-687115414)

**Comment by eatyourgreens** [comment]
@beckyrother here it is with the padding set to 20px at the top, 30px on the other three sides.

Modal storybook screenshot with updated padding around the modal body content, smaller at the top.

**Comment by beckyrother** [comment]
> @beckyrother here it is with the padding set to 20px at the top, 30px on the other three sides.
> 


Looks perfect @eatyourgreens ! Thanks!

**Review by mcbouslog — APPROVED** [review]
This LGTM, great work!

I'm not sure if `ConsensusPopup.js` also needs `titleColor=''`, but strangely that component is working on https://frontend.preview.zooniverse.org/projects/wgranger-test/anti-slavery-testing/classify?env=staging , but isn't working when I run master locally (http://localhost:3000/projects/wgranger-test/anti-slavery-testing/classify or https://local.zooniverse.org:8080/?project=1764), so I'll investigate further, but don't think should hold up this PR.

**Comment by eatyourgreens** [comment]
@mcbouslog thanks for taking a look. Maybe the consensus popup is broken in development, but not production? I was seeing a PropTypes error in the storybook (#1789.)

**Comment by eatyourgreens** [comment]
Consensus popup is showing a white close button on a white background, so `titleColor` does need to be overidden. Out of interest, why does an empty string reset it to the default text colour? That wasn't clear to me.

The error in the `ConsensusPopup` component can be worked around by replacing `StyledBox` with `Box`, so I think that might have been introduced by the style components upgrade.

Screenshot of the transcription consensus popup, where the close button is white on a white background.

**Comment by eatyourgreens** [comment]
In the dark theme, I'm not seeing the text colour being applied to the close button.

Screenshot of the consensus popup in dark mode.

Screenshot of the consensus popup in light mode.

**Review by srallen — COMMENTED** [review]
Could you update the changelog for lib-react-components?

**Comment by eatyourgreens** [comment]
@srallen Absolutely!

Would it be ok to merge this and deal with the subtask popups in a separate PR, or should we fix the styling for all the modals here? I've got no strong opinions either way.

**Comment by beckyrother** [comment]
@eatyourgreens here's the InVision for the text transcription sub-task: https://projects.invisionapp.com/d/main#/console/12923997/404084878/preview

**Comment by srallen** [comment]
@eatyourgreens I don't really have an opinion on that without having reviewed this PR. If it's just a couple of lines, maybe include it, but if not, then separate is fine.

**Comment by eatyourgreens** [comment]
@beckyrother thanks for the link. Here's the subtask from Invision (top) compared with the classifier storybook (bottom) on this branch. It looks to me like the modal header spacing is bigger (and maybe the close button size is smaller?) than for the default modal layout.

Invision design for the transcription task popup 
Screenshot of the transcription subtask from the Classifier storybook.

**Comment by beckyrother** [comment]
@eatyourgreens yes, looks like it's 20px padding rather than 30px, since we know it'll be on top of a subject and we'll want to take up less screen space. InVision's Inspect Mode (the `</>` at the bottom) lets you see exact spacing, type sizes, etc:

Screen Shot 2020-09-11 at 10 09 28 AM

**Comment by eatyourgreens** [comment]
At the moment, the `Modal` component supports passing in the title bar text and background colours as props. I'm not sure if it supports changing the padding or margins of the title bar.

**Comment by srallen** [comment]
A prop could be added to support this as needed... maybe consolidated into a `titleProps` prop?

**Comment by srallen** [comment]
Is this waiting for something to merge? I didn't actually review the code, so I'm hesitant to mark it as approved from me, but I see that the changelog has been updated :+1:

**Comment by eatyourgreens** [comment]
I think it's ok to merge this, to fix the tutorial, field guide etc. for PH-TESS, but the padding and margins on the transcription popups will still need work.

**Comment by eatyourgreens** [comment]
Reading back through @beckyrother's comments, I think it's the body of the transcription popup that has smaller padding than our default modal style.

**Comment by srallen** [comment]
Ok, @eatyourgreens, then please do merge and open issue(s) to track what other work still needs to be done. Thanks!

**Review by mcbouslog — APPROVED** [review]

**Comment by eatyourgreens** [comment]
Will do. Out of curiosity, I've tried merging this from the GitHub phone app.

**Pull request merged**
