### PR TITLE
Footer in two columns on mobile view

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-react-components

Fix for #746

Describe your changes:
Makes footer two columns:
IMG_3492

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by srallen** [comment]
@rogerhutchings I see them have a line-height of 18px for a font-size of 14px, which are the base medium sizes set in the theme. I used @beckyrother guidance in this doc for these: https://projects.invisionapp.com/d/main#/projects/prototypes/12923997/assets/77727645

According to that doc, it should be 14px/17px. @beckyrother do you want the pixel decrease for the line-height in the theme? Do you want the footer to use these base sizes or something else?

**Comment by rogerhutchings** [comment]
I'm sure they're accurate to the design, but look at them - the gap between lines in the section titles is almost the same size as the gap between section items.

**Comment by beckyrother** [comment]
Agreed @rogerhutchings, they're a bit tall. Can we adjust the style to be 14px / 14px line-height? This would be a global change for that type style.

**Comment by srallen** [comment]
Ok, I'm not sure where we should set that in the theme...

@rogerhutchings we could make the small paragraph setting 14px/14px? 

https://github.com/zooniverse/front-end-monorepo/blob/c177dd59f5f9d47ba16ee7932542f3db44613bcd/packages/lib-grommet-theme/src/index.js#L372-L375

**Comment by beckyrother** [comment]
This is for the teal labels right?

**Comment by srallen** [comment]
@beckyrother they're anchors wrapped by spans, which is reusing the theme's defaults for 'medium' sized paragraphs and spans. We could set the 'small' spans/paragraph's defaults to 14px/14px. Then any paragraph or span (and child components) we set to `size="small"` will be this.

**Comment by rogerhutchings** [comment]
@srallen heading levels can be set separately: https://v2.grommet.io/heading

**Comment by srallen** [comment]
Yep, headings have their sizes defined in the theme too, but those aren't headings in the markup. They could be however. I'll make notes on what to change in the issue for #758 and let's keep this as just the grid update for the footer.

**Comment by srallen** [comment]
I should note that the collision should be fixed and this is ready for another review.

**Comment by beckyrother** [comment]
Is there a way to see this live? I'm sorry I definitely should know this by now.

**Comment by srallen** [comment]
@beckyrother if you're willing to pull down the repo and run locally, but we don't have staged deployments setup for this yet. Or you could come bug me and take a look on my screen. We'll try to get staged deployments working soon!

**Comment by srallen** [comment]
Oh I should add, the react components repo we want to deploy the storybook to github pages, so that'd be another way to take a look, but that hasn't been done yet either.

**Pull request merged**
