### PR TITLE
[WIP] Classifier: upgrade MST to 3.15.0

### PR DESCRIPTION
**Pull request by eatyourgreens**
#1450: the return! Hopefully without bugs this time.

Package:
lib-classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Bugs to look out for, from the previous attempt to upgrade:
https://github.com/zooniverse/front-end-monorepo/pull/1450#issuecomment-582575695

**Comment by eatyourgreens** [comment]
This branch still gives this error on moving to a new subject:
```
mobx-react.module.js:26 Uncaught Error: [mobx-state-tree] 
You are trying to read or write to an object that is no longer part of a state tree. 
(Object type: 'DrawingAnnotation', Path upon death: 
'/classifications/resources/ck6knua8c000b3h60bt8bfxej/annotations/ck6knt2xv00013h60kecq605b', 
Subpath: 'task', Action: '/workflowSteps.resetSteps()'). 
Either detach nodes first, or don't use objects after removing / replacing them in the tree.
```

**Comment by shaunanoordin** [comment]
Yikes, I can confirm that the update _does_ break the Classifier.

Any attempt to submit a Classification on a simple Workflow (with a rectangle drawing task) causes a full app crash to a white page, ❗️ with the console error: `Uncaught Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'DrawingAnnotation', Path upon death: '/classifications/resources/ck6met0wx00043h5ytxejv0pj/annotations/ck6mesl6a00013h5ygeaybojq', Subpath: 'task', Action: ''). Either detach nodes first, or don't use objects after removing / replacing them in the tree.`

Curiously, you're encountering the error on `Action: 'workflowSteps.resetSteps()'` whereas I'm getting it on `Action: ''` 🤷‍♂ Probably not important though.

**Comment by shaunanoordin** [comment]
I can confirm that the error occurs _after_ the Classification is submitted to the API (I'm seeing a successful POST to `/classifications`) so maybe we just need to jam in a 'reset every goddarn thing' in the on-Classification-submit cleanup step? (I'm still trying to figure out what specifically needs to be "detached" according to the error message.)

**Comment by eatyourgreens** [comment]
After merging #1555 this branch is still broken for drawing tasks.
```
Uncaught Error: [mobx-state-tree] You are trying to read or write to an object that 
is no longer part of a state tree. 
(Object type: 'DrawingAnnotation', 
Path upon death: 
'/classifications/resources/ck7pws3st00033h621a5hdamb/annotations/ck7pwrsmt00013h620x19bcef', 
Subpath: 'task', 
Action: '/classifications/resources/ck7pws3st00033h621a5hdamb.addAnnotation()'). 
Either detach nodes first, or don't use objects after removing / replacing them 
in the tree.
```

That error is being thrown `onSubjectReady` when the Tasks component calls `addAnnotation` after the workflow step has reset but before the new classification has been created (I think.)

**Comment by srallen** [comment]
@eatyourgreens are the changes to updating the metadata something contingent on this upgrade or something that can be pulled out and done separately?

**Comment by eatyourgreens** [comment]
I’m pretty sure that can be done separately.

**Comment by eatyourgreens** [comment]
#1646 splits out `ClassificationMetadata` into its own file and adds tests for `classification.metadata.update`.

**Comment by srallen** [comment]
Ok, now that part has been split out into its own PR, I'd like to close this and attempt the upgrade in a fresh branch at some point in the near future. Sound good?

**Comment by eatyourgreens** [comment]
Sounds good to me. I’d really like to get the project and classifier onto the same version of MST so that you don’t have to download MST twice when classifying.

**Pull request closed without merging**
