### PR TITLE
Remove test stage from Jenkinsfile

### PR DESCRIPTION
**Pull request by rogerhutchings**
Package: all

Tests are run by Travis, so we don't need a test stage in the Jenkinsfile.

### CODE REVIEW

**Comment by rogerhutchings** [comment]
What I'd actually like to do is have Jenkins ignore anything not on the master branch, but I think @adammcmaster told me once that has to be done in the Jenkinsfile

**Comment by eatyourgreens** [comment]
Jenkins is fixed!

**Comment by rogerhutchings** [comment]
I can't see a reason not to merge this for now...

**Comment by rogerhutchings** [comment]
cc #156

**Pull request merged**
