### PR TITLE
Refresh user project preferences

### LINKED ISSUE #2205: Workflow assignment prompting
## Is your feature request related to a problem? Please describe.

"Back end" for #2143. We need code to manage when to prompt.

## Describe the solution you'd like

User project preferences should be requested for and stored with the actions for:

- Fetching the UPP
- Updating the UPP (will be passed down as prop to classifier)
- Last seen tutorial ids (will be passed down as prop to classifier)
- A computed view for comparing the project assigned workflow to the currently chosen workflow

## Describe alternatives you've considered
We considered putting this logic in the classifier, but discovered that the UPP is being requested for twice and the fact the routing is managed by the app too, the project app is a better choice for the logic

## Additional context
The stats model also relies on the UPP, so consideration needs to be made for this.

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

Package: app-project

Closes #2205

This is the final piece for UPP prompting. I realized that I was getting ahead of myself if I implemented the web socket idea since the Caesar portion of this feature has yet to be completed and I'm unsure if/how it actually will end up being used. So, I decided that implementing polling is much simpler rather than implementing a web socket connection that would be hard to test and take more time to remove if we end up not doing this. We also already keep track of the classification session count, so this was relatively straight forward. 

What this does is refresh the user project preferences stored every 5 classifications. The prompt is connected to the store and fires an effect when the loading state of the UPP changes, which then calls the function which checks if the assigned workflow is different from the current workflow.

This can be tested manually at: https://local.zooniverse.org:3000/projects/srallen086/workflow-assignment-testing

Sign in as `zootester`, password in passbolt. This user is assigned to workflow id `'2334'`, so has access to the beginner and journey labeled workflows. Pick to start with workflow id `'2333'`. You'll be prompted, select "No thanks". Make five classifications, and you should be prompted again. This time select "take me to the next workflow." You should then be routed to `/workflows/2334`. 

Now go back to the homepage and select the beginner workflow. This time select "Don't show me this again." and "No thanks". Do five classifications, and you won't be prompted. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
I'm not sure why tests are failing on CI. They pass locally, so let me investigate this.

**Comment by srallen** [comment]
Actually github actions is having issues right now: https://www.githubstatus.com/

**Comment by goplayoutside3** [comment]
> I'm not sure why tests are failing on CI. They pass locally, so let me investigate this.

When running this branch locally all the test pass, but every time I try to re-run on github, an error is thrown from UserPersonalization:

error

**Comment by srallen** [comment]
It seems the GA issues were a coincidence in this case. There's something indeed going on with that test on CI. @goplayoutside3 thanks for checking that, I'll have a look sometime today.

**Comment by srallen** [comment]
@goplayoutside3 I added an async/await to the setup of that test and that seems to have fixed it. I don't know why it only failed on CI though. 🤷‍♀️

**Review by goplayoutside3 — CHANGES_REQUESTED** [review]
The app works as described for this PR. I logged in as zootester, made 5 classifications, was prompted to go to the next workflow. If I check "don't show this again", I'm not prompted while classifying.

The `AssignmentModal` component is not rendering in storybook though. Everything else looks good!

**Comment by srallen** [comment]
@goplayoutside3 the story is fixed now. I also reorganized it to be under the screens / classify section so it reflects where the code actually lives in the directory structure.

**Review by goplayoutside3 — APPROVED** [review]

**Pull request merged**
