### PR TITLE
Bump react and grommet

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-grommet-theme, lib-react-components, lib-classifier, app-project

Describe your changes:
Fixes the remaining style issues we were seeing with the wrong theme being passed around in context as well as the classname mismatches in app-project. The grommet-icons bump was major version, so some minor changes needed to happen with the custom icons we've written. 

Any remaining style issues should be addressed in their own PRs. Some of them might be Grommet bugs. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by srallen** [comment]
Bummer but not surprising. I'll take a look.

**Comment by eatyourgreens** [comment]
Might just be a case of updating some `.find()` calls that aren't returning shallow wrappers any more.

**Comment by srallen** [comment]
I've fixed the broken tests and updated enzyme and the react 16 adapter.

**Comment by eatyourgreens** [comment]
Excellent. Looks like shallow rendering components that use refs works in this version of enzyme too.

**Pull request merged**
