### PR TITLE
Add an annotation prop to text tasks

### LINKED ISSUE #1951: Sub-Task Popup shows sub-task for most recent Drawing Mark, not currently selected Drawing Mark
## Major Issue

- Expected: when I click on a Drawing Mark (with a sub-task) to select it, the sub-task popup should appear, and the popup should show the sub-task for that **selected Drawing Mark.**
- Actual: the sub-task popup appears, it shows the sub-task for the **newest Drawing Mark**

### Testing

- Go to [blicksams's Transcription Task Testing](https://localhost:8080/?project=11300&env=production) (or any Workflow with Drawing Tasks that have sub-tasks, really)
- click to create your first Text Transcription Line 1️⃣ .
  - The sub-task popup should appear, with an empty text box.
  - for the transcription text, type in "Apple" 🍎.
  - Close the sub-task popup.
- click to create your second Text Transcription Line 2️⃣ .
  - The sub-task popup should appear, with an empty text box.
  - for the transcription text, type in "Banana" 🍌 .
  - Close the sub-task popup.
- click on the first Transcription Line 1️⃣ again.
  - The sub-task popup should appear with some text.
    - Expected: the sub-task should show the text typed in for the first line 1️⃣ , which is "Apple". 🍎 
    - ❌ Actual: the sub-task shows the text typed for the second line 2️⃣ , which is "Banana". 🍌 
  - Type in some new text, such as "Avocado" 🥑 
  - Close the sub-task popup.
- Submit the classification and monitor the submitted data.
  - Expected: the classification should submit annotation data that looks like `["Avocado", "Banana"]`
  - Actual: the classification submits annotation data that looks like `["Apple", "Avocado"]`

Tested on localhost with macOS + Chrome (on normal and with touchscreen emulation) on [blicksams's Transcription Task Testing](https://localhost:8080/?project=11300&env=production), which features a text transcription task.

**Advanced Testing:**

- On a new Subject, create the first Text Transcription Line 1️⃣ 
- Create the second Text Transcription Line 2️⃣ 
- Delete the second Text Transcription Line 2️⃣ 
- Click on the first Text Transcription Line 1️⃣ 
  - Expected: the sub-task popup should appear with the first line's sub-task. 1️⃣ 
  - Actual: classifier crashes because it's trying to access the sub-task of a deleted Mark.

### History

This issue was discovered while testing PR #1950 . After additional tests, I discovered this problem exists as far back as commit dc114e3, so this problem doesn't seem to have been introduced by the refactor in #1922 / #1921 (which 1950 was a response to).

### Status

n/a, to be updated

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add the annotation prop to text tasks, and use that to set the value of the text input box.

Package:
lib-classifier

Closes #1951.
Test URLs in the dev classifier:
Text task: https://localhost:8080/?project=908&workflow=3398
Transcription task: https://localhost:8080/?project=11300&env=production

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I can't remember why the text task component behaves differently to other tasks. Did having it update its own props cause focus problems (focus being lost if the text input is being constantly re-rendered?)

**Review by shaunanoordin — CHANGES_REQUESTED** [review]
## PR Review

Package: `lib-classifier`
Also see: PR #1952

This PR attempts to fix #1951, in which the sub-task popup will always show the sub-task of the _most-recently created_ mark, not the _currently selected_ mark.

Testing for 1951 looks good (the ["Apple", "Banana"] to ["Avocado", "Banana"] test), and it looks much better than #1952 where the new "cannot proceed to next step" but was found.

⚠️ However, this PR does appear to introduce a new bug, where I'm unable to proceed to the next step if the task is a _Text Task._

### Testing

Testing is mostly similar to #1952 with one major addition.

Testing on localhost + macOS + Chrome on projects:
- [blicksams's Transcription Task Testing](https://localhost:8080/?project=11300&env=production) - features a text transcription task
- I Fancy Cats - features an ellipsis tool (with sub-task) and point tool (no sub-task)
- [darkeshard's Transformers workflow](https://localhost:8080/?env=staging&project=1651&workflow=2628) - features a Point Task (with sub-task) and a second Point Task (no sub-task)
- ➕ [Jim's Text Task](https://localhost:8080/?project=908&workflow=3398) - features a single Text Task

"Avocado, Banana" Test Steps:
- On any of the drawing tasks with sub-tasks, make Mark 1 and give it a sub-task value of, say, "Apple"
- make Mark 2 and give it a sub-task value of "Banana"
- select Mark 1 (expectation: I see the value "Apple") and change it to "Avocado"
- Proceed to submit the Classification
- Expectation: submit a classification where, for that drawing task, a value of ["Avocado", "Banana"] is submitted

Test Results 1:
- ✅ the Transcription Task Testing, I Fancy Cats, and Transformers projects all pass the "Avocado, Banana" test.
- Additional tests to see what happens if I submit blank annotations also work great 👍 
- Overall, these guys projects look fine

Test Results 2:
- ❌ for Jim's Text Task, I'm unable to make any classifications.
- Entering any text into the text input (or no text, actually) and then clicking "Done" results in the classifier crashing with the following error:
```
Uncaught Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'TextAnnotation', Path upon death: '/classifications/resources/ckiuvkkkl00003g63bu3n706f/annotations/ckiuvkkld00013g63txf2pldf', Subpath: '', Action: '/classifications/resources/ckiuvkkkl00003g63bu3n706f/annotations/ckiuvkkld00013g63txf2pldf.update()'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.
```

### Status

Again, I'm not sure what's happening here. It seems that the changes work great if the TextTask is part of a sub-task popup, but not when it is its own Task in the task panel?

I'm now wondering if I need to have 1953 and 1952's changes running together to make sure everything works; that'll be next on my testing ToDo.

**Comment by shaunanoordin** [comment]
In any case, I'll continue investigating this in 2021. For now, good night!

**Comment by eatyourgreens** [comment]
I wonder if that error is why the text task is set up differently from all the other tasks?

**Comment by eatyourgreens** [comment]
That store crash should be fixed now. The text task was calling `annotation.update(value)` on unMount, which happens after the classification has been submitted. I can't remember why it was doing that, but removing it fixes the bug. Annotations are updated when the text box changes, or after you press one of the modifier buttons.

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

This PR update is looking good! I ran through all the tests described in https://github.com/zooniverse/front-end-monorepo/pull/1953#pullrequestreview-555869581 and everything is passing

- ✅ when selecting a drawn Annotation with a Sub-Task, the Sub-Task popup correctly displays the selected Annotation. (Instead of the most recent annotation)
- ✅ the single Text Task works as expected

### Dev Notes

Code changes look good, and I honestly don't know why DefaultTextTask had previously called `updateAnnotation()` when unmounting. Some tests I've performed to see if deleting `onUnmount` breaks anything (TL;DR: it doesn't)
- Apple, Banana tests for drawing annotation with sub-tasks work perfectly
- Going Next/Previous on a 3-task workflow (all Text Tasks) works perfectly; moving back from Text Task 3 to Text Task 2 shows that the content of Text Task 2 remains correctly preserved.

I'm going to say the onUnmount code might have been a legacy of an earlier implementation, maybe? In any case-

### Status

LGTM 👍

**Pull request merged**
