### PR TITLE
Style SVG subjects with touch-action: pinch-zoom

### LINKED ISSUE #5303: Data selection task broken in the classifier on touch devices
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
Data selection is broken on touch devices. I can't tap and swipe to select. 

The storybook works fine. 

## To Reproduce
Tap and swipe here to select a range of data:

https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3762?env=staging

## Expected behavior
Tap and swipe in the storybook to select a range of data. 

https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/subject-viewers-scatterplotviewer--x-range-selection

### Smartphone (please complete the following information):
 - Device: iPhone XS 
 - OS: iOS 16
 - Browser: Safari 
 - Version: 16

### LINKED ISSUE #5313: Panning flipbook subject images doesn’t work on touch devices.
Panning a zoomed subject image doesn’t work on touch devices (tested in mobile Safari on iOS 16.) It does work in iOS on PFE.

To reproduce this, zoom in to a subject image on your phone, switch to 'panning' mode in the toolbar, then tap and swipe to drag the zoomed-in image.

https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy/classify/workflow/1610

It does work on PFE:
https://master.pfe-preview.zooniverse.org/projects/zooniverse/wildcam-gorongosa/classify

_Originally posted by @eatyourgreens in https://github.com/zooniverse/front-end-monorepo/issues/5110#issuecomment-1692647374_

### PR DESCRIPTION
**Pull request by eatyourgreens**
Style the root `<svg>` element with [`touch-action: pinch-zoom`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) for SVG subject viewers. This:
- allows data to be selected by tapping and swiping on touch devices for light curve data.
- allows multi-image and data subjects to be panned, after zooming in, on touch devices.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier

## Linked Issue and/or Talk Post
 - closes #5303.
 - closes #5313.

## How to Review
Open a data subject on a touch device. I used an iPad on BrowserStack and my test workflow for JSON light curves:
https://local.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/classify/workflow/3762?env=staging

You should be able to select data by tapping and swiping. After zooming in, and switching from 'annotate' to 'pan' mode, you should be able to pan the subject left/right by dragging with your finger.

To test the changes to SVG images, visit Wildcam Gorongosa, zoom in, switch to 'pan' mode and then  drag the image with your finger.
https://fe-project-branch.preview.zooniverse.org/projects/zooniverse/wildcam-gorongosa/classify/workflow/11459

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by goplayoutside3** [comment]
I found that running this branch locally on my desktop made the dragging lag worse. In the following recording, each time my mouse moves across the subject image, I'm clicking down to drag and the subject hardly moves at all. At one point the image gets stuck following my cursor when I had released my click, too. Is this your experience testing on desktop too?

https://github.com/zooniverse/front-end-monorepo/assets/23665803/93a0a220-efed-4e33-bed4-b796e990d1b9

**Comment by eatyourgreens** [comment]
That's unexpected, since this only changes the `touch-action` styles. I've only tested on an iPad so far.

**Comment by eatyourgreens** [comment]
I recorded this on this branch, with a production build of the project app. Performance isn't great, but it's no different than the production release.


https://github.com/zooniverse/front-end-monorepo/assets/59547/98d7ef50-a31d-46ed-8333-0d26ebe5d306

**Comment by eatyourgreens** [comment]
Here's the dev classifier on this branch, so running in strict mode. Performance isn't great, but again no different from the main branch (as far as I can see.)


https://github.com/zooniverse/front-end-monorepo/assets/59547/48f3b473-a382-4885-a173-67fbcd89082e

**Comment by eatyourgreens** [comment]
I've moved #5313 into its own issues, so that problems with touch are separate from performance problems with pointer events.

**Comment by eatyourgreens** [comment]
I did some more testing on my phone, and I Fancy Cats doesn't have problems on staging either. I can reproduce the touch bug on Gravity Spy and Wildcam Gorongosa. It seems to be triggered for multi-image subjects. Panning a zoomed image doesn't work on touch devices.

**Review by goplayoutside3 — APPROVED** [review]
Looks good! My above comment was due to drag behavior fixed by https://github.com/zooniverse/front-end-monorepo/pull/5326, so I retested this branch on my phone's Safari 👍

**Pull request merged**
