### PR TITLE
Fix survey task characteristics filters

### LINKED ISSUE #2323: Filter buttons not working properly
## Package

Variable Star Light Curve Viewer

## Describe the bug
In Workflow 16454, I have created a survey task using the new frontend monorepo where we have 5 different filters associated with the survey task. When I click on the icons for the "Luminosity" filter it toggles the options for the "Amplitude" filter. I cannot successfully choose the various Luminosity options. 

## To Reproduce
1. Go to https://www.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/classify/workflow/16454?demo=true
2. Click on Filter
3. Scroll down to "Luminosity" and try to select any of the icons
4. See error (i.e., that "Luminosity" cannot be selected)

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

Stellar Sleuths project with workflow 16454

## Expected behavior
The Luminosity icons should be used to filter sources based on their expected luminosity.

## Screenshots
N/A

### Desktop (please complete the following information):
 - OS: OSX 11
 - Browser: Firefox
 - Version: 90.0

## Additional context
N/A

### PR DESCRIPTION
**Pull request by mcbouslog**
Package:
- lib-classifier

Closes #2323.

For testing (note this is the **production** project):
- https://local.zooniverse.org:8080/?project=4878&workflow=16454&env=production&demo=true

Describe your changes:
- refactors CharacteristicSection options, which uses Grommet's RadioButtonGroup, from array of characteristic value ID strings to array of objects including a unique ID (characteristic ID and value ID)
- refactors FilterStatus filter buttons with unique key (characteristic ID and value ID)
- update FilterStatus test

Notes:
- the bug occurred due to multiple radio inputs with the same `id` (i.e. "LOW"), even though each input was in a different RadioButtonGroup (each RadioButtonGroup with a unique name). So subsequent "LOW" filter inputs onChange would be called with the first instance's characteristic ID
- I'm not sure if this is a Grommet (multiple RadioButtonGroups with the same option values) RadioButtonGroup issue I should try to recreate in a CodeSandBox and report? I'm happy to, but want to check first

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by srallen — APPROVED** [review]
That sounds like a possible Grommet bug, but better guaranteeing that the ids are unique anyway is a good thing, so I wouldn't make investigating that a high priority.

**Comment by adamamiller** [comment]
This was supposed to close #2323 but I am still experiencing the same issue, where I click on the luminosity filter and it selects the amplitude filter. 

If the best fix in this case is to use different words for each filter (instead of calling everything "low" or "high") then we can do that. Please let us know what's best.

**Comment by srallen** [comment]
@adamamiller The fix is deployed to staging but not production yet. We'll let you know when it's deployed.

**Comment by mcbouslog** [comment]
@adamamiller - the fix is now deployed, should filter as expected, but do please let us know if not. Thanks,

**Pull request merged**
