### PR TITLE
Temporal rotate rectangle tool

### LINKED ISSUE #2151: Create TemporalRotatingRectangle Drawing Tool
## Package
`lib-classifier`

## Describe the solution you'd like

Create a TemporalRotatingRectangle Drawing Tool where it's properties are:

- x: x position of the vertex closets to the origin before rotation
- y: y position of the vertex closets to the origin before rotation
- width: Full width of the rectangle (along +x axis) before rotation
- height: Full height of the rectangle (along +y axis) before rotation
- angle: Degrees, RHC, domain (-180, 180)
- displayTime: mm:ss:milsec Video time when drawing tool was created

## Describe alternatives you've considered
A discussion was created for team-member's input.
[Discussion#2147](https://github.com/zooniverse/front-end-monorepo/discussions/2147)

### PR DESCRIPTION
**Pull request by ErikOstlund**
Package: `lib-classifier`
Project: `Video Annotator`
Project [URL](https://github.com/zooniverse/front-end-monorepo/projects/13)

Closes #2151 

## Changes
This PR is for extending the RotateRectangle drawing tool to a new TemporalRotateRectangle drawing tool.
The TemporalRotateRectangle uses the RotateRectangle component but the following new files were created:

- TemporalRotateRectangle Marks model
- TemporalRotateRectangle Tools model

The TemporalRotateRectangle send the following data to our api:
*New properties:
`displayTime`: Number between 0 and 1 having 3 decimal places. This represents the current position on the video slider.
`displayTimeStamp`: Human readable timestamp formatted as ss:ms
image

## Testing
In the front-end-monorepo folder, run yarn bootstrap to build the packages. Then cd packages/lib-classifier and run yarn dev.
Project URL: https://localhost:8080/?env=production&project=13789&workflow=16843

### CODE REVIEW

**Comment by goplayoutside3** [comment]
Looks good! I'm able to run the Temporal Rotate Rectangle tool locally, and the tests are passing 👍 

However, I have one question about design that may or may not be relevant to this particular PR. Maybe something to think about in the future:

As a user I'm confused about the three UI states of a drawn rectangle. In the attached picture, I think the first is a completed rectangle, the second is a rectangle actively being edited, but the third UI state with an extra outline shows up when I scrub along the time slider. Does the outer rectangle represent focus? Could the Temporal Rectangle Tool be rendered in a color not so similar to the focus outline?

rectangle

**Comment by ErikOstlund** [comment]
@goplayoutside3, that does represent focus. This is not tool specific, but does seem to only happen for `temporal` drawing tools. I will pull @eatyourgreens in to see how this affects accessibility and what our options are.

**Comment by eatyourgreens** [comment]
That is weird. It's not a bug with the changes here, but I think it's a bug in the code that autofocuses drawing tools. The active mark seems to steal focus, even if you're operating a button or control elsewhere on the page. When you use the scrubber, in Chrome at least, I'd expect that keyboard focus would follow the mouse and move to the slider control.

I think it would only be an accessibility issue if it stops you from scrubbing with the keyboard. I'd expect that the scrubber should respond to the left/right cursor keys, when the slider has focus (Chrome and Firefox might differ as to whether this happens when you click on the slider.)

**Comment by eatyourgreens** [comment]
@goplayoutside3 Good point about not allowing project owners to choose a colour that could be confused with the focus ring. [WCAG 2.4.7](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html) says keyboard focus should be clearly visible, and I'd interpret that as meaning the focus inidicator should be unambiguous.

**Review by goplayoutside3 — APPROVED** [review]
@eatyourgreens that makes sense! @ErikOstlund since the focus bug isn't blocking to this specific tool, the rests looks good to me, and probably best to track the focus question in a separate issue 👍

**Comment by ErikOstlund** [comment]
A new issue (#2272) was created to address the focus issue.

**Pull request merged**
