### PR TITLE
[Security] Upgrade lerna

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrade lerna to 4.0. Includes a security update for `glob-parent`.

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Linked security report: https://github.com/zooniverse/front-end-monorepo/security/dependabot/yarn.lock/glob-parent/open

**Review by mcbouslog — APPROVED** [review]
LGTM.

I think https://github.com/zooniverse/front-end-monorepo/blob/master/lerna.json#L2 should be updated to reflect `4.0.0` as well?

**Comment by eatyourgreens** [comment]
I’m not sure what the version field does. Lerna docs say it’s a version number for the repository. It doesn’t match our current lerna version either.

https://github.com/lerna/lerna#lernajson

**Comment by eatyourgreens** [comment]
Oh wait, sorry, the `lerna` field is deprecated. We can ignore it.

**Pull request merged**
