### PR TITLE
Bump Grommet

### PR DESCRIPTION
**Pull request by mcbouslog**
Package: fe-project, lib-classifier, lib-grommet-theme, lib-react-components

Upgrades Grommet to v2.6.6, which includes:
- fixed theme issue on grommet button
- DataTable overflow issue
- active theme support
- custom drop overflow

Might help with a few little issues we're having, at minimum good to stay current.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by srallen** [comment]
I'm not sure why coveralls is now complaining about coverage dropped. I looked into the report and I don't see any files with actually decreased coverage.

**Comment by srallen** [comment]
> That said, I'm not sure of which specific Grommet-theme-button issues or other UI quirks this update was intended to resolve (do we have links to issues/screenshots?), so it might be a good idea to get a second set of eyes on this.

The update isn't specific to known issues we have, but the hope is that the latest might fix the keyboard focus issue with the DropButton (being used as a tooltip) as seen in #355, despite no mention of it in their changelog as well as just trying to stay current.

**Comment by mcbouslog** [comment]
@shaunanoordin it looks like you're using Chrome? interestingly, also with Chrome, I don't see the "Finished for the day?" issue.

**Comment by srallen** [comment]
@mcbouslog I'm not seeing it either. @shaunanoordin if you're still seeing it, could you open an issue? Thanks!

**Pull request merged**
