### PR TITLE
Disable mark and update tests

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

Follow up for #2083

I spoke with @snblickhan and the expected behavior is that the previous mark is disabled, but available for reference as to what the original position was. A goal of the feature is to make clear the difference between marks from other volunteers, aka previous marks or low consensus reduction marks, and marks the volunteer makes during the session. To that end, as for the other question that came up:

> I also find it a bit confusing that clicking a magenta line opens the popup with previous annotations attached to the mark, but clicking the green line opens the popup with the regular text editor. I guess that's so you can change the line that you previously chose? If you made a mistake, and want to choose a different line of text, you'd be expected to delete the green line and start again from the magenta line?

The expectation is that if you want to start over that the volunteer would delete the mark they created and start over with the previous mark. To aid in understanding the color meanings and different marks, I'll be opening another PR to add tool tips to the green and blue marks. 

This can be manually tested with the dev classifier at https://localhost:8080/?project=11300&env=production&demo=true. Create a new mark from a previous mark (pink line), move your new mark (green line) and the original pink line is disabled. 

Here's a screenshot of how this might go:

Screen Shot 2021-05-03 at 2 57 17 PM

Say other volunteers didn't follow directions and only transcribed a single word, not the complete line, so you start with the previous mark to create a new mark, and make adjustments with the new mark. The original previous mark (pink) has now reduced opacity and has no event handlers, along with `aria-disabled` set to `"true"`. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
I've noticed some more clean up that can happen with this, so putting this into draft status temporarily.

**Comment by srallen** [comment]
There appears to be an issue with the `TranscribedLines` story where the subtask for creating a new mark from the previous low consensus mark isn't working. This is happening with the current deployed storybook, so not caused by this PR: https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/drawing-tools-transcribedlines--default

Since this issue is previously existing and as far as I can tell, not affecting actual projects and so is isolated to the storybook story, I'd like to address it separately.

**Comment by srallen** [comment]
This is ready for review again.

**Review by eatyourgreens — APPROVED** [review]
Looks good!

**Pull request merged**
