### PR TITLE
Refactor multi-frame viewer with Media component, thumbnail service

### LINKED ISSUE #1462: Each frame in the carousel should be a true thumbnail generated by thumbnails.zooniverse.org.
If the thumbnail request cannot be complete, gracefully fall back to empty frames.

### PR DESCRIPTION
**Pull request by mcbouslog**
Package: lib-classifier

Closes #1462. 

Describe your changes:
- refactors frame carousel to use Media component from `lib-react-components`, which uses thumbnailer service
- adds placeholder icon for frame media
- refactors and fixes issues with multi-frame viewer stories

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by mcbouslog** [comment]
Added a placeholder icon, the `<More />` icon from `grommet-icons`, I'm not sure about. I haven't styled the icon other than defaults that come through from the theme:

Screen Shot 2020-11-28 at 4 25 14 PM

Screen Shot 2020-11-28 at 5 49 18 PM

@beckyrother - let me know what you think, thanks!

**Comment by shaunanoordin** [comment]
## Quick Review

Package: `lib-classifier`

- Basic user testing looks good.
  - **Testing URL:** https://local.zooniverse.org:8080/?env=production&project=8143&workflow=11225
  - I'm using Skink Spotter NZ since they have a buncha photos per Subject
  - mac OS 10 + Chrome 87 on localhost

Screen Shot 2020-11-30 at 19 06 56

_PR version_

Notable changes:
- Thumbnails in the MFV are now actually thumbnails instead of full size images.
  - Side note: Thumbnails will always try to "contain" ("fit biggest dimension") into a 40x40 space (as opposed to "stretching to fit" or "fit smallest dimension"), so in practice the thumbnail from Skink Spotter NZ are 40x30 images. I'm mildly curious to see how long images (e.g. Anti-Slavery Manuscript pages render in this space) look like in the MFV.
- Multi-frame viewer correctly controls overflow when there are too many thumbnails. There's a scrollbar now if there are too many tiny photos to fit the space available!
  - Clicking the Next/Prev buttons correctly scrolls the view up/down to ensure the active thumbnail has visible focus.
- The "..." dot dot dot icon appears in the place of a thumbnail if it's still in a loading state.

Screen Shot 2020-11-30 at 19 14 07

_PR version: thumbnails are being loaded_

Screen Shot 2020-11-30 at 19 08 09

_Master version, for comparison_

I couldn't test anything in Storybook unfortunately; I think something borked Storybook for `lib-classifier`. 🤷‍♂️ 

Anyway, just wanted to say that functionality looks good. 👍 I'll have to take a peek at the code changes later.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: `lib-classifier`

This PR makes the Multi-Frame Viewer component work goodlier.

- Images in MFVs are now actually tiny 40x40 thumbnails (from the Zooniverse Thumbnail service) instead of huge 4000x4000 images scaled down to fit.
- UI element added: "thumbnail is loading" icons. 
- UI fixed: MFV panel correctly handles large amounts of thumbnails with a scrollbar overflow

Code looks good, tested with macOS10 + Chrome on localhost, see https://github.com/zooniverse/front-end-monorepo/pull/1916#issuecomment-735990353 for full functionality + testing report.

### Dev Notes

- main testing URL is, as mentioned, Skink Spotter NZ: https://local.zooniverse.org:8080/?env=production&project=8143&workflow=11225
- Curiosity musings (does NOT affect this PR's review):
  - I have _no idea_ what happens when a multi-image Subject also has a non-image Subject. e.g. Chimp & See, which has 1 video media file followed by a 10+ image media files.
  - I tried looking at https://local.zooniverse.org:8080/?env=production&project=7850&workflow=11941 (Chimp & See) but I can't tell if the Classifier crashes because the Survey task isn't supported or if it's because it's trying to show a video media file.
- Storybook doesn't work at the moment for me - running `yarn storybook` leads to a slew of errors in the terminal, and the webpage crashing into white.

### Status

I'm going to give this a 👍 for functionality and user testing, though I think this PR's still waiting for a review from Sarah and Becky before it's good to go? In any case: woo! 🎉

**Review by beckyrother — CHANGES_REQUESTED** [review]
This is great! Are the loading images smaller than 40x40 for a reason? I'd suggest making them the same size and using [Light Teal](https://projects.invisionapp.com/dsm/zooniverse/primary-brand/asset/colors/5bbd0df6ef5a3e0010db9c69) with white icon (which looks great btw!) so they don't stand out so much. 
Other than that it looks great! Thanks Mark!

**Review by beckyrother — APPROVED** [review]
This looks great! Thank you Mark!

**Comment by mcbouslog** [comment]
Thank you @shaunanoordin and @beckyrother! My apologies I've been sitting on an update!
Here are some updated screenshots:
Screen Shot 2020-12-16 at 3 02 25 PM
Screen Shot 2020-12-16 at 3 02 51 PM

**Review by srallen — APPROVED** [review]
LGTM. Since the stories are fixed in this too, mind deploying the updated storybook once this merges? Thanks!

**Pull request merged**
