### PR TITLE
Restructure component library code

### PR DESCRIPTION
**Pull request by rogerhutchings**
Package: `lib-react-components`

- Moves old components to `legacy` folder for reference
- Moves new components to `src` folder
- Adds the `ZooniverseLogo` to the `ZooHeader` component
- Adds the `ZooniverseLogotype` to the `ZooFooter` component
- Fix story paths

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by srallen** [comment]
Actually the build script is fine. Ignore that comment. Just the main entry needs fixing.

**Comment by srallen** [comment]
Side question: Once we get this published, should we remove committing the build output?

**Comment by rogerhutchings** [comment]
- I've changed `main` to point to `src/index.js` for now, although I expect that to change again once there's a bundler added to build the compiled version.
- I think once we can publish automatically to npm, we shouldn't commit any compiled code we don't need to.

**Comment by srallen** [comment]
I'm having a problem now, also seeing on master, of the libraries 404ing with the grommet-theme package when running `lerna bootstrap` the full log file looks like it's trying to install from npm. I'm not sure why yet. I think this is likely fine though. The issue may be with the lerna version update.

**Comment by srallen** [comment]
Just as an aside, running `lerna link` in the grommet-theme folder seemed to have fixed it.

**Pull request merged**
