### PR TITLE
app-content-pages: Add max width and elevation elements

### PR DESCRIPTION
**Pull request by goplayoutside3**
~~⚠️ This contains https://github.com/zooniverse/front-end-monorepo/pull/5488 please review that one first.~~

## Package
app-content-pages

## Linked Issue and/or Talk Post
Toward: https://github.com/zooniverse/front-end-monorepo/issues/5476
Project board: https://github.com/orgs/zooniverse/projects/40
Figma design: https://www.figma.com/file/zN9InDg8CTk2vnWp406moK/About-Pages

## Describe your changes

I created a page container element in layout.js with a max-width and elevation elements based on the Figma design above. It applies to both Team and Publications pages, and will be used in future root About, Resources, and FAQ.

Here's a screenshot:
Screenshot 2023-10-30 at 5 27 44 PM

## How to Review

- Run app-content-pages locally and check out https://local.zooniverse.org:3000/about/publications

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)

## New Feature
- [ ] The PR creator has listed user actions to use when testing the new feature

### CODE REVIEW

**Comment by goplayoutside3** [comment]
@seanmiller26 Tagging you for design review of the screenshot above, and then I'll apply it the Project About pages as well. Happy to demo in-person this week if needed too.

I hardcoded the max-width as 1440px for now, but I'm wondering if it should be defined in `rem` instead. However, 1rem still equals 14px in FEM, so might hold off until typography changes are made to define 1rem = 16px.

**Comment by eatyourgreens** [comment]
1 rem is 16px on my browser. It's set by the end user, not by us.

**Review by eatyourgreens — APPROVED** [review]
Code changes look good, pending design approval. I'd also consider using `90rem`, rather than `1440px`, so that the page sizes correctly with larger text.

**Comment by goplayoutside3** [comment]
> 1 rem is 16px on my browser. It's set by the end user, not by us.

True! I didn't describe my thoughts accurately 😆  For clarity, I was thinking along the lines of planned font-size adjustments to FEM so that paragraphs are 16px instead of 14px. This adjustment (suggested by Sean) is to bring paragraph font-size in alignment with the default browser 1rem = 16px, making breakpoints easier to define in `rem`, too.

You're right though, that 1 rem is determined by the user. I was hesitant to define a breakpoint in `rem` prior to making the mentioned font-size adjustments, but it's probably fine to do so in this PR.

**Comment by eatyourgreens** [comment]
>You're right though, that 1 rem is determined by the user. I was hesitant to define a breakpoint in rem prior to making the mentioned font-size adjustments, but it's probably fine to do so in this PR.

That's a good point. If paragraphs etc. are set in px, then text won't enlarge as the size of 1rem increases. You can test this in the DOM inspector by setting `font-size: 20px` on the `html` element (ie. explicitly set 1rem to 20px.) Elements sized in rem will get bigger, but text sized in px won't.

**Comment by seanmiller26** [comment]
The screenshot looks great. I want to clarify the definition of max-width used here since I can't test it out locally. The white container width should be a constant 1440px, so it shouldn't shrink below that size on window change. The margins should then be 30px on both sides as demonstrated here:

Screen Shot 2023-10-31 at 11 37 37 AM
Screen Shot 2023-10-31 at 11 37 44 AM
Screen Shot 2023-10-31 at 11 39 09 AM



We can definitely revisit the REM vs px debate in the near future.

**Comment by goplayoutside3** [comment]
Thanks @seanmiller26! This change focuses only on the grey elevation and the max-width of the big white container. There will be a separate PR to bring margins of the inner-page layout into alignment with the Figma design.

**Comment by seanmiller26** [comment]
Right, sorry just clarifying the language behind "max-width". Can you confirm that the big white container does not reduce below 1440px width?

**Comment by goplayoutside3** [comment]
Yes that's correct 👍

**Pull request merged**
