### PR TITLE
Use an uncontrolled textarea for text transcription

### LINKED ISSUE #1476: Text Task keeps losing focus after each character typed
## UI Bug

Package: `lib-classifier`

On the Classifier, when given a Text Task, the text input will lose focus after every character typed.

### Testing and Reproduction

- With any project, create a simple Workflow with a single free-form Text Task.
- On the Classifier, go to that Workflow.
- Attempt to type in a sentence, such as "good morning", in the Text Task's text input. _Using a keyboard, of course._
  - Expected: the text "good morning" appears in in the text input.
  - Actual: the first letter of the sentence, "g", appears in the text input, but then the text input loses focus, so all other input from the keyboard is ignored (or caught by some other component.)

Tested on macOS 10 + Chrome on commit master (commit 481e121773d868065e9de328ee0b853e09e2a929)

### Status

Serious UI bug, but... _not urgent_ at the moment since no live projects on the monorepo uses the Text task, AFAIK.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Package:
lib-classifier

Closes #1476.
Remove the annotation prop from `TextTask`, so it doesn't re-render on every annotation change.
Use `defaultValue` (making the textarea an uncontrolled input.)
Get the current text value from the `textArea` ref.
Use `useEffect` to update the current task annotation on component unmount.
 
This PR essentially reverts the changes to `TextTask` from #1409.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
I can have a look after I do freshdesk this morning.

**Comment by eatyourgreens** [comment]
Good catch. I think I've only tested this on a workflow with multiple text tasks.

**Comment by eatyourgreens** [comment]
When you press Done, the component doesn't unmount until after the classification has been sent. I didn't think of that.

**Comment by eatyourgreens** [comment]
I've updated it to update the annotation on blur and on unmount, and I've also keyed the rendered task by `annotation.id`.

**Comment by eatyourgreens** [comment]
On second thoughts, I've switched this back to updating the annotation when the text area changes. You can try it out, with text tagging, on http://localhost:8080/?project=908&workflow=3398.

**Comment by eatyourgreens** [comment]
Unrelated to the changes here (I think): transcribing from the keyboard is impossible. I can't transcribe, tab to the Done button, submit and start typing for the next subject.

**Pull request merged**
