### PR TITLE
[VSLCV] Series focus control

### LINKED ISSUE #1429: [VSLCV] Add focus toggle to composite viewer
**Package** lib-classifier

**Describe the solution you'd like**

TODO: add information

**Additional context**

Design: https://projects.invisionapp.com/d/main#/console/17294981/360635448/inspect

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package:

Closes #1429

Describe your changes:
**PRs #1526 and #1527 need to be merged first**. This adds the functionality for toggling UI focus on data series in the variable star viewer. WIP because this still needs some specs for the changes in `Controls`, but there's some setup for nock in #1527 that I'd like to use, so that comes first.

This should be manually testable in the storybook, but here's also a gif demonstrating it:

Feb-19-2020 14-46-34

And a close up screenshot of the hover/focus state because the gif doesn't show it well:

Screen Shot 2020-02-19 at 2 49 50 PM

Indesign links for comparison:

Design for checked/unchecked style state: https://projects.invisionapp.com/d/main#/console/17294981/403043950/preview

Design for hover/focus state: 
https://projects.invisionapp.com/d/main#/console/17294981/405498288/preview
https://projects.invisionapp.com/d/main#/console/17294981/405498289/preview

A couple things to note here:
- ~The original storybook I setup wasn't connected to the container, but now it is so we can manually test the functions there. This includes some math that isn't added yet to calculate the JSON for the bar charts and the scatter plot for the phased view, so that's why there's no data displaying there now.~ Moved to #1527 so I can reuse this storybook setup for implementing other features.
- ~The red and and orange are from the fallback colors picked from the theme drawing tool colors. In reality, the variable star data will be setting this to a red and blue that has meaning for the data. For demonstration purposes here, though, the red and orange should be fine.~ Blue is being used with the example variable star data since #1526 merged.
- Other functions will be styled work as I implement the interactivity, so please just check the focus function and style for this

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
@wgranger this is ready for final code review. Thanks!

**Comment by srallen** [comment]
@wgranger please do let me know if there's a keyboard issue for this particular feature, just with the same caveat that this PR is only focused on building out this one. Then, when all the features are generally built out, I'd like to do an audit to determine if any issues remain with design, accessibility, etc. 

Also, boo Safari.

**Comment by srallen** [comment]
@wgranger I've fixed the Safari alignment issue as well as the focus style state for keyboard users.

**Comment by wgranger** [comment]
Looks like the alignment issue is fixed in Safari, and I can see focus now when I tab into the filter buttons; however, I am not able to toggle the filter views once I have keyboard focus on each button. I'm assuming "enter" is the button I should be using?

**Comment by eatyourgreens** [comment]
Space is the standard control for buttons, but we have had requests to add support for Enter too (since noone ever remembers that buttons use the spacebar.)

**Comment by srallen** [comment]
Yes, it should work with space as that's the standard. I'd like to hold off on adding any additional support for keyboard until after I implement some of the zoom customizations if that's alright.

I'll get this merge conflict today though.

**Pull request merged**
