### PR TITLE
Panoptes.js: Tutorials resource

### LINKED ISSUE #63: panoptes.js: Tutorials resource
**Package** lib-panoptes-js

**Feature or Issue Description**
Add request helpers for the tutorials resource

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-panoptes-js

Closes #63.

Describe your changes:
This adds the helper functions for `GET` requests for the tutorial resource.

I also snuck in a fix for the exports for the projects resource helpers too. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by srallen** [comment]
I still need to write docs, but the code can be reviewed.

**Comment by srallen** [comment]
Docs are now added.

**Comment by rogerhutchings** [comment]
This looks good to me. My one (non-blocking) comment is on async syntax used. I know we can't use `async/await` in the code, but we can in docs and tests, and we should probably encourage users of the library to use it where possible since it's that much easier to read.

**Comment by srallen** [comment]
Just double checking `async/await` support and node >=8 and all the browsers support it now except for IE. I could switch to that in a separate PR and we can add a polyfill as needed if we'll go forward with IE support.

**Pull request merged**
