### PR TITLE
Add the TranscriptionLine icon

### LINKED ISSUE #1452: Transcription Line icon
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**
The transcription line tool is a text transcription specific variant of the line drawing tool. It has slightly different UX and and visual design to indicate the start and end of the lines. To this end, it should have a different icon to indicate its function. 

The icon is: https://github.com/zooniverse/front-end-monorepo/pull/1369#issuecomment-568001353

**Describe the solution you'd like**

The icon was attempted to be added in #1369 but it did not render correctly: https://github.com/zooniverse/front-end-monorepo/pull/1369#issuecomment-575513064

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package:

Closes #1452. I've added the icon for the transcription line tool. The tool itself can be used either with the drawing task or with the transcription task. The main difference is that the color can be set by configuration with the drawing task, whereas in the transcription task, since color has state meaning, it is set to be the actively transcribing color (I think this is supposed to be a blue color rather than the green it is now, so I'm going to fix this in a subsequent PR). I also included the addition of the icon background color @beckyrother asked for in https://github.com/zooniverse/front-end-monorepo/issues/1052#issuecomment-516686181

Here how it looks in the storybook:

drawing task, unchecked:
Screen Shot 2020-04-07 at 2 19 11 PM

drawing task, hover and focus state:
Screen Shot 2020-04-07 at 2 18 45 PM

drawing task, checked: 
Screen Shot 2020-04-07 at 2 18 10 PM

In context as transcription task (http://local.zooniverse.org:8080/?project=1764&workflow=3392):
Screen Shot 2020-04-07 at 2 33 24 PM

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [x] Has a storybook story been created or updated?
- [x] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
@beckyrother I just realized I merged this without approval from you. I saw the green tick and thought all was good. I'm sorry. Please let me know if anything needs tweaking and I'll open another PR.

**Comment by beckyrother** [comment]
Thanks @srallen. This is a terrible icon and I take full responsibility for that. Can I make a new icon?

**Comment by srallen** [comment]
@beckyrother Yes, definitely, it just need to be an svg with a viewbox of `0 0 100 100`. I'll reopen https://github.com/zooniverse/front-end-monorepo/issues/1452 and you can posted an updated one there?

**Comment by beckyrother** [comment]
@srallen thank you! Should have thought about it yesterday, sorry.

**Pull request merged**
