### PR TITLE
fix(app-project): data-fetching for assigned workflow level

### LINKED ISSUE #6217: project build error: missing useEffect dependency for assigned workflows
## Package
_Choose from the list:_
- [ ] app-content-pages
- [x] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
```
./src/hooks/useAssignedLevel.js
35:5  Warning: React Hook useEffect has a missing dependency: 'checkAssignedLevel'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
```

Missing dependencies in effect hooks lead to subtle bugs that can be hard to track down eg. the recent problems with the `AnimatedNumber` component were caused by a `useEffect` hook that didn't run when a dependency changed.

## To Reproduce
Run `yarn build` for the project app.

## Expected behavior
[`useEffect` hooks must declare all reactive dependencies](https://react.dev/reference/react/useEffect#specifying-reactive-dependencies) in their dependency array, or redefine dependencies so that they aren't reactive values.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fix missing dependency errors in the `useAssignedLevel` hook by using `useSWR` to fetch and cache the assigned workflow level. SWR also adds revalidation of the Panoptes API request for cases where I might classify in the same tab over several days or weeks.* 

Adds conditional data-fetching, so that we only fetch a workflow configuration if we don’t already have it in the `workflows` page prop. 

Also fixes the workflow assignment tests in `ClassifyPageContainer` so that they test against the correct levels, and restores skipped tests to double check that nothing is broken.

~~Adds Mock Service Worker, for mocking API requests in stories.~~ I've moved the story for this into #6406. It sets up a test case where the assigned workflow, level 3, is complete and must be fetched from the Panoptes API.

*do workflow levels change over time? If not, the fetched value can be cached indefinitely.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- app-project

## Linked Issue and/or Talk Post
- closes #6217.
- fixes an issue where the workflow API request can run more than once, when `useAssignedLevel` is used more than once in the page or the page is run in React Strict Mode.
- fixes a bug where the Classify page always renders twice, first with a level of 1 and then with your actual level. 

## How to Review
Testing for this should be the same as #6201. `useAssignedLevel` should only call the API once for a given workflow, even if it’s invoked from multiple components. 

If you load Gravity Spy with the workflow choice menu, you can check that the Classify page only makes one API request for any missing workflows, even though `useAssignedLevel` is used twice on the page. The assigned level should also be cached in the client-side project app for the duration of your session.
https://local.zooniverse.org:3000/projects/zooniverse/gravity-spy/classify?env=production

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
#6201 broke the tests for `ClassifyPageContainer`. I’ve fixed them here by moving the data fetching up into the connector component.

**Comment by goplayoutside3** [comment]
@eatyourgreens Re:

> *do workflow levels change over time? If not, the fetched value can be cached indefinitely.

Yes they can change levels. The project team has full control over workflow level configuration. Does that fact change any code in this PR?

**Comment by eatyourgreens** [comment]
I shouldn't imagine so, but you can adjust the revalidation options if the hook is constantly requesting the same level from Panoptes, for a given workflow. 

https://swr.vercel.app/docs/revalidation

**Comment by eatyourgreens** [comment]
Right now, the Classify page requests the workflow config from Panoptes on every render, even if it already has it.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/blob/6fc2c84620c4f287bf69124f8a96d7df6389f54e/packages/app-project/src/hooks/useAssignedLevel.js#L20-L23
If the assigned workflow ID in my user preferences is an inactive workflow, then `fetchedWorkflow` will be undefined here and `assignedWorkflowLevel` will be set to `NaN`. I've updated this PR to catch that case and return 1.

**Review by goplayoutside3 — COMMENTED** [review]
Something isn't quite right with displaying locked vs unlocked in this PR. When I'm signed-in with the `zootester1` account at https://www.zooniverse.org/projects/zooniverse/gravity-spy I correctly see six workflows unlocked. When I run app-project on this branch locally with `yarn start` at https://local.zooniverse.org:3000/projects/zooniverse/gravity-spy, I only see one workflow unlocked.

See details for expected behavior when a user account is assigned a workflow id and that workflow is inactive/complete: https://github.com/zooniverse/front-end-monorepo/issues/6198

**Comment by eatyourgreens** [comment]
@goplayoutside3 that's my fault. I made the data fetching options too restrictive. Switching to [`useSWRImmutable`](https://swr.vercel.app/docs/revalidation#disable-automatic-revalidations) should have fixed it, while still caching the workflow level for each workflow ID.

**Comment by eatyourgreens** [comment]
If you’d like to check out the storybook with API mocks, I’ve pushed those changes here:
https://github.com/eatyourgreens/front-end-monorepo/tree/project-msw-mocks

**Comment by goplayoutside3** [comment]
This is looking much better. When signed in with various accounts, I see the expected unlocked workflows on Gravity Spy, and when signed on I see only the first level unlocked.

However, I need to double check how truly immutable our workflow levels are. Implementing `useSWRImmutable` might create an edge case where a workflow's level changes on the backend, and then a user assigned to it doesn't see the correct locked/unlocked UI. I'll have a quick chat with Cliff before approving this PR.

**Comment by eatyourgreens** [comment]
You can pass the same options into `useSWRImmutable` as `useSWR`, if you need to revalidate workflow levels during the course of a session. The immutable hook just sets some to false by default. 
https://swr.vercel.app/docs/revalidation#disable-automatic-revalidations

**Review by goplayoutside3 — APPROVED** [review]
I reverted to `useSWR` instead of `useSWRImmutable`. Workflow `level` can be changed by project teams at any point, so I made this change to avoid future confusion.

**Comment by eatyourgreens** [comment]
In that case, you'll want to set `revalidateOnMount` to true, otherwise I don't think it fetches at all.

**Comment by eatyourgreens** [comment]
Ok. The options now are set to the options for `useSWRImmutable` but with the addition of `revalidateOnMount` set to false.

**Pull request merged**
