### PR TITLE
Add check to Modal to see if rendering on client

### LINKED ISSUE #696: Modal component should check it's not rendering on the server
**Package**

react-component

**Feature or Issue Description**

The Modal component requires access to `document`, so if you try and have it open on the server, it'll break. We can add a state object to it, e.g. `{ client: false }`, have that set to true by `componentDidMount`, and only open the modal if both `client` and the `active` prop are `true`

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-react-components

Closes #696

Describe your changes:
Adds a check and state for rendering only on client side for the Modal since it uses the Layer component. Layer uses `window.document` which is not available on the server. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Could this be done in the functional component by checking for `window.document` with `useEffect()`?

**Comment by srallen** [comment]
I'm not sure. I haven't dug into hooks yet.

**Comment by rogerhutchings** [comment]
FYI I’m pretty sure this check exists in the various individual modals as well, so it may be worth removing them in this PR as well

**Comment by srallen** [comment]
@rogerhutchings Maybe it should be a HOC?

**Comment by srallen** [comment]
> FYI I’m pretty sure this check exists in the various individual modals as well, so it may be worth removing them in this PR as wel

I searched the src folder of app-project and lib-classifier for `document` and `window.document` and didn't find anything.

**Comment by rogerhutchings** [comment]
I was sure this did exist: https://github.com/zooniverse/front-end-monorepo/tree/master/packages/app-project/src/components/AuthModals/shared/components/withOnlyRenderOnBrowser

**Pull request merged**
