### PR TITLE
Add persist_annotations to workflow config

### LINKED ISSUE #2363: Back button message is not true
One of the volunteers on HMS NHS reported this issue. When you tab through the tasks in the workflow and get to the 'Back' button at the bottom, you get a message that says "Ging back will clear your work for the current task". However, this isn't true, at least on HMS NHS. The existing annotations persist when you come back. 

image

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add `workflow.configuration.persist_annotations` to the workflow models and default it to true.

Package:
lib-classifier

Closes #2363.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
I'm supportive of removal as you noted in https://github.com/zooniverse/front-end-monorepo/issues/2363#issuecomment-901926139

We should document that this configuration property is deprecated, too. An ADR?

**Review by srallen — APPROVED** [review]
This can merge for now even if we deprecate just to hide the unhelpful tooltip that is displaying.

**Comment by eatyourgreens** [comment]
Sounds good. I need to write some notes about undo/redo for classifications anyway. I should also note why annotations can't be undone, like the code here:
https://github.com/zooniverse/front-end-monorepo/blob/cda6875d3a89ce5c42c96b3d27f4fb8551c9401e/packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js#L56-L59

**Comment by eatyourgreens** [comment]
Finally added the ADR about undo/redo for the task area.

**Pull request merged**
