### PR TITLE
Copy over lib contents to app-project

### PR DESCRIPTION
**Pull request by rogerhutchings**
Package: app-project

cc #327 

Fix for FOUC, following #535 

- [x] Create an rsync script to copy over contents of libs
- [x] Fix import paths for components in app-project
- [x] Fix import paths for classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by srallen** [comment]
Sorry about the force-push. I screwed some stuff up trying to clean up and add it to the gitignore, so I reset back to what you did 😬

**Comment by rogerhutchings** [comment]
No worries, I've tidied stuff up and it should be good to go

**Comment by rogerhutchings** [comment]
Okay, _now_ this works.

- Fixed the ZooHeader where using a HOC was causing it to break;
- Ignore the `app-project/src/lib` dir in git and mocha;
- Fix some bash script bits (don't use `dash` by accident, otherwise substitution won't work)
- Only OSX's `sed` creates backups when modifying in-place

**Comment by rogerhutchings** [comment]
Sure, I'll set those now and merge. I'm pretty sure I've [published those packages](https://www.npmjs.com/search?q=zooniverse) already, but they'll need updating.

**Comment by rogerhutchings** [comment]
Closed in favour of #544 <3

**Pull request closed without merging**
