### PR TITLE
Build the Get Involved > Collaborate page

### PR DESCRIPTION
**Pull request by goplayoutside3**
## Package
lib-content

## Linked Issue and/or Talk Post
Builds on top of https://github.com/zooniverse/front-end-monorepo/pull/6205
Link to [Figma](https://www.figma.com/design/oZB2yOd3sjw3JTvUyz7lj1/Get-Involved-Pages?node-id=1-76&m=dev)

## Describe your changes
- Add content to the Collaborate page

## How to Review

- Run app-root locally and visit https://local.zooniverse.org:3000/get-involved/collaborate
- There's also a story component for Collaborate, but the logo images will not show because the assets live in app-root's public folder

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

### CODE REVIEW

**Comment by goplayoutside3** [comment]
In the interest of time, I self-reviewed + merged the Get Involved content PRs today. These PRs for page content use pre-existing styling components from lib-content and static visuals. The PRs do not affect any public-facing production pages. I want to get the content up on fe-root.preview for re-routing planning and design review.

**Comment by seanmiller26** [comment]
2 small things:

1. Can we add some extra margin after the Supporters logo/before the Collaborators heading?
2. Cliff's email is not a link rn. Should it be a standard email link?

Other than that, looks good!

**Comment by goplayoutside3** [comment]
> Cliff's email is not a link rn. Should it be a standard email link?

I tend not to make emails `mail:to` links because that makes it more difficult for users to copy + paste (especially on a touchscreen). But I can change it to a `mail:to` if you'd like?

**Comment by goplayoutside3** [comment]
Following up from Slack:
> 1. Can we add some extra margin after the Supporters logo/before the Collaborators heading?

Yes

> 2. Cliff's email is not a link rn. Should it be a standard email link?

Decision = yes

Both handled in https://github.com/zooniverse/front-end-monorepo/pull/6222 👍

**Pull request merged**
