### PR TITLE
Cast API values to correct model types

### PR DESCRIPTION
**Pull request by rogerhutchings**
Package: lib-auth

In #268, there's a bunch of UserResource model values that aren't being correctly set, breaking the auth flow.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
Yeah, most are either `true` or `null`. `maybeNull` would work, but feels a bit janky, no?

**Comment by srallen** [comment]
I guess if Panoptes is serializing something as either null or something else, I feel that the maybeNull type represents that? Seems incorrect that Panoptes is doing that, tbh.

**Comment by srallen** [comment]
I set the model types based on my own user, so it's good that your user had some null values. I'm not sure how I would've known that without reading Panoptes' serialization code I suppose.

**Comment by rogerhutchings** [comment]
Okay, I've updated this PR

**Pull request merged**
