### PR TITLE
Data selection feedback for scatter plots

### LINKED ISSUE #5856: Graph2dRangeFeedback Doesn't show correct answers
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
I gather from #5298 that feedback used to show which annotations were incorrect and also used to show where the correct annotations should have been. Now it just seems to show the volunteer's annotations without indicating what the correct answer should have been.

## To Reproduce
1. Go to the BHH training workflow https://www.zooniverse.org/projects/cobalt-lensing/black-hole-hunters/classify/workflow/25860
2. When classifying a subject with a lensing event, either don't mark it or mark the wrong part of the light curve.
3. Submit the classification.
4. The feedback window will open with the failure message, but the subject will be displayed without the correct ranges being highlighted.

## Screenshots
IMG_0427

## Expected behavior
The correct range (towards the left hand side in the above example) should be highlighted.

### Desktop (please complete the following information):
 - OS: [e.g. Windows 10]

### Smartphone (please complete the following information):
 - Device: [e.g. iPhone]
 - OS:
 - Browser:
 - Versio:

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add `feedbackBrushes`, from PH-TESS, to the scatter plot viewer's `Selections` component. Show a green bar for each success, a red bar for each failure.

Disable the subject viewer so that annotations can't be edited in the feedback popup.

Add a selection feedback story, with mock feedback brushes.

Refactor `ScatterPlotViewer` so that it can be rendered with `jsdom`.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
lib-classifier

## Linked Issue and/or Talk Post
- closes #5856.

## How to Review
Run Black Hole Hunters in the standalone classifier and try the training workflow. Every subject should have feedback.
https://localhost:8080/?env=production&project=cobalt-lensing%2Fblack-hole-hunters&workflow=25860

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## New Feature
- [x] The PR creator has listed user actions to use when testing the new feature
- [x] Unit tests are included for the new feature
- [x] A storybook story has been created or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Screenshots here: https://github.com/zooniverse/front-end-monorepo/issues/5856#issuecomment-1896077555

**Comment by eatyourgreens** [comment]
I've added a story and a couple of tests too.

**Review by mcbouslog — APPROVED** [review]
This looks good. Tested locally on https://local.zooniverse.org:3000/projects/cobalt-lensing/black-hole-hunters/classify/workflow/25860?demo=true without issue, feedback is as expected. The colors are a little confusing, but I know that's not related to these changes.

Testing on https://localhost:8080/?env=production&project=cobalt-lensing%2Fblack-hole-hunters&workflow=25860&demo=true resulted in two/duplicated Selections each time I made a Selection. I can not figure out why this is happening in lib-classifier, but not in app-project. 🤔 @eatyourgreens - do you see the same duplicated selections locally? Maybe it's me/my machine.

**Comment by eatyourgreens** [comment]
- https://github.com/zooniverse/front-end-monorepo/issues/5272

**Pull request merged**
