### PR TITLE
Allow for configuration of several more viewers

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

Describe your changes:
This finishes adding support for several more specific subject viewers, including the VSLCV, so that we can actually load a workflow with this configuration.

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by wgranger** [comment]
@srallen This code all looks sound, but is there any place in the code I can check this out, either storybook or otherwise?

**Comment by srallen** [comment]
@wgranger good call. Try out: https://local.zooniverse.org:8080/?project=4878&workflow=16121&env=production

Trying the workflow I'm setting up let me see that I missed one additional update to the workflow configuration model. If you pull down the latest and then load up the dev classifier with those query params, then you should see the variable star viewer. The data itself isn't loading, but that's a separate issue.

**Comment by wgranger** [comment]
Ok, I see that link above loads the workflow and renders the variable star viewer, albeit without data. I assume that is possible now because the 'variableStar' string can now be recognized in the WorkflowConfigurations and subjectViewers file of this PR. Is that correct, @srallen?

**Comment by srallen** [comment]
@wgranger That's correct. We don't have any workflows setup for the `DataImageViewer` yet, but I'll maybe do that next week, so that's not testable yet.

**Pull request merged**
