### PR TITLE
Add ADR-6 about locale file organization.

### PR DESCRIPTION
**Pull request by srallen**
Package: documentation

Describe your changes:
Brought up in a couple of PR discussions. This starts ADR-6 as a proposal. We can continue discussion here to refine this into a decision between the two proposed options. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
I'm opposed to the idea of any scenario where we end up dealing with single huge files of strings. They're a pig to work with, and one missing quote means annoyance until you can find it.

If the actual goal is to make translations simpler, then an actual app that gathers all the strings up and generates the files would be far easier than asking people to submit pull requests or modify locale files by hand. It'd make a good hackday project.

**Comment by srallen** [comment]
Pandora already exists, so perhaps we can add integration there? Pandora does not generate files at the moment though as far as I know. @eatyourgreens any thoughts on this approach?

**Comment by srallen** [comment]
I still like the idea of a separate library though and perhaps a separate lib would solve issues we are having with compiling as noted in #112 since we can make sure the lib is working when it is imported in any other lib or app. We should decide on json vs js files too. PFE uses js files for the locale strings.

**Comment by eatyourgreens** [comment]
Pandora's just a small app for updating Panoptes resources via the translations API. I think that's something different from what's being discussed here.

**Comment by rogerhutchings** [comment]
It is different, but we could make it more - volunteer translators shouldn't have to know how our code is organised internally, they should just be able to go to one place and be able to translate anything.

**Comment by eatyourgreens** [comment]
Sure, translating Zoo resources should all happen from translations.zooniverse.org, but Pandora is just the translations editor for the project builder (eg. https://www.zooniverse.org/lab/5733/translations) It can edit flat dictionaries, but can't handle nested objects at all. If you want to build an editor for the locale files, I think it'd be faster to build a small app just for that purpose.

[zooniverse/Translator](https://github.com/zooniverse/Translator) is an app that reads JSON blobs (from Ouroboros), edits them and allows you to publish them as JSON files on S3. It uses Ouroboros Talk roles to manage access, which is a bit of a hack.

**Comment by srallen** [comment]
We might be overthinking the problem here. A single file might be annoying for devs, but it isn't hard to edit. Text editors, linters, git, etc will all help in making sure it's formatted correctly. These are strings that will be rarely updated, so I would give preference to making it easier for volunteers than for devs. I'd be for a single library that could have maybe a script to help with compiling files, but I'm not sure if we need a full separate app with a GUI for this.

Perhaps the structure could a separate library with a folder for each locale and a flat file for each component and then a build script that compiles them locales into a single locale file that the consuming app them uses.

**Comment by eatyourgreens** [comment]
The Spanish and Italian translations for PFE have both been submitted as PRs from volunteers, so we might be ok asking them to edit on GitHub.

**Comment by srallen** [comment]
Ok, so here's what I'd like to propose:

A separate `lib-locales` with a folder structure that mirrors component folder structures with the locale json files, so that there's only one place volunteers need to go to update languages strings for across our libs/apps. Include a readme for instructions to use github to edit files and make pull requests. We can use Webpack for compilation into a single file needs.

**Comment by srallen** [comment]
@eatyourgreens, @rogerhutchings are there any further comments on this?

**Comment by shaunanoordin** [comment]
If there are no further comments on this PR, I'm cleaning it up and merging.

**Comment by shaunanoordin** [comment]
## Update
I've cleaned up this PR. The ADR remains in the state of "proposed", so we can always continue updating this document/re-open this discussion later, but for now this PR will be merged so our formal documentation won't go out of date.

**Pull request merged**
