### PR TITLE
lib-user: Refactor dev App to use PJC auth client

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- lib-user

## Describe your changes
- refactor lib-user dev app to use PJC auth client (instead of PJC oauth)

### Notes
- there's a ResizeObserver error that I think is related to my LastPass browser extension and a sign-in field input width ([SO link](https://stackoverflow.com/a/76190200)). if someone without LastPass also gets this error I'll revisit for a fix, but if it is indeed just a LastPass browser extension issue I'm going to leave as is.

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX? n/a
- What user actions should my reviewer step through to review this PR?
  - locally from lib-user, run `yarn dev`
  - sign in/out at https://local.zooniverse.org:8080/ (with staging user)
- Which storybook stories should be reviewed? n/a
- Are there plans for follow up PR’s to further fix this bug or develop this feature?
  - import lib-react-components header and footer for dev app (with warnings not in app-root and routing won't work)
  - change lib-user from being auth-client agnostic, to expecting PJC `auth` by:
    - refactor lib-user components/hooks to use PJC auth
    - remove authClient as a prop passed into lib-user
    - update README/documentation accordingly

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Comments as of [4b4e5c0](https://github.com/zooniverse/front-end-monorepo/pull/5992/commits/4b4e5c0e8da4641ffe7d6381fc2631f7ede6c1ff):
- Looking good so far!
- I was able to run the `lib-user` dev server on local
  - On local.zooniverse.org:8080, I'm able to login, logout, and login again with multiple different users (darkeshard, zootester1, zootester2) 
  - I can view my user stats on https://local.zooniverse.org:8080/?users=darkeshard/stats (known currently-in-development caveat: stats page will show stats of the logged-in user, not the target user)
- As a baseline, I was also able to run the `app-root` dev server on local and see the same user stats while logged in on the appropriate [URL.](https://local.zooniverse.org:3000/users/darkeshard/stats) (This is just a quick sanity check - I didn't expect any changes to the _dev server_ to affect the packaged build, but good to know everything's working.)

**Comment by shaunanoordin** [comment]
Slack followup/spillover: https://zooniverse.slack.com/archives/C06LHUC6R/p1711057705537769?thread_ts=1711054967.094679&cid=C06LHUC6R

The tl;dr of that Slack thread is this: once this PR gets merged, I'd be interested in seeing if the changes to lib-user can be copied over to lib-classifier. This is because I _think_ lib-classifier _only_ uses oauth because it was originally designed to run on `localhost:8080` instead of using the newer `local.zooniverse.org:8080` standard. Low priority, though.

**Comment by mcbouslog** [comment]
>  - Are there plans for follow up PR’s to further fix this bug or develop this feature?
>    - import lib-react-components header and footer for dev app (with warnings not in app-root and routing won't work)
>    - change lib-user from being auth-client agnostic, to expecting PJC `auth` by:
>      - refactor lib-user components/hooks to use PJC auth
>      - remove authClient as a prop passed into lib-user
>      - update README/documentation accordingly

I initially planned to include the noted follow up in this PR, but I think there still are local sign in/out issues that warrant reviewing and merging this sooner than later.

**Review by goplayoutside3 — APPROVED** [review]
Looks good! I can sign-in, sign-out, and view my stats or groups by running lib-user locally.

**Pull request merged**
