### PR TITLE
Finish up Publications

### LINKED ISSUE #756: Add project logos to publications
Each publication needs its related project logo next to it in the list:

Screenshot 2019-04-24 12 41 22

### PR DESCRIPTION
**Pull request by rogerhutchings**
Adds project logos to the publications page.

closes #756, #751

### CODE REVIEW

**Comment by shaunanoordin** [comment]
This seems totally legit and not at all questionable.

Screen Shot 2019-04-29 at 18 07 38

Since you're already set for placeholder images, I have suggestions for [placeholder names](https://goodbyejohndoe.com/) for the Team section.

**Comment by rogerhutchings** [comment]
Thanks @shaunanoordin. I'm just writing tests, and then this should be good to go.

**Comment by rogerhutchings** [comment]
This is ready for final review. I've done a fair bit of refactoring and whatnot, but it still works the same way.

Note that I've also changed the name from `app-about` to `app-content-pages`, to reflect the fact that it will eventually serve up the majority of the static content

**Comment by srallen** [comment]
I'm not sure if and what I'm doing wrong, but I'm not seeing any publications populate on the page.

**Comment by rogerhutchings** [comment]
Did you add the credentials for Contentful?

**Comment by shaunanoordin** [comment]
## PR Quick Review

- Functionality is looking good: the `/about` pages, especially `/about/publications` and `/about/team`, are working as expected:
  Screen Shot 2019-05-14 at 14 58 11
  Screen Shot 2019-05-14 at 14 58 21
  _Team page and Publication page displaying data fetched from the external Contentful CMS._
- I did a full refresh (`panic-button` then `bootstrap`) and the website looks fine on OSX+Chrome.
  - Note that I had to set up the `.env` file to connect to our content on Contentful.
- Noted on the new package name: `packages/app-content-pages`

Full review in progress; I just need to run through the code changes.

**Comment by srallen** [comment]
> Did you add the credentials for Contentful?

Nope. I missed the instructions since they weren't showing in the diff. I'll give it another try.

**Comment by rogerhutchings** [comment]
WAT

It should be getting the avatars. I think I forgot to add that you'll need `PANOPTES_ENV=production`, otherwise it'll try and hit staging where the projects don't exist

**Comment by shaunanoordin** [comment]
## PR Review (Update)

Aaahhh!

OK @rogerhutchings , I've confirmed that - `export PANOPTES_ENV=production` is required to make the Project Avatars display. 👍 

Screen Shot 2019-05-14 at 18 16 51

I strongly recommend adding this note in the `README.md`, or updating the `dev` script in `package.json` if that makes more sense.

**Comment by rogerhutchings** [comment]
I've done both

**Comment by rogerhutchings** [comment]
I'm going to merge this, as I want to start off the deploy, but will leave the branch in place for any other comments and whatnot

**Comment by lcjohnso** [comment]
@rogerhutchings -- this looks great!  However, I'm not currently seeing project avatars on the production version and the console is showing errors related to failed script loading.  Not sure what happened since original merge, but wanted to point out the issue.

**Comment by rogerhutchings** [comment]
@lcjohnso this should be fixed in https://github.com/zooniverse/front-end-monorepo/pull/835

**Pull request merged**
