### PR TITLE
[VSLCV] Make glyph less visible when toggled off

### LINKED ISSUE #1778: [VSLCV] Improve styling for data series not focused when there's a lot of data
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**
Researcher request: 

> We will have some sources that have a LOT of data (>10 x what is in the current example). When turning off a filter, is it possible to make the symbols even lighter (and possibly also transparent)?

**Describe the solution you'd like**

Perhaps we should actually consider making unfocused series invisible? This will be an underlying change that affects the `ScatterPlot`. I'll see if they can provide us with an example of what "a LOT of data" is.

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

Closes #1778 

Describe your changes:
We had a request to make the data points less visible or possibly even transparent both from the researchers and from others during the alpha test (See https://github.com/zooniverse/front-end-monorepo/issues/1780#issuecomment-685167861).

We have two options, one I've removed the color and lightened the stroke:

visibility-still-show

The other is to make them fully transparent:

fully-transparent

I'm not convinced making them fully transparent is a good idea, but open to discussion. @beckyrother thoughts? I haven't been sent an example of a subject that has a lot of data points, but I guess imagine one that has much more than what we see here?

Once we decide on an option, I'll finish this PR and update tests.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by beckyrother — COMMENTED** [review]
From a design standpoint, if I were to uncheck a box that said "visibility" I would assume it would turn off the visibility entirely, so I'd be inclined to go with the second option. I'm not a scientist, though, so would defer to the research team as to the usefulness of these options.

**Comment by srallen** [comment]
@adamamiller could you let us know which is the preferred function here? Please see my initial comment for animated gif examples: https://github.com/zooniverse/front-end-monorepo/pull/1801#issue-487587665

**Comment by adamamiller** [comment]
> @adamamiller could you let us know which is the preferred function here? Please see my initial comment for animated gif examples: [#1801 (comment)](https://github.com/zooniverse/front-end-monorepo/pull/1801#issue-487587665)

I should have an example with many more observations shortly (sorry for delay). I agree with @beckyrother that if it says visibility the points should disappear entirely. However, it looks a bit strange to have no points displayed at all when all options are unchecked... 

Perhaps it would make sense to change "visibility" to highlight? And then the observations don't need to disappear entirely? @ageller what do you think?

**Comment by ageller** [comment]
I agree that we don’t want the data to disappear entirely when the box in unchecked.  (I like how the data become grayed out.)  Using the term “highlight” seems reasonable, or something like “colorize” or “emphasize”.

**Comment by beckyrother** [comment]
I like Highlight! 

Wondering if the greyed out should be even lighter just to be sure this function is useful?

**Comment by srallen** [comment]
Sounds good. Thanks for all the guidance everyone! I'll post some updates today for review.

**Comment by srallen** [comment]
@beckyrother here is the updated control label using "highlight" and the gray stroke for the points is lighter:

adjusted-colors

**Review by beckyrother — APPROVED** [review]
Looks great @srallen !

**Review by wgranger — APPROVED** [review]
LGTM. This works on multiple browsers and is accessible. I can tell series are being toggled, and in doing so the color becomes transparent and the stroke/outline changes from black to a dim gray.

Note: I'm also noticing tests are failing locally in other components, but that is unrelated to this PR.

**Comment by srallen** [comment]
> Note: I'm also noticing tests are failing locally in other components, but that is unrelated to this PR.

@wgranger What failures are you seeing? CI is passing and I don't see any locally either.

**Pull request merged**
