### PR TITLE
Add consistent-return rule to linter

### PR DESCRIPTION
**Pull request by eatyourgreens**
Package:
all

Adds the[ consistent-return rule](https://eslint.org/docs/rules/consistent-return), which requires functions that return values to return consistent values. It should warn about missing return statements on functions that return from inside blocks.

Updates `app-content-pages` to use the same linter config as other packages.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I notice it's complaining about functions where early returns are used to exit if args aren't present.
ie.
```javascript
function doSomething(args) {
 if (!args) return defaultAction()
 newState = getStateFromArgs(args)
}
```
instead of
```javascript
function doSomething(args) {
 if (!args) {
   defaultAction()
 } else {
  newState = getStateFromArgs(args) 
 }
}
```
Personally I find the second style clearer but that might just be me.

**Comment by srallen** [comment]
Was this  a part of #898? Can this close?

**Comment by eatyourgreens** [comment]
It wasn't in #898 but I can rebase this PR to add this rule to the new config. I think it will warn about any function that returns early without also having a return statement at the end of the function.

**Comment by srallen** [comment]
Ok, sounds good to me

**Comment by eatyourgreens** [comment]
@srallen should be ready now. I also enabled the recommended accessibility checks, which I think you have to do before the linter will run them. At least, we had that `extends` line in our old eslintConfig for the project and the classifier.

**Pull request merged**
