### PR TITLE
Classifier: localise survey tasks

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Pass task language strings down to survey task components.
- Use the strings map to render text for choices, questions, confusions and filters.
- Update the tests and stories to use a mock survey task with a strings map.

Based on #3193.

## Package
lib-classifier

## How to Review
Wildcam Darién in Spanish is probably a good workflow to test survey task translations:
https://localhost:8080/?project=wildcam/wildcam-darien&env=production&language=es

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## New Feature
- [x] The PR creator has listed user actions to use when testing the new feature
- [x] Unit tests are included for the new feature
- [x] A storybook story has been created or updated
  - Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetutorial--default)

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Marking this as draft because it breaks most of the survey task tests.

**Comment by goplayoutside3** [comment]
I think this is another case of components in the TaskArea not updating when locale switches. Please check out https://local.zooniverse.org:3000/projects/wildcam/wildcam-darien/classify/workflow/3033?env=production and use the LocaleSwitcher to change to Spanish (had to hardcode 'es' into `availableLocales`). All of the animal choices remain in English instead of updating to Spanish.

**Comment by eatyourgreens** [comment]
When I was working on this, I noticed that the survey task had been built with `types.frozen` so none of its components are watching for changes. All the task data is assumed to be immutable. We might need to talk to @mcbouslog about completely rewriting it to use observables. 

As a side note, I think this also means that the task area won’t react to edits and changes when you’re building a survey task.

**Comment by eatyourgreens** [comment]
First thing to try, though, is wrapping everything in `observer`, because `task.strings` is observable. 

I’m finding it odd that this keeps coming up in the built library but not in the dev classifier. It means we can’t trust work that was developed and tested in the dev classifier. It also means that classifier tests will pass for language changes, even when they don’t work in the built library.

**Comment by eatyourgreens** [comment]
I’m also find it very hard to use the new filters with the keyboard. I think that’s a regression from the PFE version.

**Comment by eatyourgreens** [comment]
I've wrapped components in `observer`, where they use `task.strings`. That seems to fix it, but there's an annoying re-render of the whole task, rather than just the labels, when the language changes.


https://user-images.githubusercontent.com/59547/174323573-1b4a362c-7352-47c2-95ea-a66d284f75d6.mov

**Comment by mcbouslog** [comment]
Thanks @eatyourgreens for flagging and it looks like you're making good progress fixing!

I think your assessment of the translation strings and types.frozen is correct (as evidenced by your recently noted progress on fixing).

I think the task updates as expected, I just confirmed replacing Aardvark with Penguin then re-uploading the Choices in the editor changed the task quickly and as I'd expect, but I'm not entirely sure I'm addressing the concern ("As a side note, I think this also means that the task area won’t react to edits and changes when you’re building a survey task."). I tested this with [this staging project & workflow](https://frontend.preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify/workflow/3611?env=staging). Feel free to mess around with if you'd like.

I know there are a few other accessibility issues in addition to what you note with the filters - I'd like to focus on fixing theses asap and I'll mention that to managers when discussing my next efforts and maintenance week efforts.

**Review by goplayoutside3 — APPROVED** [review]
Looks much better! I'm able to use the LocaleSwitcher to successfully change Wildcam's task language to Spanish.

Before merging I recommend looking at the story for Chooser / CharacteristicsFilter / CharacteristicsSection where the "Like" label is missing in this PR.

**Comment by eatyourgreens** [comment]
>Before merging I recommend looking at the story for Chooser / CharacteristicsFilter / CharacteristicsSection where the "Like" label is missing in this PR.

Good catch. The story was missing the `label` prop, which defaults to an empty string.

**Pull request merged**
