### PR TITLE
Update grommet and grommet-icons

### LINKED ISSUE #1895: grommet-icons 4.5.0 update requires Blank (custom) icon size change
grommet-icons update to 4.5.0 changes the `StyledIcon` component. Previously, if a prop of `size='1em'` is included the prop would flow through, via grommet-icons' Blank component, to the custom icon's `<svg>`. However, [this grommet-icons change](https://github.com/grommet/grommet-icons/commit/6dfa0515745bbd1c28430a7a2ce660aef23c70f0#diff-c215b028362115de52e6cbe8b056585ffc9605de4503106d87f91e1bf4b4e8dcR62), notably new `const dimension`, no longer allows a size like `1em`.

[This branch](https://github.com/zooniverse/front-end-monorepo/compare/upgrade-grommet-icons#) starts the grommet-icons 4.5.0 update, changing the icon size to match the base pixel size, but is only complete for app-project, missing changes for lib-classifier and lib-react-components.

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier, lib-react-components, the apps

Needed for #2068
Closes #1895

Describe your changes:
Updating Grommet so I can style the heading color by theme object. There's a noticeable regression with some icon sizes with the grommet-icons update (logged in #1895) which are fixed along with the update.  

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by mcbouslog** [comment]
I'm not sure, but I think the current `em`'s might be based off `18px`? When comparing production to local the icons look a little smaller locally.

Noting I don't see font size set for `font` in [lib-grommet-theme](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-grommet-theme/src/index.js#L214) though it is set for the headings, text, and other specific components/tags.

**Comment by srallen** [comment]
@mcbouslog the 1em/18px is incorrect with the style guide and always has been. Part of this effort is to correct some of these issues. If you have a look at the invision design, the icon in the modal for instance is 14px: https://projects.invisionapp.com/d/main?origin=v7#/console/12923997/335563177/inspect?scrollOffset=354

I'm going to be setting as 15px though to try to keep stuff as multiples of 5 or 10, which is what Becky intended. Good point though, that if ems are used, we should set the baseline size with the font declaration. I'm not exactly sure where in the theme object that should be done or if it has to be set per component.

**Comment by srallen** [comment]
@mcbouslog I fixed another icon I missed, so I think this is ready for review again. I'll have a look at setting the base font size in the theme update PR.

**Review by mcbouslog — APPROVED** [review]
LGTM, tested in supported browsers, focusing on app-project and lib-classifier, without seeing any issues

**Pull request merged**
