### PR TITLE
Reorganize task stories. Make TranscriptionLine task type flexible for color

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

Describe your changes:
Reorganizes the stories to be closer to their code and enables us to add multiple stories per task. Refactored `TranscriptionLine` to be task flexible as we want to allow project builders to use the tool type in either the drawing task or transcription task. The colors are only hardcoded and have meaning for the transcription task, so this adds a `color` prop back to the `TranscriptionLine` and set the default state to be an empty string. The `state` prop will only be set by the TranscriptionTask or TranscribedLines models in a follow up PR.

As an aside, the task stories refactor and the TranscriptionLine refactor don't really have to be in the same PR, so happy to split out if requested. I just got there because I like starting with stories and the organization was just confusing previously. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
One initial thought about this: plugins should be independent of the classifier. So, ideally, plugins shouldn’t be importing components from the classifier. Importing `Tasks` and classifier stores is going to make it difficult to extract tasks into their own library.

**Comment by srallen** [comment]
Sure, perhaps further reorganization can be done in future PRs. My refactor here isn't changing how these stories are being built, just where they are in the component structure which enables us to have multiple stories about specific task types more clearly and places them next to the relevant code. Several of the components need decoupling from the inject decorator and the upgrade to use React context directly as suggested in mobx-react v6 will help with that.

**Comment by eatyourgreens** [comment]
Sounds good. Maybe tasks should export mocks that can be used in `Tasks` stories? That would keep the `Tasks` code separated from individual tasks. Tasks themselves could also have stories that don’t show the task navigation and task help. I think the second one depends on whether we use tasks in projects outside of the classifier. 

Either way, it’s something to consider but not a requirement for this PR. 

From a quick look through the code on my phone, the container for individual task stories could be put into a shared component, which would keep all the external imports in one place. Looks good, though. 👍🏻

**Comment by srallen** [comment]
@eatyourgreens Yeah, I had similar thoughts on future refactoring of the stories. Generally speaking, I think we should make sure we organizationally keep stories next to the component code. I was struggling to develop against task stories that weren't along side, so I decided to make this change even though it's not immediately relevant to the other half of the PR. 

@mcbouslog no worries on the story breakage. We do our best to keep these working and useful for us in developing! Thanks!

**Pull request merged**
