### PR TITLE
Tasks: add task.reset() and step.reset()

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add `step.reset()` and `task.reset()` to reset steps and tasks for a new subject. Call `step.reset()` for each workflow step on subject ready.

I've also added notes about the components and models to the README for tasks.

Package:
lib-classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Follows on from an earlier conversation about task lifecycle hooks: https://github.com/zooniverse/front-end-monorepo/pull/1372#pullrequestreview-339340466

**Comment by shaunanoordin** [comment]
⚠️ I'm seeing a weird bug here.

- on `lib-classifier`, given a VERY simple workflow with only one yes/no question...
- if I choose Yes for Subject 1 then submit...
- the next Subject will have the Yes answer PRE-SELECTED in the UI.
  - which is already a bit of a problem.
- worse, if I submit that Classification without touching the Yes/No in the UI, the Classification will be submitted with value `null` instead of value `yes`

Further documentation incoming.

The bug might actually be extant on master, but if I'm reading the intent of the PR right, should be addressed by the `resets()`

**Comment by eatyourgreens** [comment]
I thought that bug had been fixed, but obviously not. The task area is initially rendering with the previous classification.

**Comment by shaunanoordin** [comment]
Dang! At least it's a known issue - and if it hasn't been documented yet, I'll take care of it.

Judging from your description, @eatyourgreens, do you already know what the solution needs to be?

**Comment by shaunanoordin** [comment]
Note: you can test this out on my latest test project:

- lib-classifier, http://localhost:8080/?env=staging&project=1898

**Comment by eatyourgreens** [comment]
My fix for this, in #1339 by the way, had been to hold off classifying until `onSubjectReady`. Previously, it happened on `classificationComplete`, which fires while the previous classification is active.

**Comment by eatyourgreens** [comment]
This PR only changes the drawing task, so I don't see where it would re-introduce that bug for question tasks.

**Comment by shaunanoordin** [comment]
This PR does _not_ reintroduce the "Task Area rendering with previous Classification" bug. I've confirmed the bug is extant on `master` (247ae16ab7f31bf75b002a8e0b209fcf093a2b30), but I thought the implementation of `.reset()` was meant to solve problems like this.

**Comment by shaunanoordin** [comment]
After an absurd amount of testing, I can confirm that the "Task Area rendering with previous Classification" is completely unrelated to this PR, or any `.reset()` actions, or _anything to do with the stores._ It's a purely UI-related issue, so I can proceed with writing the review for this PR as I originally intended, which was basically: _LGTM_ 👍

**Pull request merged**
