### PR TITLE
Use next/link in project markdown

### LINKED ISSUE #5532: Links in Markdown ignore Next.js client-side routing.
## Package
_Choose from the list:_
- [x] app-content-pages
- [x] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
Links within the Next.js apps should use Next's client-side router, but they refresh the page when clicked.

## To Reproduce
1. Click the Team page link on this page: https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/about/research?env=staging

## Expected behavior
Links within each app should use `next/link`, which adds client-side routing for pages within the app.

## Additional context
There's a 500 error from the example, on staging, because `Markdownz` also strips query strings from URLs.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Wrap links in `next/link` in project markdown, so that links use client-side routing within the Next app, where appropriate.

NB. this is built off the `next-13` branch, so that we can take advantage of the new `Link` API.
_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- app-project

## Linked Issue and/or Talk Post
- closes #5532.

## How to Review
Build the project app and run it with `yarn start` or `npm start`. I have a test Research page with links to the project Team page. Those links should use client-side routing on this branch.
https://local.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/about/research?env=staging

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Review by goplayoutside3 — COMMENTED** [review]
I ran this branch locally, and I noticed when I hover over the relative link in your example project, the previewed url has `projects/projects/`. Is that expected?

Screenshot 2023-10-31 at 6 40 41 PM

**Comment by eatyourgreens** [comment]
>I ran this branch locally, and I noticed when I hover over the relative link in your example project, the previewed url has `projects/projects/`. Is that expected?

It should link to the Team page (see the same link in #5532.)
https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/about/research?env=staging

**Comment by goplayoutside3** [comment]
When I click on the relative link, it takes me to `https://local.zooniverse.org:3000/projects/projects/eatyourgreens/-project-testing-ground/about/team?env=staging`. There's an extra `/projects` in the url -- probably due to [defining the base path](https://github.com/zooniverse/front-end-monorepo/blob/af859405744ccc506ff5042dac78677e2e5ae268/packages/app-project/next.config.js#L41) as `/projects` in app-project's next.config.js. One solution could be to somehow change the base path for relative links. I'm not sure off the top of my head how to do that though.

Another thought: should markdown in [GenericAnnouncement](https://github.com/zooniverse/front-end-monorepo/tree/master/packages/app-project/src/components/Announcements/components/GenericAnnouncement) use `next/link` too?

**Comment by goplayoutside3** [comment]
Oh wait! You've already got GenericAnnouncement covered 👍

**Comment by eatyourgreens** [comment]
Looks like `next/link` is adding the app's `basePath` to links. That is annoying.

**Comment by eatyourgreens** [comment]
I've updated the markdown for that Research page, so that there are now three example links.
```md
Here's a link to the [Team page (./team?env=staging)](./team?env=staging).
Here's a link to the [Team page (/projects/eatyourgreens/-project-testing-ground/about/team?env=staging)](/projects/eatyourgreens/-project-testing-ground/about/team?env=staging).
Here's a link to the [Team page (https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/about/team?env=staging)](https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/about/team?env=staging).
```

**Comment by eatyourgreens** [comment]
I don't know if anyone uses markdown to link between their project About pages, so this could be a very minor bug.

**Comment by goplayoutside3** [comment]
Agreed, because we're relying on `basePath` for app-project and app-content pages I think this should be a draft for now, but I'll keep it in mind to revisit when app-root is deployed.

**Comment by eatyourgreens** [comment]
I've rebased this off the `next-13` branch, so that we can use the new `Link` API, where `Link` actually generates an `<a>` tag.

**Comment by goplayoutside3** [comment]
Because this doesn't fully work with a Next.js app using `basePath` (see comments above), I'm going to close for now and keep the linked Issue open. The fate of app-project being converted to a library or staying as a Next.js app is up in the air at the moment, so I'd rather address enhancements like this farther down the road.

**Pull request closed without merging**
