### PR TITLE
Disable add to collections for anonymous users

### LINKED ISSUE #658: Add to favourites and Add to collection should require sign-in
**Package**
lib-classifier

**Feature or Issue Description**
'Add to favourites' and 'Add to collection' should only be available if you've logged in.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Disable 'add to collections' or 'add to favourites' if there's no logged-in user.

Package:
lib-classifier

Closes #658.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Not the greatest solution to #658 but it works.

**Comment by shaunanoordin** [comment]
## PR Review

This PR fixes an issue where non-logged-in users could _attempt to_ add a Subject to their favourites or to a collection. These features should _only_ be available to users that are signed in.

Screen Shot 2019-04-10 at 17 02 35
_app-project showing a Classifier with the "Add to Favourites" and "Add to Collections" buttons_

With this fix, if a non-logged-in user clicks on the "Add to Favourites" 🇬🇧 or "Add to Collections" button on the Classifier, the user is prompted with the _Sign-In modal._ A signed-in user can click these two buttons to execute their functions as normal.

Without this fix, a non-logged-in user who clicks on "Add to Favourites" would immediately crash the app, and one who clicks on "Add to Collections" will show the Collections modal _before_ crashing the app.

### Testing

Tested on _app-project_ (note to self: do I need to check on lib-classifier?), on the localhost+OSX+Chrome, using the [I Fancy Cats](http://localhost:3000/projects/brooke/i-fancy-cats/classify) staging project.

This PR's changes to the button behaviours work mostly as intended, save for one quirk.

Screen Shot 2019-04-10 at 17 00 39

Quirk: clicking _"Add To Favourites"_ 🇬🇧 as a non-logged-in user correctly displays the _Sign In modal,_ but ALSO incorrectly marks the Subject as Favourited (i.e. the heart turns red)

This may be confusing if the user cancels out of the Sign In modal, because the Favourite heart _continues_ to be red even if there's logically no user profile to add a "favourite" to.

Further tests: determine if Subject is correctly added to Favourites after Signing In.

### Status

Code review is still ongoing.

**Comment by eatyourgreens** [comment]
Logging in rebuilds the subject queue (#636), which is why I'm not 100% happy with this solution.

**Comment by shaunanoordin** [comment]
> Logging in rebuilds the subject queue (#636), which is why I'm not 100% happy with this solution.

Aye, I just noticed it actually basically reloads the page.

A non-logged-in user clicking "Add To Favourite" or "Add to Collection" causes the Sign In modal to appear, and when the user logs in, the page reloads - meaning the Subject they were looking at is lost, and isn't added to favourites/collections.

While this is definitely a bad user experience, this fix _does_ solve the more pertinent issue of the app crashing, so hmm.

**Comment by eatyourgreens** [comment]
I think my ideal solution would be that logging in refreshes the incoming subject queue, but doesn’t change the active subject. Pinging @srallen and @rogerhutchings for opinions about how the subject store should change when you log in.

**Comment by shaunanoordin** [comment]
> I think my ideal solution would be that logging in refreshes the incoming subject queue, but doesn’t change the active subject.

Agreed that this is the ideal situation, though there are some edge cases that I'm not sure are solved. _(e.g. consider a project with an A-B split. If a non-logged-in user sees a Subject from the A-split, the logs into a user account in the B-split, will that user still see that the active Subject is from the A-split? Same question for projects that allow "levelling up" to new workflows like Gravity Spy.)_

If we're tight on time, a faster solution would be to do what PFE currently does: hide the _"Add to Favourite"_ and _"Add to Collections"_ buttons until the user signs in, with a _"you should sign in"_ prompt where the buttons should be.

**Comment by eatyourgreens** [comment]
@shaunanoordin I replaced this branch with a version that disables those buttons if you aren't logged in.

**Comment by eatyourgreens** [comment]
There still seems to be a bug where the classifier crashes if you log in and Add To Collections after the page has loaded.

**Comment by eatyourgreens** [comment]
>There still seems to be a bug where the classifier crashes if you log in and Add To Collections after the page has loaded.

That bug should be fixed by #706.

**Pull request merged**
