### PR TITLE
Patch React Components

### LINKED ISSUE #1708: ZooniverseLogoType is not exported
**Package**
react-components

**Describe the bug**
The ZooniverseLogoType [should be exported](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-react-components/src/index.js)

### PR DESCRIPTION
**Pull request by wgranger**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-react-components

Closes #1708 

Describe your changes:
With #1710 merged, the lib-react-components package is ready for a patch push to npm, allowing the ZooniverseLogoType to be exported.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by wgranger** [comment]
@eatyourgreens Does the wording here need to change? There is reference to the `ZooniverseLogoType` being an SVG https://github.com/zooniverse/front-end-monorepo/tree/master/packages/lib-react-components/src/ZooniverseLogotype

**Comment by eatyourgreens** [comment]
Both components render SVGs. I think the wording could be clearer. The logotype is the 'Zooniverse' SVG in the site footer.

**Comment by eatyourgreens** [comment]
Sorry, I meant the wording in the changelog. The Readme for the logotype is correct.

**Comment by wgranger** [comment]
Nice. Adjusted the CHANGELOG a bit and will merge and push once all checks pass

**Pull request merged**
