### PR TITLE
Upgrade Next to version 10

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrade the content pages and project app to NextJS 10.0.9.

The new router in Next 10 will be a breaking change for client-side navigation in the project app. I've opened #1973 to track that. In the meantime, this version of Next is fully backwards compatible with v9, so we can carry on using the old code in production.

Package:
app-content-pages
app-project

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Nothing seems to be broken, browsing I Fancy Cats with a local build of the project app.

**Comment by eatyourgreens** [comment]
Bumping this because 10.0.7 is out now.

**Comment by eatyourgreens** [comment]
Rebased and bumped to Next 10.0.9

**Comment by srallen** [comment]
The tendency for these big projects to not have breaking changes between major version is making me question the meaning of semver, hah! https://nextjs.org/docs/upgrading#upgrading-from-version-9-to-10

Anyway, now that I have my docker install fixed, I think I can more confidently review this.

**Comment by eatyourgreens** [comment]
I know! I think the upgrade from 9.4 to 9.5.5 was a bigger headache, for us, because of the router changes and our older `Link` code. This upgrade seems pretty mundane. I've held off on actually trying any of the new features in this PR.

**Review by srallen — APPROVED** [review]
Apps are building and tests are passing.

**Comment by eatyourgreens** [comment]
Excellent. Let’s try out Next 10.

**Pull request merged**
