### PR TITLE
lib-user: Refactor Certificate with credited_name and info Tip

### LINKED ISSUE #6182: Volunteer certificate: minor copy change
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

Can we please change 'PI' to 'Principal Investigator' under Laura's name?

### LINKED ISSUE #6187: Volunteer certificate: Add descriptive blurb if user exists before Mar 17, 2015
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

Question: 
Should the blurb be added to the cert, itself, or below the printable portion?

Copy:
This certificate only reflects efforts recorded after March 17, 2015. You should have received a certificate for previous efforts by email. If you did not receive this, or believe this is an error, please contact us.

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- lib-user

## Linked Issue and/or Talk Post
- closes #6182 
- closes #6187 

## Describe your changes
- refactor usePanotpesUser with `requiredUserProperty` (for user stats `requriedUserProperty` is `avatar_src`, for certificate it's `credited_name`, for MyGroups no `requiredUserProperty`)
  - the authorized user object can come from 3 places: 1) panoptes-js JWT, 2) PJC auth, or 3) panoptes API request
  - 1) JWT does not include `avatar_src` or `credited_name`, 2) PJC auth does not include `credited_name`, 3) includes everything in the user object
  - the changes in this PR make it so a user resource is only requested if needed based on the use case
- refactor Certificate `name` and related stories
- add Tip with info regarding stats start date of March 17, 2015 (#6187)
- edit 'PI' to 'Principal Investigator' (#6182)

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX? n/a
- What user actions should my reviewer step through to review this PR?
  - go to your user stats page, generate a user certificate
  - in the url, change the `start_date` to March 17, 2015 or earlier, note Tip next to date range
- Which storybook stories should be reviewed?
  - http://localhost:6008/?path=/story/components-certificate--pre-panoptes-info
- Are there plans for follow up PR’s to further fix this bug or develop this feature? no

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by mcbouslog** [comment]
Setting as draft pending https://github.com/zooniverse/front-end-monorepo/pull/6161 refactor with date helper function. Once 6161 is updated and merged with date helper function, I'll refactor these changes accordingly.

**Review by goplayoutside3 — APPROVED** [review]
Looks good! Small note, but when I generated a certificate the Tip icon looks really small next to the page font, so I recommend increasing the icon size if possible

Screenshot 2024-08-08 at 2 00 08 PM

**Comment by mcbouslog** [comment]
> Looks good! Small note, but when I generated a certificate the Tip icon looks really small next to the page font, so I recommend increasing the icon size if possible

Yes, great suggestion! I've bumped up the icon size a bit. 

Just to confirm - this is related to the browser page and not when you go to "Save Certificate" and create the PDF? The tip is intentionally [hidden on print](https://github.com/zooniverse/front-end-monorepo/pull/6191/files#diff-441454c1793dbd7e37889d64405529b03a3b27df9a6980b07fba70051e266a78R46-R48).

**Comment by goplayoutside3** [comment]
Yes that's correct! The screenshot is of the webpage not a PDF

**Comment by goplayoutside3** [comment]
@mcbouslog in response to

> I've bumped up the icon size a bit.

Would the icon in Top Contributors on a Group Stats page be affected too? I just noticed on fe-root.preview that icon now looks too large:

Screenshot 2024-08-09 at 4 56 08 PM

**Pull request merged**
