### PR TITLE
Add components for related projects modal

### PR DESCRIPTION
**Pull request by rogerhutchings**
Package:

app-project

Adds the UI for the related projects modal. I'm going to do the selection strategy in a separate PR.

Screenshot 2019-04-11 13 01 14

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
`Media` isn't showing a placeholder...

**Comment by beckyrother** [comment]
This looks awesome. Do you want an image placeholder rather than the grey boxes?

**Comment by rogerhutchings** [comment]
I'm partial to a [placecage](https://www.placecage.com/), but it's cool, these placeholders will get swapped out for the project images when I put some actual data in there :)

**Comment by srallen** [comment]
Nah, https://placekitten.com/ is the best

**Comment by beckyrother** [comment]
Classic

**Pull request merged**
