### PR TITLE
[DataImageViewer] refactor image rendering and finding subject locations

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

For #1717. This refactors the single image viewer used in the data image viewer to function similar to how it now works in the VSLCV. I also added another utility function that now finds subject locations from the locations array by media type and (and also calls the already existing validators). I'd like to update the VSLCV at a later point to use this new utility function. 

We don't have a project quiet setup yet, so this can be previewed by story: http://localhost:6006/?path=/story/subject-viewers-dataimageviewer--light-theme

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by ErikOstlund — CHANGES_REQUESTED** [review]
@srallen Code looks good. All tests pass. I'm seeing the image on the right side is too high. Can this be put in the same div or grommet box so the data plots and image are aligned?
image

**Comment by srallen** [comment]
@ErikOstlund I've started to work on a follow up to this that will add the zoom controls (the same button above the scatter plot) to control whether or not the image is zoom enabled, which will also fix the layout positioning at the same time. Is that ok?

**Comment by ErikOstlund** [comment]
Sounds good to me!

**Comment by srallen** [comment]
@ErikOstlund Great! Is there anything else that needs addressing? If not, could you switch the status to approved?

**Review by ErikOstlund — APPROVED** [review]
Good to go.

**Pull request merged**
