### PR TITLE
Lazy-load ZooHeader's and ZooFooter's user-specific navigation and admin feature

### PR DESCRIPTION
**Pull request by goplayoutside3**
## Package
lib-react-components

## Linked Issue and/or Talk Post
Toward https://github.com/zooniverse/front-end-monorepo/issues/5273

## Context

I investigated hydration errors a bit in https://github.com/zooniverse/front-end-monorepo/pull/5658 because running app-root or app-project still throws the following with a stack trace to SignedInUserNavigation:
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <a> in <nav>
```

The root cause of the error is that we have a component with links specifically for a user (SignedInUserNavigation) and a component with links specifically for a signed-out state (SignedOutUserNavigation). When React hydrates, there's a mismatch between html generated during SSR and html rendered client-side.

Similarly, ZooFooter's admin container only exists when a user is signed in, and that only happens at client-side auth. ZooFooter causes a hydration error due to AdminToggle's label being inserted client-side, but didn't exist on the server.

## Describe your changes

In this PR, I created a `useHasMounted` hook to detect when a component mounted in the browser. This concept is based on Josh Comeau's article about hydration, https://www.joshwcomeau.com/react/the-perils-of-rehydration, and is definitely worth the read. 

`hasMounted` is used to detect when ZooHeader has mounted or when ZooFooter has mounted, and only at that point should the user-specific components be rendered. I combined SignedInUserNavigation and SignedOutUserNavigation into one component to facilitate this process, and for better dx.

## How to Review

- The hydration errors should not persist when **app-root** is run locally in dev mode. ⚠️ Running app-project will still throw hyrdation errors because there are other components outside of ZooHeader and ZooFooter on the project pages with similar SSR issues.
- I recommend taking a glance at #5658 but I'm requesting to merge this PR into that one because the former focuses mostly on styling and `defaultProps`, but this PR is a specific solution to #5273.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by eatyourgreens** [comment]
You can be logged in to Panoptes before the header and footer mount in the browser. When you leave a page (eg. to go to Talk), then come back, the user is loaded from local storage. That was what stopped me from using `useEffect` to fix this originally.

**Comment by eatyourgreens** [comment]
I think the changes should be ok but I would be careful about regressing https://github.com/zooniverse/front-end-monorepo/issues/2980 with the lazy-loading code. 

There might be a couple of other closed issues around not being properly logged in if you have a Panoptes session when the page first loads. I remember volunteers reporting problems on Engaging Crowds, after going to Talk and returning. I solved those problems with local storage, so that the page can have a logged-in user before the React app mounts.

**Comment by goplayoutside3** [comment]
I tested out the navigation of Classify --> Talk --> back button to Classify on this branch, and I didn't notice anything strange with user auth. That test was in dev mode though, so I may deploy these changes to the FEM branch for further testing.

However, I don't think I follow how https://github.com/zooniverse/front-end-monorepo/issues/2980 could be re-introduced with `hasMounted`. In this PR, `hasMounted` must be true before any of the navlinks appear in ZooHeader (register if signed-out or user's navlinks if signed-in). Only once `hasMounted` is true, does the following check happen: `Object.keys(user).length === 0`. This way there won't be a flash of signed-out navlinks and then signed-in navlinks. 

Is there a case where `hasMounted` would never be true?

**Comment by goplayoutside3** [comment]
Deployed here: https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify

When I navigate away from FEM, and then back to Classify, there's no longer a flash of signed-out navlinks before I see my signed-in navlinks.

**Comment by eatyourgreens** [comment]
Sorry, what I meant is that if you are already logged in before the app mounts, then it’s intended that the first client-side render won’t match the server HTML. That isn’t a bug.

**Comment by goplayoutside3** [comment]
If you are already logged in before the app mounts though, why is there a flash of signed-out navlinks on production?

**Comment by eatyourgreens** [comment]
That's the time it takes for the React app to mount and render in the browser. The Million PR should speed that up.

While you're waiting for the React app to mount, you'll see the server-rendered HTML.

**Comment by goplayoutside3** [comment]
Thanks! That makes sense, and the purpose of `hasMounted` is to prevent a volunteer from seeing the server-rendered HTML (only applies to ZooHeader navlinks and the admin toggle in ZooFooter).

Is further review for this PR needed? Should I go ahead and merge into https://github.com/zooniverse/front-end-monorepo/pull/5658?

**Comment by eatyourgreens** [comment]
This is absolutely fine to merge, but it is safe to show the username etc. immediately, when the header mounts in the browser.

**Pull request merged**
