### PR TITLE
@zooniverse/react-components: remove require

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Replace `require` with `import` in a couple of places.
- Remove the `React` global from the tests.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
lib-react-components

## How to Review

```sh
# clean installed packages and builds
yarn panic
# install and build from scratch
yarn bootstrap
# test the project app on eg. https://local.zooniverse.org:3000/projects/zooniverse/gravity-spy
cd packages/app-project
yarn start
# test the content pages app on eg. https://local.zooniverse.org:3000/about/publications
cd ../app-content-pages
yarn start
```

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by goplayoutside3** [comment]
For conceptual documentation, is this change working toward FEM compatibility with ESM-only packages?

**Comment by eatyourgreens** [comment]
This is removing CommonJS `require` and `module.exports` from our code, yes. Otherwise, these files will error when `type: 'module'` is present in `package.json`.

We can also rename them to `.cjs` if we really need to use `require`.

**Comment by eatyourgreens** [comment]
Also worth noting that Bun supports both`import` and `require`, so that’s an option too (replace Node and Mocha with Bun.)
https://bun.sh/docs/runtime/modules#module-systems

**Review by goplayoutside3 — APPROVED** [review]
Looks good! Storybook for this package looks good and translating a project to another language works as expected.

**Pull request merged**
