### PR TITLE
Add visual indicators that project is in beta aka under review

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: app-project

Describe your changes:
We were missing the visual indicators for projects under review aka in beta. This involved adding a few of the project resource properties to its store model, a getter view for the beta state, some new components for the 'under review' label, connecting some existing components as well as refactoring the layout to be able to display the border.

Compare the Stellar Sleuths project home page and classify page, currently in the beta state, now with teal border and label:

Screen Shot 2020-10-16 at 11 27 29 AM

Screen Shot 2020-10-16 at 11 19 58 AM

To TESS which is launched approved, no teal border and label:

Screen Shot 2020-10-16 at 11 28 09 AM

Screen Shot 2020-10-16 at 11 20 30 AM

It'd be great if we could have this reviewed and ready for merge on Monday.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by beckyrother — APPROVED** [review]
Looks good to me! 👍

**Comment by shaunanoordin** [comment]
## Quick Review

Functionality looks good:
- For a project that is `beta_approved == true`, e.g. http://localhost:3000/projects/mikewalmsley/bursts-from-space?env=production, the teal border appears around the page, and the "under review" label appears below the project title.
- For a project that is fully launched (no longer in beta), e.g. http://localhost:3000/projects/tzwaanswijk/athena-spot-species-in-fine-art?env=production, there's no teal border, and no "under review" label.

Visual Quirk:
- In PFE, a project under beta review (e.g. https://www.zooniverse.org/projects/mikewalmsley/bursts-from-space?env=production) has a **teal border around the viewport.**
- In the monorepo, there is instead a **teal border around the page content**

screenshot-20201019-1738

_Comparative border coverage: monorepo PR on left, current PFE on right. Border was changed to double size (8px) with an obnoxious fuchsia pattern for visualisation purposes. Note that with the monorepo PR, the top border is only visible when user is at the top of the page, the bottom border is is only visible when user has scrolled to the bottom of the page, and only the left/right borders are visible at all times. Might be worth noting if we wanted to make the "under review" status more obvious._

Testing Note: "Bursts from Space" is in beta-approved status as of Mon 19 Oct 2020, and the status will probably change if you're reading this in the far future. Go find another un-launched, beta-approved project in the database if you're reading this in 2021 or whatever.

Next up, code review!

**Review by shaunanoordin — APPROVED** [review]
## PR Review

This PR adds visual indicators for projects that are currently under review.

- When a project is "under review" (i.e. beta approved, but not launch approved), then on the project page...
  - ...a teal border will appear around the page content.
  - ...an "under review" label will appear below the project title.
- The Project resource data model has been updated with "am I in Beta?" values

Testing:
- This has been confirmed on at least one production project: http://localhost:3000/projects/mikewalmsley/bursts-from-space?env=production
- Testing looks good on both the project home page and the classify page.
- Sanity check: projects _not under review_ do not have the teal border, nor the label.

Quirks:
- In previous PFE, the teal border is around the _viewport_ and is a constant visual reminder to the user.
- In this monorepo PR, the teal border goes around the _page content,_ which means the top/bottom borders aren't always visible to the user, depending on the viewport's scroll position.

Tested on localhost + macOS10 + Chrome86. See [Quick Review](https://github.com/zooniverse/front-end-monorepo/pull/1854#issuecomment-712291764) earlier for more detailed notes on visuals/functionality.

### Status

LGTM, I'm giving this a 👍  since functionality is met and code looks good.

The visual difference between old and new teal borders is something for a designer to evaluate (tagging @beckyrother in case you missed this tiny quirk during the review; if you already noted it, my bad, sorry!) BUT even _if_ that quirk needs to be addressed, it can be done in a separate PR.

As far as I'm concerned, this PR is good to merge!

**Comment by beckyrother** [comment]
Thanks for noting that Shaun! I'm okay with the change.

**Pull request merged**
