### PR TITLE
Adds zoomLevelOnCreation data to the graph2DRangeXAnnotation tool

### LINKED ISSUE #1068: Zoom information in the PHT data export
It would be great to know whether the volunteers are using the zooming in option on the new interface. Would it be possible to have this information in the PHT data exports? @shaunanoordin

### PR DESCRIPTION
**Pull request by simensta**
Package: lib-classifier

Closes #1068 .

Describe your changes:
This PR adds a zoomLevelOnCreation property to the annotation field for the graph2DRangeXAnnotation tool. @shaunanoordin paired with me on these code changes.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && yarn bootstrap` and app works as expected?
- [ ] Can you run a [production build](https://github.com/zooniverse/front-end-monorepo#getting-started) of the app?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## PR Notes

- As the title of this PR suggests, the `zoom` is level is only recorded _when the Annotation is created,_ and not when the Annotation is edited later.
- @noraeisner , once this update go will change the annotations will change from...
```
{
  tool: 0,
  toolType: "graph2dRangeX",
  width: 2.023974175304321,
  x: 19.99852454023084
}
```
- ...to...
```
{
  tool: 0,
  toolType: "graph2dRangeX",
  width: 2.023974175304321,
  x: 19.99852454023084,
  zoomLevelOnCreation: 2.5820389112625133
}
```
- ...where `zoomLevelOnCreation` is a number from 1.0 (no zoom) to 10.0

I've also updated this PR branch to match the latest `master` by clicking on that button on GitHub, so remember to update your local branches.

### Testing

Testers, to confirm that these changes are functioning on your end, please...
- Run the `lib-classifier` package
- Go to `http://localhost:8080/?project=1862` (Staging Project 1862 is the staging version of the TESS Light Curve Viewer)
- Create annotations at different zoom levels, submit, and monitor the annotation data sent to `/classifications`

**Comment by srallen** [comment]
@CKrawczyk Does this change impact how any of the extractors or reducers work?

**Comment by CKrawczyk** [comment]
This will not impact the extractors or reducers.

**Comment by eatyourgreens** [comment]
Tests are failing because `undefined` is not a valid value for `zoomLevelOnCreation`.

**Comment by shaunanoordin** [comment]
## PR Update

Thanks @srallen and @eatyourgreens - the missing update to the `Graph2dRangeXAnnotation` test has now been added. `yarn test` for the package looks good; I'm keeping an eye on the builds now.

@noraeisner do you have any feedback or comments on the added feature?

**Comment by srallen** [comment]
@noraeisner do you have any feedback to give to @shaunanoordin about the proposed 1-10 zoom transform information added to the classification? Thanks.

**Comment by noraeisner** [comment]
Sorry for not replying sooner. The 1-10 zoom levels looks great, thank you!

**Comment by shaunanoordin** [comment]
👍 The branch has been updated in preparation for a merge. @srallen did you have any CRs other than the failing tests?

**Pull request merged**
