### PR TITLE
app-content-pages: Replace counterpart with i18next

### PR DESCRIPTION
**Pull request by goplayoutside3**
## Package
app-content-pages

Translations project board: https://github.com/zooniverse/front-end-monorepo/projects/15

## Describe your changes

- Removed `counterpart` from all files and uninstalled it
- Replaced smaller locales.json files with one consolidated English dictionary of translation keys
- Used the i18next `t` function in component files
- Added a "test" language dictionary
- Skipped all failing tests for now, see notes below

## How to Review

This translations structure is based on app-project, so `next-i18next` is used in the same manner here.

Run app-content-pages locally and you can visit the following urls with and without /test/ as a subpath:
- https://local.zooniverse.org:3000/about/test/publications?env=production
- https://local.zooniverse.org:3000/about/test/team?env=production

Further work is needed to refactor all unit tests in this package, and also get ZooHeader and ZooFooter to correctly refresh with translations, as they do in app-project. I plan to follow-up with several PRs introducing stories for components, and unit tests written with RTL. As I refactor, I'll address any holes in the app-content-pages package where translation keys could be added. Much later on, I'll connect this package to Lokalise.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by eatyourgreens** [comment]
The `/about/test/publications` and `/about/test/team` URLs will break URL forwarding via our static proxy here:
https://github.com/zooniverse/static/blob/49e566a3218706d5b87113a668e974e0fd8d6340/nginx-fem-staging-redirects.conf#L24-L31

Is that something that should be fixed in this PR, with a `middleware.js` file, or something to fix later?

**Comment by goplayoutside3** [comment]
Hmm I didn't think about that since there's not a language toggle on the Zooniverse About pages yet. Even after this PR, app-content-pages is not really adding a translations feature.  If we don't address the locale subpath in the `static` repo yet, that just means we can't visit /about/test/publications on production, is that right?

A couple of architecture questions we'll need to handle that I can add to the FEM Translations board:
- If a volunteer is viewing Project Hunters TESS in Spanish, should the link in ZooHeader lead to /about/es/? Or should ZooHeader always link to English?
- Where should the Zooniverse About pages language dropdown go? Should there be one?

**Comment by goplayoutside3** [comment]
This refactor of _app.js introduces a bug where a signed-in user is not always recognized. For example, if viewing the publications page, I sign-in and then refresh the page, I'm signed-out again.

Converting to draft while I find what's going wrong.

**Comment by eatyourgreens** [comment]
In the project app, we store the user in local storage, then background refresh with an API call.

**Comment by goplayoutside3** [comment]
In this PR, I accidentally deleted the following: https://github.com/zooniverse/front-end-monorepo/blob/a41907814992b670fee00fd03d0b7bc744255ee3/packages/app-content-pages/pages/_app.js#L31-L34

So I think I'll need to add the `checkCurrent()` back in.

**Comment by eatyourgreens** [comment]
Running `store.user.checkCurrent()` on every render might spam the Panoptes auth API in the browser. Depends how often the App component renders. 

Maybe have a look at the `usePanoptesUser` custom hook in the project app. 

We should also look at sharing these hooks between the two apps.

**Comment by eatyourgreens** [comment]
Nothing blocking though. I think this is good to merge and try out on staging.

**Pull request merged**
