### PR TITLE
Add devcert to deal with SSL in browsers for local dev (particularly Chrome)

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

Package: project-app

Toward the workflow assignment effort...

This adds [devcert](https://github.com/davewasmer/devcert#readme) to the project app which creates a local certificate authority to generate self-signed SSL certificates (more info on how this works: https://github.com/davewasmer/devcert#how-it-works). Currently, we can get around Chrome's security warnings about SSL by using `http://localhost` and typing in `thisisunsafe`, but we still cannot sign in to Panoptes because of CORS errors. Adding this will enable us to use `https://local.zooniverse.org:3000` and `https://localhost.zooniverse.org:3000` which will get auth to work with Panoptes.

Note that the first time this is run on Mac OS X, you will get prompted for sudo:

> macOS and Linux: the certificate authority's credentials are written to files that are only readable by the root user (i.e. chown 0 ca-cert.crt and chmod 600 ca-cert.crt). When devcert itself needs these, it shells out to sudo invocations to read / write the credentials.

(More on this here: https://github.com/davewasmer/devcert#security-concerns)

Firefox still shows SSL cert warnings and you can still get around using certain configuration settings to get around it. We can [configure it to allow Firefox to trust](https://github.com/davewasmer/devcert#skipcertutil) the locally installed certificate authority. Let me know if anyone wants this done and it can be looked into.

Also note, this does not setup the CA for docker or for the classifier library. This can be done in additional follow up PRs. This right now just gets me in a place to continue workflow assignment feature development. 

To test, run `yarn bootstrap`, go to the project app, run `yarn dev`, enter your sudo password when prompted. You should see a new success message of `Ready on https://local.zooniverse.org:3000 or https://localhost.zooniverse.org:3000` then browse to one of those (depending on which of those local sub-domains you have setup). Now go to a staging project:

https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats

or 

https://localhost.zooniverse.org:3000/projects/brooke/i-fancy-cats

And try authentication with a staging user. You should now be able to authenticate.

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [x] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: `app-project`
Affects: localhost dev only ; allows login

This PR adds a localhost SSL cert system, so we can finally properly login with our Zooniverse accounts, when testing on `local.zooniverse.org:3000` 👍 

(Note: we're assuming you've set up _local.zooniverse.org_ to point to _localhost_ in your local hosts file).

Code read looks good, testing looks good, and I don't have any specific concerns about the new dependency, `devcert`, on the basis of _"well it works and anyway what other options do we have?"_

### Testing

Due to the way this is set up, the initial setup can only be tested once.

Initial setup:

- `yarn bootstrap`, go to app-packages, `yarn build && yarn start`
  - As forewarned, `devcert`requests sudo access and I had to provide my computer account password. This only happened once.
  - ⚠️ Side note, that initial `yarn build && yarn start` didn't fully build & start, instead getting stuck at some process ("clang"?). Stopping and restarting solved the issue, and I was never asked for my password again.
  - I also tested with `yarn dev`, and this works basically the same.

Main testing:

- Go to I fancy Cats, https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats/classify/workflow/693?env=staging , with macOS 10.12.6 + Chrome 91 in an Incognito Window.
  - The "thisisunsafe" warning page appears but is easily dismissed.
- Attempt to login with my Zooniverse account.
  - Success. 👍 
- Repeat with macOS 10.12.6 + FF 90.
  - Success. 👍 
  - The "are you sure this is a legit website?" warning page appears but is easily dismissed.

### Status

LGTM 👍 

I'm happy with this PR, though it'd be great if more people can chime in on their experience/thoughts on Docker, Firefox, etc etc.

**Comment by srallen** [comment]
@shaunanoordin thanks for the feedback. Actually, we only want the self-signed certificate to run for development, so I need to add some environment checks to this.

**Comment by srallen** [comment]
@shaunanoordin I requested a new review from you. I separated out the `devcert` function into an explicit server for development and added a new npm/yarn command `start:dev` for the case of running the server in a production environment, but with devcert. The original `server` file is restored since it is used in the top level docker-compose file for the actual deployment.

**Review by goplayoutside3 — APPROVED** [review]
I'm also able to run this branch locally, enter my password for sudo, and see i-fancy-cats locally while logged in as a staging user. I can use `yarn start:dev` to run a project in production and login as a real user, too 👍

**Comment by ErikOstlund** [comment]
Tested this PR on:
macOS Big Sur 11.4
Chrome 91.0.4472.114 in an Incognito Window

## Additional info for set-up
As @shaunanoordin mentioned, this assumes you've set up local.zooniverse.org to point to localhost in your local hosts file.
To check if your local host file is set-up correctly, open terminal
Type in: `sudo nano /private/etc/hosts`
Enter the admin password for the laptop
The host file should look like this:
image

I did not have to edit my local host file! But if you need to...

If not, move the cursor using the arrow keys and position the cursor after the text in the window.
Type the IP address
Hit tab
Type `local.zooniverse.org`
Add the additional url if desired (`localhost.zooniverse.org`)
Control + O keys to save the file, then control + X to exit.
Once back at the command line,
Type `sudo killall -HUP mDNSResponder`
That will flush your Mac's DNS cache, so it doesn't get confused by any changes you've made to the Hosts file.

## Running
I did not use `yarn build && yarn start`
I used `yarn dev`

Opened : `https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats`
and all is good! 👍 

Logged in with a Staging user
and all is good! 👍 

## Note:
I do get 3 `Warnings` in the web dev console

1. Prop `className` did not match. Server: "sc-pjSSY dVFZNW" Client: "sc-fzoyTs lfpSXU"
2. Failed prop type: Invalid prop `StyledAnchor` supplied to `NavLink`, expected a ReactNode.
3. Failed prop type: Invalid prop `StyledSpacedText` supplied to `NavLink`, expected a ReactNode.

And 1 Error

1. GraphQL Error (Code: 500): {"response":{"error":"","status":500},"request":{"query":"{ statsCount( eventType: \"classification\", interval: \"1 Day\", window: \"1 Week\", projectId: \"335\", userId: \"1326051\" ){ period, count } }"}}

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

Updates LGTM! 👍

- The newest changes ensures the self-signed SSL cert service _only runs for development,_ and _not production._
- New command has been added for app-package: `yarn start:dev`. It's the same as `yarn start`, except for the dev environment.

### Additional Testing

Tested using macOS + Chrome, accessing [I Fancy Cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats) on localhost

- `yarn dev` - https + login work as expected
- `yarn build && yarn start:dev` - https + login work as expected
- `yarn build && yarn start` - (production mode) https does NOT work and only http is accessible, _as expected_

### Status

Noice! 👍

**Review by mcbouslog — APPROVED** [review]
👍 LGTM, works as described (I tried Chrome, Firefox, and Safari) ✔️ . On initial `yarn dev` after entering sudo password I had to stop and restart, similar to Shaun's initial comment, point 2, but subsequently no issue.

**Pull request merged**
