### PR TITLE
Multi-frame viewer styling clean-up

### PR DESCRIPTION
**Pull request by mcbouslog**
Package:
- lib-classifier

Describe your changes:
- edit margins between frames
- edit previous/next buttons' focus/hover styling
- pointer cursor for frames
- edit frame list styling

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by mcbouslog** [comment]
@beckyrother what's your preferred way of reviewing? I can post screenshots, including animated gifs, though I'm not sure if that's the best way for you to review functionality.

Also, I've struggled with the active border and focus styling, which is on the input/image element, and the parent label element's height/width and margins. I think it's fine as is, but there might be a better way.

**Comment by eatyourgreens** [comment]
Only one element in the DOM can be `document.activeElement` and apply `:focus` styles, so this does sound like a Grommet bug. The Previous button should lose focus styling once `:focus` moves to another element.

**Comment by srallen** [comment]
I think it'd probably work as expected if we were using Grommet components for the input list.

**Comment by beckyrother** [comment]
Hi @mcbouslog sorry for the delay! Sarah's been creating gifs of interactions which work pretty well, so I'm fine with that if you'd like to do that.

**Comment by mcbouslog** [comment]
Attempted to use Grommet's https://v2.grommet.io/list unsuccessfully, as it worked in some ways but by default has certain functionality that created new issues or didn't work. The Grommet [RadioButtonGroup](https://storybook.grommet.io/?path=/story/radiobuttongroup--children) showed promise though with some initial work this afternoon.

**Comment by mcbouslog** [comment]
@srallen do you usually share `lib-classifier` screenshots from that library's dev env or do you rebuild `app-project` with `lib-classifier` changes and share from `app-project`'s dev env? I don't think makes a big difference for this case, but just curious. prob depends.

@beckyrother - here are some mp4s from a test project,
few frames:
frame-viewer-few-frames
clicks:
frame-viewer-clicks
tabs:
frame-viewer-tabs

**Comment by mcbouslog** [comment]
I'll create a new issue for the focus issue.

I also started adding the Media component from `react-components` to utilize its use of the thumbnail service as well as other helpful functions, but that affects how the focus styling is applied as well, so I think adding the Media component and refactoring for proper focus should come in a subsequent PR? I think they're so intertwined it makes sense, but open to suggestion.

**Comment by eatyourgreens** [comment]
It's also worth checking focus in Safari, Chrome and Firefox. The Chrome team have a different opinion, from Mozilla, as to how focus should be managed. You'll probably notice that, in FF, clicking an element does not automatically focus that element.

**Comment by srallen** [comment]
@mcbouslog I think it depends on how far along the feature is in development, whether or not the context of the app is important for reviewing it, etc. I've taken screenshots from storybook, the dev classifier, and from the project app. If you aren't sure, I think just asking what would be useful for the reviewer is probably sufficient. 

Also agree to just note the focus issue separately and not get bogged down in it for this PR.

**Comment by beckyrother** [comment]
These look great, thanks @mcbouslog ! 

Small note that maybe doesn't belong here – when the image is shorter than the toolbar, can it be centered vertically with a white background rather than top aligned:
image

**Comment by mcbouslog** [comment]
@beckyrother 💯 on vertically centering wider images, which touches on a more general dynamic layout based on image dimensions and subject classification purpose that I think we have planned for later this year, but I'm going to leave out of this PR, though will make sure we have noted.

**Pull request merged**
