### PR TITLE
Revert "Drawing: Add pointer capture to mark creation (#1420)"

### LINKED ISSUE #1454: Drawing: new marks can't be completed
**Package**
lib-classifier

**Describe the bug**
Pointer capture by the drawing canvas (#1420) means that the `onFinish` handler (#1369) is never called for new marks. Points and Lines can be started but not finished.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Reverts pointer capture (#1420) to fix creating new marks (#1454).

Package:
lib-classifier

Closes #1454.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
EDIT: I'm just now reviewing #1457, which may have some effect on this PR. Or maybe this PR has an effect on that PR? Sorry, I'm still reading through 1457, so I won't comment on the correct order of merging, yet.

**Comment by srallen** [comment]
Just noting my comment from related #1457: https://github.com/zooniverse/front-end-monorepo/pull/1457#issuecomment-580930434

I'm not sure why we need to revert unless there's a plan to implement the functionality from #1420 in a different way? #1457 enables us to support it and the new functionality for the transcription line.

**Comment by eatyourgreens** [comment]
In retrospect I think I implemented pointer capture in a very heavy handed way. I’m not sure stealing all events from new Marks was the right thing to do.

**Comment by eatyourgreens** [comment]
I'm going to merge this because #1420 introduced unexpected and confusing behaviour to event handling. In retrospect, event handler should be captured by the newly drawn mark, not the interaction layer container.

**Comment by eatyourgreens** [comment]
Closing this in favour of #1474, which fixes the broken event handlers.

**Pull request closed without merging**
