### PR TITLE
build: docker instructions and fixes

### PR DESCRIPTION
**Pull request by eatyourgreens**
- replace the outdated `docker-compose` command with `docker compose` in the READMEs.
- fix `AS` in Dockerfile.
- update the Docker instructions in the READMEs.
- make sure that environment variables are set for local development in the `docker-compose.yml` files.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Linked Issue and/or Talk Post
- https://github.com/zooniverse/front-end-monorepo/pull/6446#issuecomment-2475316117

## How to Review
To build and run the monorepo packages from the root directory:
```sh
docker compose build
docker compose up -d
```
That runs production builds of the project app and root app in a container:
- http://localhost:3002/projects/nora-dot-eisner/planet-hunters-tess
- http://localhost:3003

Shut down the running services and test the project docker compose config:
```sh
docker compose down
cd packages/app-project
docker compose up -d
```
That runs `yarn dev` for the project app and starts a development storybook. In theory, local changes to the project app should trigger hot module reloading in the running container:
- https://localhost:3000/projects/nora-dot-eisner/planet-hunters-tess
- http://localhost:9001

Shut down the project services:
```sh
docker compose down
```

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This PR gets the Docker builds working on a MacBook, but if no one uses Docker to run `yarn dev`, it might just be best to delete `packages/app-project/docker-compose.yml`, to be honest.

**Comment by eatyourgreens** [comment]
If you're new to Docker, here's a description of images vs. containers:
https://stackoverflow.com/questions/23735149/what-is-the-difference-between-a-docker-image-and-a-container/26960888#26960888

**Comment by eatyourgreens** [comment]
Working on this, I saw the the production monorepo image has become really big again. You might need to do another pass on removing unnecessary files from the image. `front-end-monorepo_prod` here is a copy of the image that gets deployed weekly, and it's grown to over 1GB again. You can inspect image sizes in Docker Desktop, or by running `docker images` from a terminal.

Sizes for the monorepo dev and production images. Dev is 2.07GB. Production is 1.42GB.

**Review by goplayoutside3 — COMMENTED** [review]
This is looking good. Thank you for your help in getting Docker sorted out!

I'm able to use docker compose at the root and app-project. I'll push some updates to the `docker-compose.yml` for app-root too (and its Readme).

I'm also going to run a test deploy to the fe-project-branch just to be safe before approval/merge.

**Review by goplayoutside3 — APPROVED** [review]
Success 👍 [Build run](https://github.com/zooniverse/front-end-monorepo/actions/runs/11842098608)

**Comment by eatyourgreens** [comment]
>Success 👍 [Build run](https://github.com/zooniverse/front-end-monorepo/actions/runs/11842098608)

:tada:

**Pull request merged**
