### PR TITLE
Video subjects: Add touch styles

### PR DESCRIPTION
**Pull request by eatyourgreens**
When drawing is enabled for video subjects, style the root SVG element with `touch-action: pinch-zoom;` so that dragging doesn't scroll the screen.

## Package
lib-classifier

## Linked Issue and/or Talk Post
- #3535.
- #3534.

## How to Review
On an iOS device, or Chrome on Android, you should find that you can draw a rectangle on a Solar Jets subject without the window scrolling when you drag the shape.
https://frontend.preview.zooniverse.org/projects/eostlund/video-project/classify/workflow/16843

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Review by goplayoutside3 — COMMENTED** [review]
Following PR #3645, the line below prevents a drawing layer from being rendered on any project because the `enableInteractionLayer` prop isn't passed on a per-project basis yet, and I can't test this PR properly.

https://github.com/zooniverse/front-end-monorepo/blob/c195d2991b20b04bedb561c8dc893281ccb3d3e7/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js#L78

Would you like to include handling `enableInteractionLayer` in this PR? Or I could write a separate PR to build it in.

**Comment by eatyourgreens** [comment]
That's weird, drawing was already enabled for the Solar Jets test project. I'll take a look.

**Comment by goplayoutside3** [comment]
> That's weird, drawing was already enabled for the Solar Jets test project. I'll take a look.

Prior to my refactor of SingleVideoViewerContainer, the prop `enableInteractionLayer` was always initialized as `true`.

**Comment by eatyourgreens** [comment]
Oh, I see. Each subject viewer hard codes it to either `true` or `false`.

**Comment by eatyourgreens** [comment]
I've written a really quick hook that checks the workflow for drawing tasks. It's working in the dev classifier so I'll push it up.
https://localhost:8080/?project=eostlund/video-project&workflow=16843&env=production

**Review by goplayoutside3 — APPROVED** [review]
Looks good!

**Pull request merged**
