### PR TITLE
Maintenance: rebuild yarn.lock. Upgrade NextJS to 12.1.6

### LINKED ISSUE #3429: Broken router mocks block NextJS 12.1+
Project app tests are failing in NextJS 12.1.6 or higher, wherever they mock the router, since the following code doesn't really stub the `useRouter` hook.

In the test:
```js
import * as Router from 'next/router'
…
sinon.stub(Router, 'useRouter').callsFake(() => ({ query: 'fake query', locale: 'fake locale'}))
```

In a component:
```js
import { useRouter } from 'next/router'
…
const { query, locale } = useRouter()
```

That errors in the tests because `useRouter()` returns null in the component.

_Originally posted by @eatyourgreens in https://github.com/zooniverse/front-end-monorepo/issues/3425#issuecomment-1179979951_

### PR DESCRIPTION
**Pull request by eatyourgreens**
A clean rebuild and re-install of `yarn.lock`, to update outdated packages and remove conflicting babel modules.  
- Includes an upgrade of `next` to [12.1.6](https://github.com/vercel/next.js/releases/tag/v12.1.6).
- Updates tests that mock `useRouter`, which fails with NextJS 12.1.6 and higher.
- Closes #3429. 

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
- What user actions should my reviewer step through to review this PR?
- Which storybook stories should be reviewed?
- Are there plans for follow up PR’s to further fix this bug or develop this feature?

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [x] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Maintenance
- [x] If not from dependabot, the PR creator has described the update (major, minor, or patch version, changelog)

### CODE REVIEW

**Comment by eatyourgreens** [comment]
`app-project` tests are broken because of #3429.

**Comment by eatyourgreens** [comment]
The difference between this and #3529 is that builds are running without failing here.

**Comment by goplayoutside3** [comment]
Tests are passing and builds are looking good.

Do you know why this particular NextJS upgrade caused `useRouter()` to fail in a testing environment? As an example, why does providing an empty object in TeamMember allow its tests to pass? I'm especially interested in that component because its tests are already converted to React Testing Library.

**Comment by eatyourgreens** [comment]
To be honest, I’m not sure how the original code worked, in that I would expect this snippet to create a new `nextRouter` object, then stub the `useRouter` method on that object. 

```js
import * as nextRouter from `next/router`

sinon.stub(nextRouter, ‘useRouter’)
```

**Comment by eatyourgreens** [comment]
See #3429 for a brief explanation but basically component code will error when it tries to destructure `null`.

**Comment by eatyourgreens** [comment]
I've added a link to the `12.1.6` tag, so that we can see what changed in that release.

**Comment by goplayoutside3** [comment]
> To be honest, I’m not sure how the original code worked, in that I would expect this snippet to create a new `nextRouter` object, then stub the `useRouter` method on that object.
> 
> ```js
> import * as nextRouter from `next/router`
> 
> sinon.stub(nextRouter, ‘useRouter’)
> ```

Agreed with your statement above.

However, `sinon` wasn't used to mock `useRouter()` in ProjectAboutPage's /components, and I want to continue with TeamMember as an example. TeamMember.spec uses stories as the component under test, and previously RouterContext.Provider worked with `useRouter()`. This PR adds a custom hook, `useQuery()`, to the actual TeamMember component for handling when `router` does not exist.

Adding custom hooks such as `useLocale()` and `useQuery()` adapts the component code to the testing environment rather than mocking up a testing environment that matches the NextJS app. I want to discourage us from doing this especially in components with unit tests already converted to React Testing Library. 

Is there a way to modify our RTL units test to the upgraded NextJS version and provide a `router` context? I'll do some research on that question and check back in tomorrow.

**Comment by eatyourgreens** [comment]
Have a look a this NextJS discussion for tests that don’t use shallow rendering. 
https://github.com/zooniverse/front-end-monorepo/issues/3429#issuecomment-1222537534

**Comment by eatyourgreens** [comment]
It looks like the `TeamMember` stories are using the wrong import path for `RouterContext`. That should be easy to fix. 

The About and Classify page tests should also be wrapped in a context provider, in order to pass the router to `StandardLayout`. 

Lines like this will probably still need a guard for the case where `useRouter()` is null. 

```js
const { query, locale } = useRouter()
```

**Comment by eatyourgreens** [comment]
I’ll have another look tomorrow but I don’t think `TeamMember.spec.js` is broken with 12.1.6. Does it fail for you?

However, `TeamMember.js` does crash when it’s rendered in the `AboutPage` tests, where the router is null.

**Comment by eatyourgreens** [comment]
>However, `sinon` wasn't used to mock `useRouter()` in ProjectAboutPage's /components, and I want to continue with TeamMember as an example. TeamMember.spec uses stories as the component under test, and previously RouterContext.Provider worked with `useRouter()`. This PR adds a custom hook, `useQuery()`, to the actual TeamMember component for handling when `router` does not exist.

Just to confirm, your RTL tests are absolutely fine but those subcomponents crash in the the tests for `ProjectAboutPage, when they access `router.query` but `router` is null.

I've pushed the original About pages code back up, so you can see the errors in the latest test run.

Screenshot of the tests running in a terminal, showing that tests for ProjectAboutPage fail when the router is null.

**Comment by eatyourgreens** [comment]
I've also set the default `router.locale` and `router.query` to `undefined` or `null`. That seems safer than adding default values, like 'en', to individual components.

**Review by goplayoutside3 — APPROVED** [review]
Looks good! My only other recommendation is to add a code comment in these places:
`const nextRouter = useRouter()`
 `router = router || nextRouter`
that explains how router may not exist in a testing environment. 

There isn't a case in the actual browser app when router is undefined from `useRouter()`, is that the correct understanding?

**Comment by eatyourgreens** [comment]
I think `useRouter()` is null in some of the stories but that doesn’t seem to prevent components from rendering eg. Daily Classifications Chart looks fine when I checked it in the storybook.

**Comment by eatyourgreens** [comment]
Components that generate links to `/owner/project` might link to `/undefined/undefined` in the storybook but we don’t expect links from stories to work. 

Those would benefit from being wrapped in a context provider, like you’ve done with the About pages.

**Comment by eatyourgreens** [comment]
>Looks good! My only other recommendation is to add a code comment in these places:
`const nextRouter = useRouter()`
 `router = router || nextRouter`
that explains how router may not exist in a testing environment. 

I'll document the `router` prop as an optional prop that can be used to pass a mock router for stories and shallow Enzyme tests.

**Pull request merged**
