### PR TITLE
Add storing of client sizes for DataImageViewer

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

Package: lib-classifier

Similar to #2383. This adds storing of the client sizes of the DataImageViewer to the SubjectViewerStore and classification metadata. This can be manually tested with: https://local.zooniverse.org:8080/?project=10996&workflow=16264&env=production&demo=true. In demo mode, you can quickly classify by selecting no then checking the POSTed classification for metadata for subject dimensions. Also with this one, the natural sizes are set to 0 since it would have no meaning with this complex composite viewer. 

This project isn't going to beta or launch any time soon, so doesn't have a specific timeframe that it needs to be reviewed by. Thanks!

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
@ErikOstlund are you available to review this in the next few days? Thanks!

**Comment by ErikOstlund** [comment]
@srallen, Using the project link posted above doesn't POST a classification. Unless I'm missing something.
image

However, I tested this using a different project: [Drawing Grid](https://localhost:8080/?env=production&project=16201&workflow=18675)
And everything worked as expected.
Screen Shot 2021-09-17 at 11 58 54 AM

Are you experiencing the same thing with your posted link?

**Comment by srallen** [comment]
@ErikOstlund The URL I shared has the `?demo=true` param included. I'm not sure if this branch got updated with the demo mode update, but that'd be something to check.

**Review by ErikOstlund — APPROVED** [review]
Ahhh, yes. My previous comment was my mistake. If Demo mode is enabled, a classification will not be sent. Duh! 🙄 
Making a classification (with Demo mode disabled) will now send `clientHeight` and `clientWidth` inside the `subject_dimensions` within the metadata. I tested this on a couple of projects and all looks well.
image

All unit tests are passing.
Looks good. 👍

**Pull request merged**
