### PR TITLE
Setup shared component resolution and start project home page

### PR DESCRIPTION
**Pull request by rogerhutchings**
- Sets up shared folder resolution in webpack as per https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346
- Moves shared components to be resolved in their new locations
- Add shared components to project home page

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks like this should be reviewed and merged before the front-end components are built for #37 (recent classifications) and #38 (your stats).

**Comment by eatyourgreens** [comment]
Can this PR also add a description of the component directory structure to either the Readme or to Contributing.md?

**Comment by eatyourgreens** [comment]
Build errors when I try running this with the new component paths. 😞 
```
./components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
Module not found: Can't resolve 'components/ClassifyBox' in 
'/Users/odonnell/zooniverse/front-end-monorepo/packages/app-project/components/ClassifyPage/components/FinishedForTheDay'
```

**Comment by eatyourgreens** [comment]
After reading the linked gist, I expected the shared page components to be in `app-project/shared` so I'm confused as to why you chose to put them into a top-level `shared` directory. I think this PR is missing an explanation of how you've chosen to implement shared module directories.

**Comment by eatyourgreens** [comment]
Tests fail to run with `Error: Cannot find module 'components/withOnlyRenderOnBrowser'`. Reading through the comments on the linked gist, is babel unable to resolve the new paths?

**Comment by rogerhutchings** [comment]
Did you stop and start the app when you checked this branch out? Changes to the babel config don't hot-reload...

**Comment by eatyourgreens** [comment]
I started the app from scratch. Module resolution is failing on the classify page with `Module not found: Can't resolve 'components/ClassifyBox'`.

**Comment by rogerhutchings** [comment]
Yeah - I can't find a non-hacky way to get round that at the moment, and it's falling squarely within the 'nice-to-have' camp at the moment, so I'm going to go back to using relative paths for imports for now.

**Comment by eatyourgreens** [comment]
I realised that the top-level shared directory is confusing me because the classifier has a `/src` directory and `app-project` doesn’t. Definitely consider organising the code in the same way across repos.

**Comment by rogerhutchings** [comment]
We can do that. There would still have to be a top-level `pages` dir, since that's a Next.js requirement, but I can make that change in this PR if you'd like

**Comment by eatyourgreens** [comment]
It seems like a good idea to me right now. I was thinking `/src/components` and `/src/shared` at the top level of the app. The classifier has `/src/stores` too, but I think moving the stores right now might conflict with a couple of open PRs.

**Comment by eatyourgreens** [comment]
👍 Folder structure looks good to me, and tests are running correctly. I can load a couple of projects from staging and run the app locally.

I'm seeing Bad Request errors when submitting classifications, but I'll assume those aren't connected to this PR.

**Comment by eatyourgreens** [comment]
At some point, we'll need a brief description in the readme, or contributors.md, so that other members of the team can jump in and get up to speed without asking us to explain the repo structure to them. I'm happy to approve this without those changes, though.

**Comment by eatyourgreens** [comment]
I think this is going to conflict with #457. Do you want to merge that first, or merge this then sort out the conflicts with the ClassifierWrapper in that PR?

**Comment by rogerhutchings** [comment]
@eatyourgreens ready to go

**Pull request merged**
