### PR TITLE
yarn clean-install

### PR DESCRIPTION
**Pull request by eatyourgreens**
`clean-install.sh` is a bash script that emulates [`npm ci`](https://docs.npmjs.com/cli/v8/commands/npm-ci). It removes installed node modules from all packages, then runs [`yarn install --frozen-lockfile`](https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile).

Run it from the root directory with `yarn clean-install`.

## How to Review
Run `yarn clean-install`, then `yarn bootstrap` to build the libraries and apps.

_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn clean-install && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

### CODE REVIEW

**Comment by mcbouslog** [comment]
This looks similar to https://github.com/zooniverse/front-end-monorepo/blob/master/bin/panic-button.sh ? Maybe we should remove `panic-button` in favor of these changes and update related references in `package.json`, `bin/README.md`, and `docs/PULL_REQUEST_TEMPLATE.md`?

**Comment by eatyourgreens** [comment]
The panic script rebuilds the libraries and apps. This script is meant to do a clean install without a build eg. after dependabot updates. Good question whether it’s useful having both, though.

**Review by goplayoutside3 — APPROVED** [review]
Looks good!

**Comment by eatyourgreens** [comment]
Noting here, for posterity, that I use this script to clean up old or outdated packages that might have accumulated in `node_modules` over time.

**Pull request merged**
