### PR TITLE
Classifier - TESS Light Curve Viewer - allow adding Annotations

### LINKED ISSUE #241: TESS LCV - viewer should be able to add annotations
## Required Feature

Package: lib-classifier
Project: Light Curve Viewer / Planet Hunters TESS
Requires: #240 to distinguish between Move (navigate) mode and Annotate mode.

The TESS Light Curve Viewer requires the ability to add Annotations.

**Desired Functionality**
- [ ] When the Classifier is in 'Move/Navigate' mode, the LCV will treat all mouse actions as navigation actions, as is usual with the D3 'zoom' behaviour.
- When the Classifier is in Annotate mode,
  - [ ] a click on the InterfaceLayer will create a new (confirmed) Annotation (a column with minX-maxX coordinates) centred around the click.
  - [ ] a drag on the InterfaceLayer will create a new ACTIVE Annotation, with minX starting at the point where the mouse click starts, and maxX at the point where mouse drag ends. (or vice versa if dragging right-to-left)
    - Releasing the drag will change the Active Annotation into a Confirmed Annotation
- Annotations must follow these rules:
  - [ ] Annotations that are currently being worked on are called Active Annotations
    - Active Annotations exist only in the D3 environment (and not the MobX store).
    - Active Annotations are initially removed from the Annotations Store, and re-added when they become Confirmed Annotations. (i.e. when the user finishes adding a new Annotation, or finishes editing an old Annotation.)
    - Rationale: If we don't do this, we'd need to actively change the value of a specific annotation in the array in the Annotations Store while the UI interactions happens and the Annotation is marked "active", which can get tricky, object reference-wise.
- [ ] Annotations might need to exist on their own AnnotationLayer that sits "above" (after) the InterfaceLayer. _(Note: this was originally proposed to make the annotation logic distinct from other forms of interaction, but I'm starting to realise that they may be too closely tied together... so regard this ToDo point with a pinch of salt.)_

### Dev Notes

Required: the ability to map mouse click coordinates to data point coordinates. See Roger's `plotly-prototype` code, notably:
```
import * as d3 from 'd3'
 export default function getXFromEvent (context, xScale) {
  const coords = d3.mouse(context)
  return Math.round(xScale.invert(coords[0]))
}
```

NOTE: for the TESS project, we assume the active Task is a Drawing Task of type Column, which is a very very specific assumption for how the LCV should be set up.

NOT PLANNED FOR: what happens when the Light Curve Viewer is used in conjunction with a Task that ISN'T a Drawing Task of type Column?

NOT PLANNED FOR: what if a user cancels out of Annotation mode and into Move/Navigation mode... while there exists an Active Annotation?

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview
Package: `lib-classifier`
Requires (and is a sequel to) #279 
Closes #241 

The goal of this PR is to let users add annotations via the LCV
- [x] Users should be able to add new annotations in Annotate Mode.
  - [x] When in Annotate Mode, mouse click should add an annotation at the point of click.
  - [x] Mouse drag and wheel scroll should be ignored. 

screen shot 2018-12-04 at 15 45 09
_When in Annotation mode (selected from the Classifier page toolbar), users can click on the light curve to plonk down a "Graph Range"-type annotation (with a fixed width), which indicates the range where a dip in the brightness has been detected_

NOTE: the annotation data should be in the form of: `{ x: number, width: number }`
- `x` marks the centre of a selection range (aka a column) indicating a dip in the light curve.
- `width` marks the total range of the, er, selection range.

NOTE: not covered in this PR -
- ability to edit or remove existing Annotations.

### Status
~~WIP~~
This PR is now feature-complete and ready for reviews, but see posts below for massive **Dev Notes** in regards to 1. how LCV is connected to the store, and 2. how the `graphRanges` workflow task is used. I'm performing some cleanup, documentation updates, and test improvements, before moving on to the _'edit or remove Annotations'_ PR. (2018.12.04)

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## PR Update
This PR now properly allows users to add Annotations to the light curve viewer.

screen shot 2018-12-04 at 15 45 09
_Annotations are shown as red bands indicating a range where a dip in the brightness has been detected._

### Dev Notes

While this PR is functional, I have two points that I feel require some discussion, and I welcome advice on how these should be best implemented.

#### 1. Connecting the LightCurveViewer to the MobX stores

The Light Curve Viewer (a subset of the Subject Viewer) needs access to several points of information in the MobX stores:
- whether the user has activated Annotate or Move mode (via the Classifier toolbar).
- what is the **current task** the user is working on.
- the **annotations** that the user has already made.
  - and the ability to _add_ annotations.

_Currently,_ the `LightCurveViewer` component _connects directly to the stores,_ and this functions perfectly for this component and the TESS project. (The prime rationale for this is how the D3 implementation integrates data/stores with presentation/user interactivity, with a lot of reading/writing directly to the stores coupled to user interactions.) However, for long-term/other components/general patterns used in the `lib-classifier`, should this be the way it's implemented?

The question comes up because the general pattern in the `lib-classifier` is that higher-order/container components are the ones responsible for connecting to the stores, and then passing those values down to the lower-order rendering components. How would other components - e.g. SubjectViewers or "Annotation Panes" (?) for Drawing Tasks - handle this?

e.g. should the root SubjectViewer component now start passing _a whole lot more_ data (annotations, annotation/move mode, functions to create new annotations, etc etc) down to its lower order components, or would the future `DrawingTaskAnnotationPaneOrEtc.jsx` component connect to the store directly like the LCV?

To be clear, I'm happy with how the LCV connects to the stores as a short-term, deliver-by-January solution, but I'm keen to know the long-term implementation for other annotation components like Drawing Tasks.

#### 2. Using the "graphRanges" workflow task

For the TESS Light Curve, I've added a new kind of workflow task - or rather, _task annotation type_ - called `graphRanges`, represented in the new `GraphRangesAnnotation` class.
- This annotation type describes an array of x-ranges on a graph, of the format: `[{ x, width}]`
- the TESS Workflow must be custom-modified to have this task.

Question: have we formalised how new task annotation types are being created? If not I'll have to step up my documentation game.

I imagine that the "proper" (or classic, according to PFE) way to implement the UX for this task would be as follows:
- if the current Task is a Graph Ranges task, then
  - if in Annotation mode, clicks add/edit/remove Annotations
  - if in Move mode, mouse drags pan the image
- if the current Task _isn't_ a Graph Ranges task, then
  - if in Annotation mode, clicks _do nothing
  - if in Move mode, mouse drags pan the image

However, _current implementation_ used in this PR is as follows:
- the Light Curve Viewer is aware of what the current Task is, but _doesn't care._
- When in Annotation mode, clicks _always_ add Annotations, despite what Task is being showed in the Task panel.
  - For the moment, the LCV creates a new Task with arbitrary key `T100`.

~~The main reasons I'm using the current implementation (i.e. ignore the current Task, and instead add tasks based on a custom key) is because 1. the LCV only works with the graphRanges task, so any mouse clicks on the LCV might as well _enforce_ Annotations of the graphRanges type. (Otherwise, the problem is that the only way that the LCV works is if the project owner KNOWS to both set the **custom** `subjectViewerType=LCV` and `task.type=graphRanges` values in the workflow, which feels iffy due to its implicit-external nature and easily messed up) 2. I don't like how a user can be in Annotation mode but _not_ be able to add/edit Annotations. From a UX perspective, it's weird - the PFE's current solution is that, if the Subject Viewer is in Annotation mode, but the current Task doesn't allow Annotations (i.e. not an active Drawing Task), the mouse clicks on the Subject Viewer automatically switch the mode to Move mode, which feels a bit odd in terms of expectations.~~

Wait, now that I've written that out, that sounds stupid. There's no real reason I shouldn't follow the original PFE pattern, so I'll need to create an update that 1. adds a Graph Ranges Task to the Task Panel, even if it just displays text, and 2. adds some UI logic when the LCV is in 'inert' mode (i.e. when `currentTask !== 'graphRanges' && currentMode === 'annotation'` ), so clicks either automatically switch the mode back to Move mode (as in classic PFE) or do nothing, with some sort of indicator to the user what's happening.

The problems I stated earlier can be mostly resolved with some documentation, though please feel free to add any thoughts on the UI experience when users are in different annotating/moving/etc modes.

### Status
Ready for review.

New on the TODO list:
- revisit how the Graph Ranges Task is used in the LightCurveViewer.

**Comment by shaunanoordin** [comment]
NOTE: This PR is set to merge to `tess-lcv-add-annotations` instead of `master` for ease of review. The original intent is to merge to `master` (if all looks good) after PR #279 is approved.

**Comment by shaunanoordin** [comment]
The base branch to this PR (#279) was recently rebased to fix a problem with MobX stores, so this PR should best be reviewed after #279 is merged and this branch rebased.

**Comment by rogerhutchings** [comment]
This is probably not a helpful comment, buuuuuuut did the D3 Brush API not work for this?

**Comment by shaunanoordin** [comment]
I didn't touch D3 brushes yet, since for this PR I just wanted to focus on adding Annotations - and since the new graph annotations would in the form of `{xCentre, width}` I decided that a mouse click to indicate `xCentre` (instead of a drag/brush motion to mark `xStart, xEnd` and then extrapolate) would be a more natural form of UI interaction.

_I may be wrong about this,_ so in any case I will revisit this UI interaction design when I get into the Editing/Removing Annotation feature.

**Comment by shaunanoordin** [comment]
> I have some comments on the code - I can't test it in practice as I'm getting an error as MST tries to assign the workflow steps to the store

Argh, sorry @rogerhutchings ! I think this branch is broken at the moment, I need to rebase this to match the current updates in #279 (rebased heavily) and #352 (replaces #319). This might be a fresh new branch/PR to make things simpler.

**Comment by shaunanoordin** [comment]
Replaced by #357

**Pull request closed without merging**
