### PR TITLE
[VSLCV] Increase row sizes and image area size

### LINKED ISSUE #1782: [VSLCV] Increase height of grid area
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**

In context of the classify page, we have some wasted space between the bottom of the plots and the meta tools buttons, so let's increase the height of the subject viewer to use it:

Screen Shot 2020-09-02 at 11 30 40 AM

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package:

Closes #1782 

Describe your changes:
In context of the classify page, we had some extra space, so this increases the height of the grid rows and image area size.

Before:
Screen Shot 2020-09-02 at 11 30 40 AM

After:
Screen Shot 2020-09-11 at 11 15 35 AM

Also can be previewed by building and running the project app  and navigating to: http://local.zooniverse.org:3000/projects/adamamiller/stellar-sleuths/classify

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [x] Has a storybook story been created or updated?
- [x] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by beckyrother — CHANGES_REQUESTED** [review]
Adding consistent spacing will help this feel a little more organized. I also added white backgrounds to the right-hand graphs to help them feel more connected. Note that white boxes have a 1px #E2E5E9 border: 

v3

**Comment by beckyrother** [comment]
Added this to InVision as well: https://invis.io/AFYRC1RGM6D

**Comment by srallen** [comment]
@beckyrother here is the layout now with borders and background color updates. Note that the HR diagram image is not taking the full height and is slightly too wide. I'd like to solve that issue separately.

Light theme:
Screen Shot 2020-09-17 at 4 45 38 PM

Dark theme:
Screen Shot 2020-09-17 at 4 14 30 PM

I noticed we don't have consistent background colors with the dark theme. The controls use #666666 and the bar chart and image area use #333333. Which would you like across all the modules?

**Comment by beckyrother** [comment]
Thanks Sarah! Let's do #333 for the backgrounds on the dark theme. Is there a reason the `temperature` label is so far away from the HR Diagram? Other than that I think this works.

**Comment by srallen** [comment]
@beckyrother here is the update background colors for the dark theme:

Screen Shot 2020-09-18 at 3 09 29 PM

For the HR diagram image, it's not taking the full height and is slightly too wide because I'm hard coding its size right now. To make it dynamic, I need to update the underlying `SingleImageViewer` to make a few changes so it can be better used a module in a complex subject viewer like this one. I'm planning on doing that separately if that's ok?

**Comment by beckyrother** [comment]
Totally makes sense! This looks great 🎉

**Review by beckyrother — APPROVED** [review]

**Comment by srallen** [comment]
@mcbouslog this is ready for code review.

**Review by mcbouslog — APPROVED** [review]
Code LGTM, reviewed storybook, compared http://local.zooniverse.org:3000/projects/adamamiller/stellar-sleuths/classify to https://frontend.preview.zooniverse.org/projects/adamamiller/stellar-sleuths/classify

**Pull request merged**
