### PR TITLE
Transcription tooltips

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

Package: lib-classifier

This extends the tooltips to include the default and active state transcription lines since these colors aren't changeable and have specific meaning too. This can be tried using the dev classifier at: https://localhost:8080/?project=11300&env=production&demo=true

Default created state:
Screen Shot 2021-05-06 at 12 48 48 PM

Actively editing:
Screen Shot 2021-05-06 at 12 48 21 PM

And the preexisting tooltips should still work as well:

Screen Shot 2021-05-06 at 12 56 09 PM

Screen Shot 2021-05-06 at 12 56 04 PM

@snblickhan is the messaging on these tooltips ok?

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by snblickhan** [comment]
@srallen confirming that the messaging is great on these -- sorry for the delay in reviewing this!

**Comment by srallen** [comment]
@goplayoutside3 neither of the issues you found are documented. We've had quite a few with focus, but not that particular one. The modal going off screen is likely an underlying function of the CSS Grommet is applying, so I'm happy to open up a couple of issues to track these items. Mind giving this PR another review? Thanks!

**Review by goplayoutside3 — APPROVED** [review]
@srallen sounds good about making separate issues for the minor styling bugs, and the rest looks good to me!

**Comment by srallen** [comment]
I've opened #2177 and #2178.

**Comment by eatyourgreens** [comment]
I'm getting a weird bug on this branch:
Screenshot of a green transcription line, showing the delete button moved away from the focused line.

When I drag one of the drag handles (in Chrome), the delete button moves but the rest of the line stays where it is.

I'm also seeing that all the grey lines have `tabindex=-1`, as if they were disabled. That might be a completely different issue.

**Pull request merged**
