### PR TITLE
Zoom configuration docs for ScatterPlotViewer

### LINKED ISSUE #2120: Zooming on a specific point in the ScatterPlot viewer
## Package
lib-classifier (Zooming ScatterPlot)
## Is your feature request related to a problem? Please describe.
For our project (14770) the features of interest are not always in the centre of the plotted range (see image) and the zooming function only seems able to zoom in on the middle of what's currently displayed. 

In addition, when zooming in on a particular section of the data, it would be good to limit zooming to the x direction. I think I can see from the source code that this should be possible with developer intervention, but I may be wrong. 

Also it would be good if we could pad the display area beyond the limits of the data but I'm aware that there is another issue [#1777](https://github.com/zooniverse/front-end-monorepo/issues/1777) on that topic. As is evident from the image part of the interesting feature is actually truncated because it contains (in this case, but not always), one of the extreme points in the data set.
Screenshot 2021-04-23 at 14 38 14

## Describe the solution you'd like
I would like to be able to zoom in on a particular section of the data, regardless of where it is within the display window or the data range. I would also like to limit zooming to the x direction, keeping the y zoom locked.

## Describe alternatives you've considered
Padding the data with outlier points far outside the real data range so that the display can be panned to have the feature of interest in the centre and zoom in on it that way. The problem is that this makes the range of real data a small fraction of the display at the initial zoom level.

## Additional context
We cannot determine where within the range of the data any feature of interest might be so we cannot prepare data that have the feature pre-centred

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

Package: lib-classifier

Closes #2120 

Adds to the readme docs on the zoom configuration for the ScatterPlotViewer.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
@ErikOstlund Hey, are you available this week to review this? Ok if not, just let me know. Thanks!

**Review by ErikOstlund — COMMENTED** [review]
Just one question regarding `Monorepo Front End` vs `Front End Monorepo`.
And one suggestion.

**Comment by srallen** [comment]
@ErikOstlund I've applied your suggestion and this is ready for review again.

**Review by ErikOstlund — APPROVED** [review]
Looks good! 👍

**Pull request merged**
