### PR TITLE
Drawing: scale marks

### PR DESCRIPTION
**Pull request by eatyourgreens**
Calculate the subject image scale when the subject image loads. Pass the scale down as a prop to marks. Scale rendered mark sizes and delete button position.

Package:
lib-classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Now that #1339 has merged, this should also scale any previously drawn marks.

**Comment by shaunanoordin** [comment]
> Now that #1339 has merged, this should also scale any previously drawn marks.

I'm not seeing this yet, unfortunately. Aren't the previous marks rendered in `<InteractionLayerContainer />`, whereas the `scale` is calculated only in (and for) `<InteractionLayer>` ?

Tested on http://localhost:8080/?env=staging&project=1895 on commit a6c82d2efe55083636db7305f840a4e9491ad42c:

Screen Shot 2019-12-03 at 15 48 10

_On Task 1, I draw a few Points which are scaled up._

Screen Shot 2019-12-03 at 15 48 20
_When moving to Task 2, the Points drawn in Task 1 use the default scale of 1.0_

**Comment by shaunanoordin** [comment]
Thought: should the `scale` be stored as `SubjectViewer.subjectScale`, so it'll be visible to the parent Container? Putting it in the SubjectViewer might also be handy if we need to refer to the zoom values, e.g. if we want to maintain a consistent mark size independent of zoom levels.

**Comment by eatyourgreens** [comment]
>I'm not seeing this yet, unfortunately. Aren't the previous marks rendered in <InteractionLayerContainer />, whereas the scale is calculated only in (and for) <InteractionLayer> ?

That's because I hadn't written the code yet. I've just committed changes which move the scale calculation up to the parent subject viewer.

**Comment by eatyourgreens** [comment]
An SVG context might be useful to store the common props that are being passed around to every SVG component. #1334 is going to need client bounding rectangles for each drawn mark, as well as the subject image, so that would be a good place to think about that.

**Pull request merged**
