### PR TITLE
Upgrade visx and d3

### LINKED ISSUE #2371: Upgrade visx
## Package
app-project
lib-classifier

visx supports React 17 now, so we should upgrade to the latest version. https://github.com/airbnb/visx/pull/1268

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrade `visx` to version 2 and `d3` to 6.7.0. `visx` v2 adds official support for React 17. `d3` v7 ships as pure ES modules, which don't work with our current test setup.

Test URLs for the dev classifier:
PH-TESS: https://localhost:8080/?project=nora-dot-eisner/planet-hunters-tess&env=production&demo=true
Stellar Sleuths: https://localhost:8080/?project=adamamiller/zwickys-stellar-sleuths&workflow=16135&env=production&demo=true

Package:
app-project
lib-classifier

Closes #2371.

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by mcbouslog — CHANGES_REQUESTED** [review]
Getting an error `Uncaught TypeError: Cannot read properties of undefined (reading 'selection')` when I attempt to create an annotation in TESS. I think related to the d3 v6.0 migration changes (specifically events and zoom? https://observablehq.com/@d3/d3v6-migration-guide#events).

**Comment by mcbouslog** [comment]
Noting https://www.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths is a good project to test `visx` changes on.

**Comment by eatyourgreens** [comment]
Good catch re. the changes to `d3` events.

**Comment by eatyourgreens** [comment]
@mcbouslog thanks for the project links. I've added a couple of links that should work in the dev classifier too.

**Comment by eatyourgreens** [comment]
>Getting an error Uncaught TypeError: Cannot read properties of undefined (reading 'selection') when I attempt to create an annotation in TESS. I think related to the d3 v6.0 migration changes (specifically events and zoom? https://observablehq.com/@d3/d3v6-migration-guide#events).

Worse, there's no indication of an error when `onAnnotationBrushEnd` fails. To a volunteer, it looks like the transit has been recorded and submitted. Errors seem to be caught and silently ignored, unless you've got the browser console open.

**Comment by eatyourgreens** [comment]
@mcbouslog I've removed `d3.event` from the light curve viewer. It should work, although I'm not 100% sure how `event.selection` works in `d3`.

Zwicky's Stellar Sleuths seems to work without any problems.

**Comment by eatyourgreens** [comment]
I've also tidied up the LCV event handlers, so it's obvious that they're only bound once to the LCV component. Each call to `.bind()` generates a new function, potentially generating a new event handler for every event, which is only run for that event. That can lead to memory leaks. Hat-tip to @rogerhutchings who originally pointed this out to me.

**Review by mcbouslog — APPROVED** [review]
TESS and Zwicky looking good now, thanks!

**Pull request merged**
