### PR TITLE
Disable real HTTP requests in tests

### PR DESCRIPTION
**Pull request by eatyourgreens**
Set [`nock.disableNetConnect()`](https://github.com/nock/nock#enabledisable-real-http-requests) for all tests. Any requests and responses that are required for tests must be mocked.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
app-content-pages
app-project
lib-classifier

## Linked Issue and/or Talk Post
- towards #4105.

## How to Review
Run the tests.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This setting was shamelessly stolen from the [Sugar test setup](https://github.com/zooniverse/sugar/blob/e9151de47bf3ac98fe95d0be12c681dcc5bfc9e0/test/index.coffee#L23-L25).

**Comment by eatyourgreens** [comment]
This should fix all the project app tests that send requests for notifications when the store is created. 

TODO: move those data requests out of the store.

**Review by mcbouslog — APPROVED** [review]
LGTM!

I used nock with notifications tests in app-content-pages in #4010, should be able to use the same or at least very similar tests in app-project.

**Comment by eatyourgreens** [comment]
Let’s see if this makes the tests run any faster.

**Pull request merged**
