### PR TITLE
Move favourites button to shared react components

### LINKED ISSUE #1192: Move `FavouritesButton` to shared react components library
**Package** lib-classifier, app-project, lib-react-components

**Is your feature request related to a problem? Please describe.**

The `FavouritesButton` and its icon are nearly identical code between the classifier library and the project app:

https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.js

https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/FavouritesButton.js

The only difference I see is the project app version has an additional language registered with counterpart and a class name passed as a prop to the icon.

**Describe the solution you'd like**

Move the `FavouritesButton` to the react component library and remove the duplication between the two locations. Update them to use the shared version.

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #1194: Move `MetaToolsButton` to shared react components library
**Package** lib-react-components, lib-classifier, app-project

**Is your feature request related to a problem? Please describe.**

This is the underlying component used by `FavouritesButton` and `CollectionsButton`. If they are moving to the shared react components library, then this one has to as well.

The code is nearly identical:

https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetaToolsButton/MetaToolsButton.js

https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/shared/components/SubjectPreview/components/MetaToolsButton/MetaToolsButton.js

The only difference I see is the margin which we can make a prop for configurability. 

**Describe the solution you'd like**

Move the shared code to the react components library for use by the `CollectionsButton` and `FavouritesButton`

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by eatyourgreens**
Move FavouritesButton and MetaToolsButton to the react-components library. Update the classifier and project app to use the shared buttons.

Package:
app-project
lib-classifier
lib-react-components

Closes #1192.
Closes #1194.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks like someone changed `filled` from a boolean to a string at some point. :thinking:

**Comment by eatyourgreens** [comment]
@rogerhutchings I can't reproduce that error. I'm able to favourite subjects both in the project app and standalone classifier.

**Comment by eatyourgreens** [comment]
@rogerhutchings that's fixed now.

**Comment by rogerhutchings** [comment]
Appears to be fixed now, thanks

**Comment by rogerhutchings** [comment]
The tests need fixing though

**Comment by eatyourgreens** [comment]
I've updated the tests to use the SVG `fill` attribute. Hopefully they'll pass now.

**Pull request merged**
