### PR TITLE
Add proposed adr-7

### PR DESCRIPTION
**Pull request by rogerhutchings**
Add proposal for marking tool schemas.

Package: docs

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks ok to me, but I think this should apply to annotations from all classification tasks, not just drawing tools.

**Comment by eatyourgreens** [comment]
Workflows are versioned, and each classification records the workflow version. Annotation schemas might be more efficiently stored with the workflow task definitions.

If we update the code for a task, how would the updated schema get passed to either classifications or to the task definition in workflows that are using that task? Should we automatically publish new versions of all workflows that use that task?

**Comment by srallen** [comment]
Could this be ADR-7? #109 is for ADR-6

**Comment by rogerhutchings** [comment]
Done

**Comment by rogerhutchings** [comment]
@eatyourgreens We talked about this the other day, but for the issue:

- When a tool gets changed, we update the schema link attached by the tool to the classification
- Changing the code shouldn't change the workflow; workflows determine _what_ is recorded, the tool / schema determines _how_ it's recorded

**Comment by shaunanoordin** [comment]
If there are no further active discussions on this ADR, I'll clean up the code and merge it with master to ensure all our formal documentation is up to date.

**Comment by shaunanoordin** [comment]
## Update
This PR has been cleaned up and will be merged. Since this ADR only has a status of 'proposed' we can always re-open/continue this discussion at a later date and re-update the documentation accordingly.

**Pull request merged**
