### PR TITLE
Made SubjectViewer props viewBox and src optional

### LINKED ISSUE #1999: viewBox and src props marked as required should be optional
**Package**
`lib-classifier`

**Describe the bug**
In certain scenarios, loaded subjects within a project may give the following console errors.
`The prop `viewBox` is marked as required in `ForwardRef(SingleImageViewer)`, but its value is `undefined`.`
and
`The prop `src` is marked as required in `SVGPanZoom`, but its value is `undefined`.`

These props should be marked as optional.

**To Reproduce**
1. In the `front-end-monorepo` dir, run `yarn bootstrap`
2. cd to `packages/lib-classifier` and run `yarn dev`
3. In a browser, go to https://localhost:8080/
4. See error in console

**Screenshots**
image

**Desktop (please complete the following information):**

### PR DESCRIPTION
**Pull request by ErikOstlund**
Package: `lib-classifier`

Closes #1999 

Describe your changes:
`viewBox` in SingleImageViewer and `src` in SVGPanZoom are now optional.
A lot of Prettier format changes.

To test:
1. In the front-end-monorepo dir, run yarn bootstrap
2. cd to packages/lib-classifier and run yarn dev
3. In a browser, go to https://localhost:8080/
4. Check browser dev tools/console. No more errors! (See Issue #1999 for error details)

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by srallen — CHANGES_REQUESTED** [review]
I'm not sure if removing the requirements for `src` and `viewBox` is what should happen here after I've reviewed this more closely. What is happening is that in practice, when the image subject viewer is initially loading, `src` and `viewBox` are undefined for a moment, which is why we get the prop-types errors. The `viewBox` depends on the image `src` to either set its default or then get calculated correctly to scale, so it seems to me that we shouldn't attempt to render until we have an image source. Could we try another approach to this and leave `src` as required and only render the div and child components if src is defined?

**Comment by srallen** [comment]
@ErikOstlund Any chance you have time to respond to my change request for this?

**Comment by ErikOstlund** [comment]
Inverted the logic statement around the SingleImageViewerContainer. This makes it easier to read and fixed the `src undefined bug`!
Removed the `isRequired` flag on the viewBox PropType; doing this causes no issues and this component is being refactored in the near future.

**Review by srallen — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
