### PR TITLE
NextJS: migrate Sentry to @sentry/nextjs

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Replace `@sentry/node` and `@sentry/browser` with `@sentry/nextjs` in the NextJS apps.
- Replace `initializeSentry.js` with `sentry.{env}.config.js` for each runtime environment: Node, Edge and browsers.
- Use Sentry to capture errors in the generic NextJS `_error.js` page.
- Use `withSentryConfig` to enable Sentry in `next.config.js`.
- Add the `SENTRY_RELEASE` env variable to builds. We use git commit hashes to identify releases.
- Add Sentry Webpack Plugin options to both app builds.
- Add `SENTRY_AUTH_TOKEN` to Docker builds.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Packages
- app-content-pages
- app-projects

## Linked issues
- https://github.com/getsentry/sentry-javascript/issues/8288

## How to Review
This is based on the [`with-sentry` NextJS example](https://github.com/vercel/next.js/tree/canary/examples/with-sentry) so it might be helpful to have a quick read of that.

Sentry error logging and performance tracing should continue to work as before on this branch. A production build of either NextJS app should log performance data to Sentry. Errors should be logged both from Node and in the browser.

If you're running the apps locally, with `APP_ENV=development`, then the environment will be set to [`development`](https://zooniverse-27.sentry.io/issues/?environment=development&project=1492691&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1) in Sentry too.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Content pages builds warn that we’re using the edge runtime, but I don’t see where. Any ideas, @goplayoutside3? You’ve been in that code more recently than anyone else. 

I added `sentry.edge.config.js` to both apps anyway, to squash those warnings. The project app is using middleware.

**Comment by goplayoutside3** [comment]
Hmm I'm not sure why app-content-pages Next app would be different than app-project.

When I build any of the FEM packages on this branch, there's a warning about SENTRY_ORG:
Screenshot 2023-06-12 at 10 34 30 AM

Is that a harmless warning or something that needs to be addressed in this PR?

**Comment by eatyourgreens** [comment]
I guess one way to test that would be to deploy this branch to kubernetes and see if it also warns about the missing organisation slug.

**Comment by eatyourgreens** [comment]
I think this PR is missing the Sentry auth token too. 

https://docs.sentry.io/platforms/javascript/guides/nextjs/

**Comment by eatyourgreens** [comment]
@goplayoutside3 that error should be fixed now, and the Sentry Webpack Plugin should be properly configured during builds. You'll need to get a token from Sentry, and set `SENTRY_AUTH_TOKEN`, if you want to upload source maps from a local production build. It should be set from the repo secrets during GitHub builds.

**Comment by eatyourgreens** [comment]
I'm still seeing a missing auth token in the Docker build. 🤔 
https://github.com/zooniverse/front-end-monorepo/actions/runs/5248205497/jobs/9479441070#step:4:365

**Comment by eatyourgreens** [comment]
Oh, I'm an idiot. The Docker build args are wrong in the build workflows, so `SENTRY_AUTH_TOKEN` is undefined.

**Comment by eatyourgreens** [comment]
Aha!
https://github.com/zooniverse/front-end-monorepo/actions/runs/5248444257/jobs/9479946342#step:4:388

Build logs for the NextJS apps, showing source maps being uploaded to Sentry.

**Comment by eatyourgreens** [comment]
This branch build uploaded source maps to Sentry.
https://github.com/zooniverse/front-end-monorepo/actions/runs/5248444257/jobs/9479946342

I'm seeing Sentry logging happen, in the browser, when I browse Gravity Spy.
https://fe-project-branch.preview.zooniverse.org/projects/zooniverse/gravity-spy

**Comment by eatyourgreens** [comment]
Logs from this PR should show up under [the 'branch' environment](https://zooniverse-27.sentry.io/issues/?environment=branch&project=1492691&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0).

Branch deploys are using the 'staging' environment, so I've fixed that here.

**Review by goplayoutside3 — APPROVED** [review]
Looks good!

**Pull request merged**
