### PR TITLE
Upgrade MobX and MST

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-classifier

Describe your changes:
The base WIP MobX/MST upgrade branch. Fixes for this minor version update will be in separate PRs and this one will merge into master when it's ready. These are not the latest versions, but the versions when breaking changes happen. 

#1003 should be reviewed first, then the PRs updating the individual stores. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by srallen** [comment]
TODO

- [ ] ClassificationStore
- [ ] DataVisAnnotatingStore
- [ ] DrawingStore
- [ ] FeedbackStore
- [ ] FieldGuideStore
- [ ] ProjectStore
- [ ] ResourceStore
- [ ] RootStore
- [ ] SubjectStore
- [ ] SubjectViewerStore
- [ ] TutorialStore
- [ ] UserProjectPreferenceStore
- [ ] WorkflowStepStore
- [ ] WorkflowStore

**Comment by srallen** [comment]
This is ready for final review and I'd like us to do a series of manual tests to make sure TESS is working as expected:

- A user can:
  - [ ] Load the classify page with the project default workflow
  - [ ] Sees a light curve subject
      - [ ] Can pan/zoom/reset
  - [ ] View task help
  - [ ] Submit classification without annotation (annotation is not required for the no transit case)
  - [ ] Annotate and submit classification of a real subject
    - [ ] Does not submit feedback classification metadata
  - [ ] Annotate, submit, and receive feedback of a training subject
    - [ ] Does submit feedback classification metadata
  - [ ] Submit classification and load the subject Talk page
  - [ ] Favorite and unfavorite a subject (authenticated)
  - [ ] Add to a collection (authenticated)
  - [ ] View the tutorial
    - [ ] pops up on initial load (unauthenticated)
  - [ ] View the field guide

**Comment by srallen** [comment]
Also each store's updates was reviewed in separate PRs, so the code and automated tests should be good to go.

**Comment by eatyourgreens** [comment]
Classifying on TESS works for me (running a production build locally.)

`app-project` and `lib-classifier` are now using different versions of MobX (5.5 and 5.9 respectively.) Will this be a problem?

**Comment by eatyourgreens** [comment]
#1108 adds a valid reference check that I missed in the subjects store.

Also, there have been ~100 issues and PRs since this PR was opened. 😱 I vote for getting it merged ASAP.

**Comment by eatyourgreens** [comment]
I may have spoken too soon. I'm seeing this error when I run the `app-project` tests:
`Error: [mobx-state-tree] default value cannot be an instance, pass a snapshot or a function that creates an instance/snapshot instead.`

**Comment by srallen** [comment]
Yeah that last rebase was not easy. I had to re-write a couple of a spec files to make sure it got the changes merged together correctly.

**Comment by rogerhutchings** [comment]
Manual local testing:

  - [ ] Load the classify page with the project default workflow
  - [ ] Sees a light curve subject
      - [ ] Can pan/zoom/reset
  - [ ] View task help
  - [ ] Submit classification without annotation (annotation is not required for the no transit case)
  - [ ] Annotate and submit classification of a real subject
    - [ ] Does not submit feedback classification metadata
  - [ ] Annotate, submit, and receive feedback of a training subject
    - [ ] Does submit feedback classification metadata
  - [ ] Submit classification and load the subject Talk page
  - [ ] Favorite and unfavorite a subject (authenticated)
  - [ ] Add to a collection (authenticated)
  - [ ] View the tutorial
    - [ ] pops up on initial load (unauthenticated)
  - [ ] View the field guide

**Comment by srallen** [comment]
I was running through the manual tests, but the feedback bugs on master (see: #1112) were really distracting me and made me not 100% confident in this PR, so I've done some work on fixing those.

**Comment by eatyourgreens** [comment]
I've opened #1114 to add tests for `isActive` when the subject observer runs.

**Pull request merged**
