### PR TITLE
Upgrade NextJS to 9.5

### LINKED ISSUE #1829: Upgrade to Next 9.5
**Package**
app-content-pages
app-project

Next 9.5 is out! We're on 9.4. Interesting [new features](https://nextjs.org/blog/next-9-5) include:
- stable incremental static builds.
- custom response headers
- base paths and rewrites for incremental migration from an existing site.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrade next to 9.5.5 and change `unstable_revalidate` to `revalidate` for static pages.
Specify `dist: bionic` for the Travis builds.

Package:
app-content-pages
app-project

Closes #1829.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Tests pass locally in Docker. I'm not sure why they're failing on Travis.

**Comment by eatyourgreens** [comment]
Tests are failing in the enzyme adapter. 🤔 
```
TypeError: /home/travis/build/zooniverse/front-end-monorepo/packages/app-content-pages/test/create-enzyme-adapter.js: (0 , _helperModuleTransforms.getModuleName) is not a function
```

**Comment by eatyourgreens** [comment]
Bumping the installed enzyme adapter didn't fix the Travis failure. The CI tests run fine in a fresh Docker image, so I'm not sure why Travis is failing.

**Comment by eatyourgreens** [comment]
Deleting the Travis build cache for PR 1886, then restarting the build, doesn't fix CI either.

**Comment by eatyourgreens** [comment]
Upgrading the Travis build to a more recent version of Ubuntu fixed the tests.

**Review by srallen — APPROVED** [review]
The project app and content pages app build and run. Just needs a rebase.

**Pull request merged**
