### PR TITLE
Refactor survey task styling and related stories

### PR DESCRIPTION
**Pull request by mcbouslog**
Package:
- lib-classifier

Staging: 
- https://local.zooniverse.org:8080/?project=1634&workflow=2434

Towards #1991.

Describe your changes:
- refactors for better light/dark theme styling
- replace StyledHorizontalRule with bottom border on FilterStatus
- refactor ChoiceButton theme
- fix thumbnail issue with width size

Question:
- in PFE requests for SVGs from thumbnail service don't include width/height scaling:
    - (https://panoptes-uploads.zooniverse.org/staging/workflow_attached_image/475c469d-448f-4207-8a58-2cb42a3faa60.svg) 
- with the Media component there's no way to exclude any scaling (the following includes 25x25, but if omitted it defaults to 999x999) and I think including scaling for SVGs results in a 415 error response?
    - https://thumbnails.zooniverse.org/25x25/panoptes-uploads.zooniverse.org/staging/workflow_attached_image/475c469d-448f-4207-8a58-2cb42a3faa60.svg

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [x] Has a storybook story been created or updated?
- [x] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by srallen — COMMENTED** [review]
I've done a quick read through and to answer your question about the SVG icon, I think we can just use a standard image. How `Media` works with images I think needs some improvement in general. 

I'd like to spend a bit more time looking this over for the dark theme changes, so I'll be giving an updated review once I get through that. The other updates are looking good however.

**Comment by srallen** [comment]
Ok I've been playing around dark theme options for survey task and I branched off this one with a few ideas: https://github.com/zooniverse/front-end-monorepo/tree/survey-styling-options

Have a look and let me know what you think. The `FilterStatus` button was failing contrast accessibility tests in dark theme, so I made some changes there as well as updated the background color of the filter buttons to be like the choice buttons... We can discuss tomorrow?

**Comment by mcbouslog** [comment]
> Ok I've been playing around dark theme options for survey task and I branched off this one with a few ideas: https://github.com/zooniverse/front-end-monorepo/tree/survey-styling-options
> 
> Have a look and let me know what you think. The `FilterStatus` button was failing contrast accessibility tests in dark theme, so I made some changes there as well as updated the background color of the filter buttons to be like the choice buttons... We can discuss tomorrow?

Sounds great! Taking a closer look now to discuss during usual Tuesday chat.

**Comment by mcbouslog** [comment]
I think this is looking better now, FilterStatus looks similar to MetaToolsButtons (and passes Storybook Accessibility tests in dark theme), and Choice questions inputs have hover styling, but let me know if I've forgotten anything or any additional edits, feel like I might be, but per notes/memory I think covers what discussed.

**Review by srallen — APPROVED** [review]
I think this is looking ready to go. I had one more additional comment, but non-blocking since it's outside of the scope of this PR.

**Comment by mcbouslog** [comment]
Without `stretch: align` there's a (I'd argue very remote) chance the drop content will stretch quite wide, but I think I can address that separately, or regardless I think rarely if ever wide drop content is preferable to the super narrow content that happens currently all the time. Great suggestion, thank you!

**Pull request merged**
