### PR TITLE
Project: remove inject from the classifier wrapper

### PR DESCRIPTION
**Pull request by eatyourgreens**
Refactor the Classifier wrapper, which loads the classifier into the Classify page, to use `MobXProviderContext` instead of `inject`. I've used a HOC pattern to add store props, so that the tests can continue to run against the undecorated component.

Package:
app-project

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by srallen — COMMENTED** [review]
Are you intending to abstract out the HOC that I see you reusing at some point? If not, I find it harder to read as well as think it'll be harder to swap out MST if we need to by keeping the store connections in the same file. My intention of having separate files was to make it as easy as possible to swap out MST if we find that we need to in the future.

**Comment by eatyourgreens** [comment]
The HOC was a quick refactor, to replace the `inject` function without having to rewrite `ClassifierWrapper` or write new tests. Abstracting it out doesn't make much sense, to me, since the store mappings are unique to each connected component.

Looking back at this,I think the classifier wrapper could do with some documentation too.

**Comment by eatyourgreens** [comment]
OK, I've split the wrapper/container into separate components and had an initial go at documenting them, including a usage example that's copied straight from the project classify page.

**Comment by eatyourgreens** [comment]
Having said that, about premature abstraction, a reusable `useStore` hook is starting to look like it might be useful.

**Comment by srallen** [comment]
A HOC pattern as I see it is meant to be a reusable abstraction. If it can't actually be abstracted, then let's just have clearly separate files. I'd like to see at a glance if a component is connected and reliant on a store, and a separate connector file will show that.

**Review by srallen — APPROVED** [review]
LGTM

**Pull request merged**
