### PR TITLE
Video viewer

### LINKED ISSUE #1877: Create New Subject Viewer for Video Player
**Package**
`lib-classifier`

**Describe the solution you'd like**

As part of the Solar Jets project, we need a subject viewer that will display a video player.

### PR DESCRIPTION
**Pull request by ErikOstlund**
Package: `lib-classifier`

Closes #1877 

Describe your changes:

The goal of this PR is to simply display a video player showing the loaded video.

When a subject is a single video file of type mp4, the subject viewer will display a video player component.  A user can interact with the video player's default controls.
ADR 29 [PR#1930](https://github.com/zooniverse/front-end-monorepo/pull/1930) outlines an argument for choosing `react-player`.

This can be tested by running `yarn bootstrap` to build the packages. Then `cd packages/lib-classifier` and run `yarn dev`.
Project URL: https://localhost:8080/?env=production&project=13789&workflow=16843

Apologies for the number of commits here. The `SingleVideoViewer` components were copied from `SingleImageViewer`. This means there was a lot of extra features in the code not needed for the video viewer. The approach was to remove one item at a time in hopes the commits and my intentions are clear (vs. doing huge commits that look like a murder scene!).
The `SingleVideoViewer` components are at a good starting point now where a video player appears and plays videos and we can now start adding features.

This PR is part of ongoing work and part of the [Video Annotator](https://github.com/zooniverse/front-end-monorepo/projects/13) project.
No styling/positioning has been done yet. This will be address in future PRs.
The `stories` file was not touched. This will be addressed in future PRs.
Unit tests are very basic and only test if components properly render. These will be built upon in future PRs.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## Quick Review

I had a chance to run through this PR (testing on localhost+macOS+Chrome at https://localhost:8080/?env=production&project=13789&workflow=16843) and here some notes I've got so far:

- 👍  The baseline features of SingleVideoViewer works. 
  - The Viewer displays (of course) a single video from a SingleVideoSubject. Example subject:
    ```
    subject.locations = [{
      video/mp4: "https://panoptes-uploads.zooniverse.org/production/subject_location/5e7581cc-1d92-46cc-9762-50457c55c4f9.mp4"
    }]
    ```
  - Video player has the standard play, pause, and volume features. (NOTE: example Subject does not have a video with sound, but it's so standard that presumably sound works.)
  - 👍 Video player is keyboard accessible.

Screen Shot 2020-12-14 at 22 43 41

_SingleVideoViewer component in ideal conditions._

- We have a new dependency: `react-player`
  - ❔  At the moment I'm neutral to the addition of this new dependency as I haven't had much experience with it, but if you'd indulge me in a...
  - _...personal rambling tangent regarding new dependencies:_ if we're going to use `react-player` instead of, say, customising our own `<video />`, it'd be nice to see one or two sentences in the documentation (or an ADR - did I miss an ADR?) that says "we're going with react-player because we think its pros of X outweighs its cons of Y". As I said, I haven't played with react-player yet, but I'm already wondering if the next step of the Solar Jets project requires you to annotate on top of a playing video, and if so, how easy it'd be to do so with a pre-packaged `react-player` vs a barebones `<video />` player. Please note that I'm not discouraging you from using `react-player`, it's just that I've had an equal share of successes and migraines whenever my code relies on external libraries. (Example, good times: using Leaflet.js to very easily display maps and create custom interfaces. Bad times: getting comfy with Jumpstate for state management and then watching the library get deprecated out of left field.)

- ❌  Code formatting: yikes, SingleVideoViewerContainer.js is using tabs instead of spaces. Something must have derped with the auto-linting, but this should be an easy fix.

Screen Shot 2020-12-14 at 23 19 45

- ❓ By default, it seems that `react-player` allows videos to be downloaded and viewed picture-in-picture.
  - In terms of functionality in the classifier, the Download feature is fine. In terms of project management, I'm not sure if every project owner will be happy if users can download their videos so easily. (I mean, as techies, we both know that it's possible to download videos that are displayed on a browser regardless of an easy-to-click Download button, but some projects can be very strict with their data sharing rules.) I'm probably overthinking this, but it's worth pinging someone like @mrniaboc for an opinion.
  - As for the PiP thing, I'm _genuinely_ not sure if that's a good thing or a bad thing. Will there be projects where you don't want Subjects videos playing while, uh, users browse other pages? Will loading the next video be a problem if the previous one is still playing in PiP mode? There are a lot of hypotheticals we can't realistically plan for at the moment, but fortunately, react-player allows us to set `pip={false}` so we can side-step the what-ifs if someone raises it as a problem.

Screen Shot 2020-12-14 at 22 43 50

- ❌ Layout issue: OK, this is the only real bug I've discovered in this quick review. **The video player does not resize to the space available.**

Screen Shot 2020-12-14 at 22 45 01

(I was going to suggest an """easy""" fix of adding flex rules to the react player and its container(s), but something's telling me it might be a wee bit more complicated than that. In any case, there should be a fix for this.)

**Comment by shaunanoordin** [comment]
If we use our current video player as a baseline, (see https://github.com/zooniverse/Panoptes-Front-End/blob/a29f6cdde193d8a50cefbe35424aa8268b324944/app/components/file-viewer/video-player.jsx) here are some small things to note.

- Our current video player allows users to change the play speed. Will this be required in the Solar Jets project, or any future project that uses the SingleVideoViewer?
- None of our projects have ever required a video to autoplay, and we generally don't allow it, which is good design. Cool! Nothing to be done here.
- None of our projects have ever required a video to play on loop... and I don't think it's ever been requested. (Good, because that'd be weird?) But I'm noting it's technically possible if it does come up in some future proposal.

**Comment by shaunanoordin** [comment]
I DID miss the ADR: https://github.com/zooniverse/front-end-monorepo/pull/1930

**Comment by srallen** [comment]
I haven't had a chance to review this yet, but I can answer this:

> By default, it seems that react-player allows videos to be downloaded and viewed picture-in-picture.

We should disable the option to download. This is an issue for some project, including Chimp&See. Their concern is conservation and poaching, but other projects may have other concerns. Technically savvy users will still be able to figure out how to access and download the video, but we shouldn't provide UI for it.

**Comment by srallen** [comment]
For ref, when I disabled the video download UI on PFE: https://github.com/zooniverse/Panoptes-Front-End/pull/3819

**Comment by ErikOstlund** [comment]
For clarification, the controller currently displayed is the default controller and will not be in the final product. The next issue I'm working on is creating a video player controller ( #1880 ). We can dive into what controls are available to users in that PR.
This PR is just to get a video player to display.

**Review by shaunanoordin — APPROVED** [review]
I just had a chat with @ErikOstlund about this PR and I'm going upgrade my quick review to a full one. 👌 

## PR Review

This PR adds a video player for showing off Single Video Subjects.

- This PR has a very straightforward goal of setting up a bare bones SingleVideoViewer, which works (tested on localhost + macOS + Chrome)
  - I understand that the refining the controls (and the download/PiP option, etc) and fixing the layout will be done in a separate PR 👍 
- This PR introduces the new `react-player` dependency; for more details (such as the reason for the selection) please see the [associated ADR.](https://github.com/zooniverse/front-end-monorepo/pull/1930)

### Status

This PR looks good to me - functionality checks are met and the PR's goals are fulfilled - so this gets my 👍. I'll follow up with the other out-of-scope-for-this-PR issues (controls, layout, etc) when their follow up PRs are ready.

Before this PR is merged though, I think it'd be good to figure out what the heck is going on with those invisible tabs [(instead of 2 space)](https://standardjs.com/rules.html#rules) - it's defo gonna be some weird thingamabob setting in VScode.

**Comment by ErikOstlund** [comment]
Fixed formatting issue. Indentation is now using spaces instead of tabs in the `SingleVideoViewerContainer.js` file.

**Review by shaunanoordin — APPROVED** [review]
## PR Review (update)

The latest updates cleaned up the formatting issues with the tabs/spaces - nice! 👍

Searching through the code indicates that all tab characters are gone, so this is LGTM

**Review by srallen — APPROVED** [review]
LGTM as an initial step. Just one thing to note for future iteration that I would suggest and I also mentioned this in the ADR PR: i would recommend validation for hosted location. I don't think we should allow sources from youtube and other similar monetized services since we can't guarantee ads won't show. We also should validate for the mp4 mime type. I think there's a few utility functions that could be useful for this that already exist in the code base, so if you open a tracking issue, I can leave comment there. Thanks!

**Pull request merged**
