### PR TITLE
Upgrade to Storybook 7

### PR DESCRIPTION
**Pull request by goplayoutside3**
## Package
app-content-pages
app-project
lib-classifier
lib-react-components

## Describe your changes

- Upgrade all four packages to use Storybook version 7
- Related updates to storybook config files main.js and preview.js
- Renaming imports related to `composeStory` since `@storybook/testing-react` is now part of `@storybook/react`
- Removed deprecated `subcomponents` arg

## How to Review

`yarn bootstrap` on this branch and then either run `yarn storybook` from the root, or do so on each individual FEM package. All unit tests should still pass and storybook component should appear as they do on `master` or the [deployed version](https://zooniverse.github.io/front-end-monorepo/).

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

## Maintenance
- [ ] If not from dependabot, the PR creator has described the update (major, minor, or patch version, changelog)

### CODE REVIEW

**Comment by goplayoutside3** [comment]
Work on this upgrade is paused for a little bit. I can't get `composeStory` to work correctly with global decorators in lib-classifier. The Storybook-suggested `setProjectAnnotations` function does not work in our mocha setup.js file, and passing `projectAnnotations` into every `composeStory` function does not work either.

**Comment by eatyourgreens** [comment]
> I was able to fix the `composeStory` unit tests by passing` projectAnnotations.default ` rather than just projectAnnotations.

Maybe I'm missing something, but isn't `projectAnnotations.default` the same as
```js
import projectAnnotations from '.storybook/preview'
```
or
```js
import { preview as projectAnnotations }  from '.storybook/preview'
```
since `preview` is the default export from `.storybook/preview`?

**Comment by goplayoutside3** [comment]
> Maybe I'm missing something, but isn't `projectAnnotations.default` the same as import projectAnnotations from '.storybook/preview'.

Yes that will work too! I was initially confused by the examples provided by storybook that all use `import * as projectAnnotations`

**Comment by eatyourgreens** [comment]
You haven't exported `parameters` as a named export from `.storybook/preview`, so that could be why `import * as projectAnnotations` fails.

['Configure story rendering'](https://storybook.js.org/docs/react/configure/overview#configure-story-rendering) says `preview.js` should export `decorators`, `parameters` and `globalTypes` but I can only see `globalTypes` and `decorators` in the exports. I only took a very quick look at the `app-content-pages` config, though. I haven't gone through all the storybook configs.

**Review by eatyourgreens — APPROVED** [review]
Looks good. You might need to rebuild the lock file to install 7.0.11.

**Pull request merged**
