### PR TITLE
Add data-testid to done and done & talk buttons, skip survey task test

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- lib-classifier

## Describe your changes
- adds `data-testid`s to "done" and "done & talk" buttons
- refactors ^ related survey task tests to use `data-testid`s
- skips longest running survey task test

Survey task tests are continuing to occasionally timeout in CI. See #3933 for previous refactors to survey task tests. 
These changes improve the SurveyTask.spec.js tests timing by roughly 2 seconds for me locally. I'm not sure if these changes are a good idea, opening this draft PR for related discussion.

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
- What user actions should my reviewer step through to review this PR?
- Which storybook stories should be reviewed?
- Are there plans for follow up PR’s to further fix this bug or develop this feature?

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by mcbouslog** [comment]
Must be the multiple renders. But I think the remaining multiple renders are necessary based on the user interactions / state changes.

I'm not familiar with how to profile our mocha / RTL tests. Is there a resource (article, blog, or similar) you could point me to to learn more about how to profile our tests? I know I can add `--inspect` to open node dev tools, but I'm not sure what to do with those tool.

**Comment by eatyourgreens** [comment]
Simplest way to profile JS is probably to log timers to the console as it runs. `--inspect` might also work to see what Node's doing while the tests run.

**Comment by eatyourgreens** [comment]
CI tests timed out on this branch 😞 .

**Comment by mcbouslog** [comment]
Closing in favor of #3971

**Pull request closed without merging**
