### PR TITLE
app-root: Add login param as prop to lib-user UserStats and MyGroups components

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- app-root
- lib-user

## Describe your changes
- add `login` param in app-root as prop to lib-user components UserStats and MyGroups, adding functionality for an admin user to be able to access any user's user stats page or their "my groups" pages that lists that user's groups

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX? n/a
- What user actions should my reviewer step through to review this PR?
  - logged in as an admin user:
    - load my user stats page: 
      - lib-user (yarn dev): https://local.zooniverse.org:8080/?users=markb-panoptes/stats
      - app-root (yarn start): https://local.zooniverse.org:3000/users/markbouslog/stats
    - load my groups (listing) page:
      - lib-user (yarn dev): https://local.zooniverse.org:8080/?users=markb-panoptes/groups
      - app-root (yarn start): https://local.zooniverse.org:3000/users/markbouslog/groups
- Which storybook stories should be reviewed? n/a
- Are there plans for follow up PR’s to further fix this bug or develop this feature? Yes, see linked GitHub project, and notably:
    - add containers to main components for cleaner code, can create stories and tests for components
    - pass adminMode boolean from app-root to lib-user, update usePanoptesUser and usePanoptesUserGroup hooks accordingly

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## New Feature
- [ ] The PR creator has listed user actions to use when testing the new feature
- [ ] Unit tests are included for the new feature
- [ ] A storybook story has been created or updated
  - Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetutorial--default)

### CODE REVIEW

**Comment by goplayoutside3** [comment]
I'm not able to load lib-user on this branch via `yarn dev` 🤔 I made sure that I am signed in to staging, for instance I can see that I'm signed in to I-fancy-cats when app-project is run locally, but trying to view https://local.zooniverse.org:8080/?users=markb-panoptes/stats causes my browser to hang. The page doesn't load.

For app-root, I can view your stats at https://local.zooniverse.org:3000/users/markbouslog/stats via `yarn start`, but when trying to see your groups at https://local.zooniverse.org:3000/users/markbouslog/groups, it just says "You are not an active member of any groups." Am I following the manual testing steps correctly?

**Comment by goplayoutside3** [comment]
I just remember your note about this code is dependent on https://github.com/zooniverse/front-end-monorepo/pull/5948 so I'll take a look at that other PR instead!

**Comment by mcbouslog** [comment]
lib-user (yarn dev)
- for me (staging user markb-panoptes) I can load https://local.zooniverse.org:8080/?users=markb-volunteer11/stats (markb-volunteer11 is a different staging user I have) 
- and https://local.zooniverse.org:8080/?users=markb-volunteer11/groups 
- do either of those work for you?
- do your staging user's stats and groups page load ok?
- is your staging user an admin staging user?
- any console errors?

app-root (yarn start)
- for me (prod user markbouslog) I can load https://local.zooniverse.org:3000/users/mcbouslog/groups (mcbouslog is my personal user) , but only when I have admin mode toggled on, maybe if you toggle admin mode on it works?
- I don't need admin mode on to see https://local.zooniverse.org:3000/users/mcbouslog/stats , I'm not sure why there's a discrepancy between admin mode on/off between /stats and /groups 🤔

**Review by goplayoutside3 — COMMENTED** [review]
Hmm so I can see your `/stats` either by running lib-user or app-root locally, while signed-in to my account with admin permissions 👍 

Is there some reason `/groups` is different though? When I run lib-user or app-root locally while signed-in to my account, visiting urls with _your_ account usernames does not show me any groups data. Looking at the browser console, the request for `/memberships` with your `user_id` comes back with an empty array. This is in contrast to looking at my own groups such as `.../users/goplayoutside3/groups?env=staging` where the memberships array correctly has two items.

**Review by goplayoutside3 — APPROVED** [review]
Oh wait! Actually I can see your groups data as long as the admin mode is toggled as "on". That means there's inconsistencies between needing admin mode for `/groups` urls and `/stats` urls. Totally okay for now! We just chatted about the difference and how to handle intended UX from here.

Good to merge as long as duplicate code lines above are addressed 👍

**Comment by mcbouslog** [comment]
Thanks! Noting per conversation, so I don't forget, though needs confirmation - it appears:
- ERAS requires auth for certain endpoints (like for a user's stats) but doesn't require an "adminFlag" param, while... 
- panoptes requires auth for certain endpoints (like for a user's memberships which is used in the MyGroups component) and requires an "adminFlag" request param (`?admin=true` - [panoptes code link](https://github.com/zooniverse/panoptes/blob/master/app/controllers/api/api_controller.rb)) 

I'll pass the `adminMode` boolean from app-root into lib-user and make or more notably not make requests accordingly so:
- a user can NOT see a different user's /stats or /groups
- an admin _with admin toggled on_ can see a different user's /stats and /groups
- an admin _with admin toggled off_ can NOT see a different user's /stats or /groups

**Comment by goplayoutside3** [comment]
👍 Here's a somewhat related Issue to bookmark about admin mode requests too: https://github.com/zooniverse/front-end-monorepo/issues/3691

**Pull request merged**
