### PR TITLE
Classifier - TESS Light Curve Viewer - Improved Axes

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview
Package: `lib-classifier`
Requires #219 to be merged first.

The goal of this PR is to improve the presentation of the Light Curve Viewer's axes.
- [x] the x-axis and y-axis should have margins, to make it look more like a standard scientific chart.
- [x] the data points should also have margins to space it apart from the axis and the surrounding container. (Otherwise, the top-most, left-most, right-most, and bottom-most data points would bleed into the edges and would not be easily visible to users.)

The downside to these presentation updates is that they eat up more visual screen real estate.

screen shot 2018-11-09 at 14 45 35
_"After": this is how the data is now presented. The dead space to the top and right is currently for symmetry, though I welcome thoughts on it. (Add axis labels there?) Note that the data points are now placed behind a clipping mask, so that <circles> don't appear outside of the centre frame once zoomed in._

screen shot 2018-11-09 at 14 46 18
_"Before": the data is jammed into whatever space is available. This is a problem where it's easy to miss the top-most data point (look between the 6 and the 8 of the top x-axis) and the left-most points get smudged by the left y-axis._

Optional:
- [x] Add labels to the x-axis and y-axis? I think this should be a no-brainer but 

### Dev Notes
**IMPORTANT D3 QUIRK DETECTED**

```
this.d3interfaceLayer = this.d3svg.call(addInterfaceLayer)
// this.d3interfaceLayer is now the <svg> element of this.d3svg

this.d3interfaceLayer = this.d3svg
  .append('g')
    .attr('class', 'interfaceLayer')
// this.d3interfaceLayer is now the <g> element

https://github.com/d3/d3-selection#selection_call
"The only difference is that selection.call always returns the selection and not the return value of the called function, name."
```

During this PR, I've discovered that the `d3svg.call(addWhateverLayer)` code didn't function as expected. I incorrectly thought that return of `.call()` would be `whateverLayer`, but instead, it was `d3svg`. The fix for this has been implemented in this PR.

Without this fix, we'd encounter weirdness like <circle.data-point>s being added to the root <svg> node instead of the <g.data-layer> node, making the SVG organisation wonky... although as far as users are concerned, _everything still worked despite the wonkiness._

### Status
~~Development for this PR is now complete. However, it's _probably_ advisable to not review this until #219 is merged, and it should _definitely_ not be merged until 219 is.~~

Ready for review - feedback on the visual design is especially appreciated. (2018.11.12)

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## PR Update
We now have axis labels.

screen shot 2018-11-09 at 19 07 13

**Comment by shaunanoordin** [comment]
## Update
This PR is now ready for review!

**Comment by shaunanoordin** [comment]
## PR Update

screen shot 2018-11-13 at 15 39 51
_New style_

After some thought, here's an alternative style which...
- uses up more of the available screen space (the axes point inwards instead of outwards)
- looks way cleaner, and is closer in style to the previous Planet Hunters layout. 
- BUT data points start smushing into the y-axis when zoomed in. Hmm. Not sure if this is something to worry about.

screen shot 2018-11-13 at 15 42 10
_Note how the data points smush into the y-axis when zoomed in._

**Comment by rogerhutchings** [comment]
It doesn't have to be external files - breaking up the `updatePresentation` method into smaller class methods and having that as a wrapper function would be a good move too.

**Comment by shaunanoordin** [comment]
## PR Update
A few improvements:
- A few actions have been pulled out into external D3 calls.
- `LightCurveViewer.updatePresentation` has been broken down into a few smaller functions, which should make unit testing a bit easier.

A few weaknesses:
- Tests for these broken-down functions are still rudimentary at best, and can use more thought to communicate how they "should" work.

### Status
I'm going ahead and merging this branch, with an eye to improve tests at a later pass.

**Comment by shaunanoordin** [comment]
OH! Derp, forgot to add in that last PR Update: the config has also been properly moved into the props. 👌

**Pull request merged**
