### PR TITLE
Remove self.fetchMedia from tutorial store

### PR DESCRIPTION
**Pull request by eatyourgreens**
Package:
lib-classifier

Remove the public `fetchMedia` action. It was only being exported so that it could be stubbed in tests.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
`fetchMedia` tests still pass, so I think this works.

Previously, I think I was seeing different results between the code and the tests because the stubbed `fetchMedia` method returned a Promise, but the actual `fetchMedia` method is a generator.

**Comment by srallen** [comment]
The generators wrapped by flow always return promises according to MST docs: https://github.com/mobxjs/mobx-state-tree#asynchronous-actions

**Comment by eatyourgreens** [comment]
Weird, so why are the tests failing with `Promise.all`?

**Comment by srallen** [comment]
I cleaned up the stubs a little bit (see: https://github.com/zooniverse/front-end-monorepo/pull/600#issuecomment-476298333). The test for `it should show the tutorial for logged out users` still needs `fetchMedia`'s stub to call a fake because the panoptes client stub for that test doesn't stub `getAttachedImages`. Does that clarify it at all? Could this update close? Do you still want at least the update to not make `fetchMedia` public?

**Comment by srallen** [comment]
It looks like there's some additional changes coming in with this that shouldn't be, too. I went ahead and merged #600 so if there are any more changes you'd like, please comment on #552. Thanks.

**Pull request closed without merging**
