### PR TITLE
Project: Refactor Team page

### PR DESCRIPTION
**Pull request by eatyourgreens**
Refactor the project Team page to fetch the team members with a single Panoptes API query, rather than running one query per person.

## Package
app-project

## Linked Issue and/or Talk Post
Project Team pages can be quite slow to build. Here we can see the SuperWASP Black Holes Team page taking 11s, most of which is spent in 5 calls to `/api/users`.

New Relic report for a slow Team page, which spent ~11s on API calls to /api/users.

## How to Review
Testing a project team page against a live project might be the best way to test this. Here's the team page for HMS NHS.
https://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/about/team?env=production

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [x] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [x] The refactored component(s) continue to work as expected

### CODE REVIEW

**Review by mcbouslog — CHANGES_REQUESTED** [review]
The code LGTM, but when I compare
https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/about/team?env=production&demo=true
to
https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/team
the `translator` team members show as "@UNDEFINED"
Screen Shot 2022-07-07 at 4 48 26 PM

**Comment by eatyourgreens** [comment]
PH-TESS Team page lists 31 people so I bet it’s a page size problem.

**Comment by eatyourgreens** [comment]
That means that the live PH-TESS team page makes 31 requests to Panoptes. 😳

**Comment by eatyourgreens** [comment]
@mcbouslog I've added paging to the user query, which seems to have fixed it when the team is large.

**Review by mcbouslog — APPROVED** [review]
Changes look great, works great!

**Pull request merged**
