### PR TITLE
Engaging Crowds: subject banners

### LINKED ISSUE #2014: Engaging Crowds: Already Seen and Retired subject banners
Engaging Crowds should use different banner messaging for subjects that have been already seen or retired.

Returning to an already-classified subject would display the `Already Seen` banner and a modal explaining why they can still look at this subject; same with a retired subject. 
- [Already seen](https://projects.invisionapp.com/d/main#/console/12924056/438011816/preview)
- [Retired](https://projects.invisionapp.com/d/main#/console/12924056/438011817/preview)

The modal has two options: to return to the project home page or to choose another subject from the subject set. Choosing another subject opens the modal to choose another subject within the classify page: https://projects.invisionapp.com/d/main#/console/12924056/440898093/preview  

Should be able to reuse the modal from the project home page on the classify pages, but should not include the 'back to workflow selection' button and has different text ('choose a subject' rather than 'choose a subject to get started').

_Originally posted by @beckyrother in https://github.com/zooniverse/front-end-monorepo/issues/1875#issuecomment-748225197_

### LINKED ISSUE #2025: Engaging Crowds: subject banner
## Package
lib-classifier

## Describe the solution you'd like
Subjects using priority selection should have a banner showing the current subject's position within its subject set.
Screenshot of the design for a green subject banner, saying 'Subject 12/234'.
[InVision design](https://projects.invisionapp.com/d/main#/console/12924056/429508906/preview)

## Additional context
We're only going to consider workflows that are both prioritised and grouped. It is possible to have prioritised selection across multiple subject sets, in which case Panoptes will present all available subjects in priority order. We are not designing or building for that scenario.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Connect classifier Banners to the store, so that we can display banners based on subject and workflow state. Add a SubjectSetProgressBanner, which shows for prioritised subjects in grouped workflows. The banner indicates subject position within a set and status (already seen or finished.)

https://local.zooniverse.org:8080/?project=11429&workflow=16807&subjectSet=85304&env=production
Green banner showing subject progress for an unfinished subject.
https://local.zooniverse.org:8080/?project=11429&workflow=16807&subjectSet=82738&env=production
Red banner showing progress for a finished subject.

Package:
lib-classifier

Closes #2025.
Closes #2014.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by beckyrother** [comment]
Are my eyes having trouble or does that say Subject 32/11 ?

**Comment by eatyourgreens** [comment]
Your eyes are right. The individual priority numbers in the test set are bigger than the total number of subjects in the set.

**Review by beckyrother — CHANGES_REQUESTED** [review]
"Why am I seeing this?" is really hard to read on both colors. In the invision it's #addde0 but that's hard to read too; can it just be #fff for both?

**Comment by eatyourgreens** [comment]
I think we can change the colours. It's using the default disabled button state, but I don't think we've ever shown that button as disabled before. It's disabled here because there's no tooltip text, at the moment, for those banners.

There's also [an argument for not showing it at all](https://ux.stackexchange.com/questions/120848/should-i-have-a-disabled-button-or-no-button-at-all-if-the-user-doesnt-have-su), if it can't be clicked or tabbed to.

**Comment by beckyrother** [comment]
I'd recommend leaving disabled buttons in; the argument linked above reflects more on being able to close a modal, which would be frustrating to see a close button and not be able to use it. 

In [Slack](https://zooniverse.slack.com/archives/CTXM9AZL6/p1613678789149800) we decided these modals would say "This project allows volunteers to view subjects in sequential order. The number shows you the subject’s position within the total group"

**Comment by eatyourgreens** [comment]
I can add the tooltip text, no problem. I'm not sure what we can do if the subject number, from the manifest, leads to counts like 'Subject 32/11.' That might just be specific to the test subject set here.

**Comment by beckyrother** [comment]
Yeah that sounds like an issue in the manifest we'll have to troubleshoot on that end (@snblickhan) so I'm not as worried about that

**Comment by eatyourgreens** [comment]
Here you go. I'm not sure why the tooltip arrow is in the wrong place, but that's an old bug. I think you can also see it on the live PH-TESS project.

Green subject set progress banner, with a black explanatory tooltip.

Red subject set progress banner, with a black explanatory tooltip.

**Review by beckyrother — APPROVED** [review]
Looks great! Thanks Jim! 

As long as the tooltip arrow is recorded somewhere this is good to go on my end 👍

**Comment by shaunanoordin** [comment]
👍 Basic tests look good!

re: the tooltip, I can hazard a guess as to why it's borked. (It's separate from this PR of course, but still interesting to note.) The tooltip box has no fixed width, so how it works is... (1) it first positions itself (and its tooltip arrow) at the correct position, then (2) it fills up with content, and if the content is a long line of text, the tooltip body just expands to fit and wastes all the careful positioning work it did in step 1.

Going through the code now, but I don't foresee any issues.

**Comment by eatyourgreens** [comment]
Oh, that’s a good point about the tooltip width.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: `lib-classifier`
Context: the Engaging Crowds project (2020-2021) has sequential Subjects, and users need a UI element to keep track of "where they are" in the sequence.

This PR adds a "Subject Set Progress" banner to the Classifier, which is shown only when viewing a Subject that belong to a "sequential" Subject Set.

- The actual criteria for this banner showing is 1. the Subject has a "#priority" metadata field (which implicitly indicates it has a position in the Subject Set) and 2. the Subject Set is .grouped.
- ⚠️ Limitations: the metadata of the Subjects in the Subject Set need to be properly maintained/indexed by the project owners. Or else, a Subject might have priority 9 in a set of only 5 Subjects, or two Subjects might share the same priority, etc, which leads to wonky UI issues.
  - To be clear: this banner just shows the data given to it from Panoptes and doesn't/can't verify if the data is nonsense.

### Testing

Basic tests on mac OS 10 + Chrome 88 on localhost, just to see when & where the Subject Set Progress Banner appears. All tests LGTM.

Banners show, as expected, for Engaging Crowds workflows:
- https://local.zooniverse.org:8080/?project=11429&workflow=16807&subjectSet=82738&env=production
- https://local.zooniverse.org:8080/?project=11429&workflow=16807&subjectSet=85304&env=production

No banners show, as expected, for basic workflows like I Fancy Cats:
- https://local.zooniverse.org:8080/?env=staging&project=335&workflow=693

### Status

LGTM!

**Pull request merged**
