### PR TITLE
add prod service pod disruption budgets

### PR DESCRIPTION
**Pull request by camallen**
Ensure we have these service pods running in our k8s cluster

_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package:

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by zwolf — CHANGES_REQUESTED** [review]
This is new. If I'm understanding the docs, then currently the minimum number of running pods for `project-production` is 2. So if there are 2 running, and the minAvailable in the PDB is 2, then...will they ever be replaced?

>If you set maxUnavailable to 0% or 0, or you set minAvailable to 100% or the number of replicas, you are requiring zero voluntary evictions. When you set zero voluntary evictions for a workload object such as ReplicaSet, then you cannot successfully drain a Node running one of those Pods. 

In this case minAvailable == minReplicas ==  2 in prod/1 in staging. So a deploy would never voluntarily evict a pod, and the new pod would never deploy. Would it be better to set this to minReplicas - 1 to ensure there's at least 1 running pod?

**Comment by camallen** [comment]
> This is new. If I'm understanding the docs, then currently the minimum number of running pods for `project-production` is 2. So if there are 2 running, and the minAvailable in the PDB is 2, then...will they ever be replaced?

Pod disruption budgets ensure that a minimum number of pods are running at any time in the cluster. This may cause issues when doing `node drain` events etc, TBD i guess.

The HPA & replica set will ensure the number of running pods matches our desired targets, taking into account any issues with the cluster. 

> In this case minAvailable == minReplicas == 2 in prod/1 in staging. So a deploy would never voluntarily evict a pod, and the new pod would never deploy. 

Deploys won't be impacted by this change. I copied the existing setup in panoptes to ensure we have at least 2 api nodes running at all times, https://github.com/zooniverse/panoptes/blob/de7a2c9cae481979f55753366eba1bf0183dde10/kubernetes/deployment-production.tmpl#L243-L251

> Would it be better to set this to minReplicas - 1 to ensure there's at least 1 running pod?

We want at least 2 to handle the traffic profile we want for our apps (and ensure they are available).

**Comment by zwolf** [comment]
The quote from the docs seems to say one thing while our Panoptes deploys indicate another. Maybe I'm still missing something about "voluntary evictions" or "node draining". If 2 pods must always be running, and there are currently two pods running, I don't see how we could evict them to deploy. It clearly works, though, so objection withdrawn.

**Review by zwolf — APPROVED** [review]

**Comment by camallen** [comment]
> The quote from the docs seems to say one thing while our Panoptes deploys indicate another. Maybe I'm still missing something about "voluntary evictions" or "node draining". If 2 pods must always be running, and there are currently two pods running, I don't see how we could evict them to deploy. It clearly works, though, so objection withdrawn.

👍 Let's get this out and see how our deploys behave. We can always modify the PDB to better fit our needs

**Pull request merged**
