### PR TITLE
Classifier: validate simple dropdown options

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add a minimum and maximum options count to the simple dropdown task. Add a MenuOptions type which validates the task options against those counts.

Package:
lib-classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
If task creation fails, because the number of options doesn't match the model, then the `WorkflowStepStore` model will error here:
https://github.com/zooniverse/front-end-monorepo/blob/30a8516cb0d0d5b827da00b6b011e058f8f611b6/packages/lib-classifier/src/store/WorkflowStepStore.js#L166-L171

That error handler could be modified to store the error message and display it in the classifier, if we want to make the error visible outside of the dev console. The MST error in the console is a little opaque, but should tell you that the supplied `options` snapshot is not a valid `MenuOptions` type.

**Comment by eatyourgreens** [comment]
Try it out on this workflow, which is a dropdown task with three options: https://localhost:8080/?project=908&workflow=3339

```
Error: [mobx-state-tree] Error while converting `{"help":"","type":"dropdown","selects":[{"id":"c0a8efe878208","title":"Main Dropdown","options":{"*":[{"label":"one","value":"3a5e7c30a1f81"},{"label":"two","value":"ecc0e62c6c11"},{"label":"three","value":"57ca0302a9e4d"}]},"required":true,"allowCreate":false}],"instruc......":"T0"}` to `(DataVisAnnotationTask | DrawingTask | MultipleChoiceTask | SimpleDropdownTask | SingleChoiceTask | TextTask | TranscriptionTask)`:

    at path "/options" snapshot `["one","two","three"]` is not assignable to type: `MenuOptions`
Value does not respect the refinement predicate, expected an instance of `MenuOptions` or a snapshot like `MenuOptions` instead.
```

**Review by srallen — APPROVED** [review]
LGTM, but it'd be nice to have a display of an error in the UI. The test project https://localhost:8080/?project=908&workflow=3339 has a dropdown with only 3 options, so no longer meets the requirements and displays a blank task area:

Screen Shot 2020-10-28 at 11 19 01 AM

Perhaps follow up item?

**Comment by srallen** [comment]
Apologies! Just saw that you noted how the error handling works already, but happy to have that be in a follow up PR. Thanks!

**Comment by eatyourgreens** [comment]
Yeah, I think we can modify the step tasks model so that any invalid task shows a message in the task area. Maybe have a `TaskError` model that gets pushed into `step.tasks` or something like that.

**Pull request merged**
