### PR TITLE
Improve Publications and Team page content accessibility

### LINKED ISSUE #3584: Content pages: H1 Publications tag needs to come before the content filters but after the main body.
## Package
app-content-pages

## Is your feature request related to a problem? Please describe.
#1699 - flagged when resolving this issue.

When using a screen reader, the content filters come before the H1 publications tag, making it difficult to understand what the page is actually for. The 'h1' tag is within the main body but needs to be separate so that the publications heading can be read before the sidebar filters without the content of the main-body coming before the sidebar.

## Describe the solution you'd like
Separate the h1 tag and description from the main body. Put it before the sidebar content filter.

## Describe alternatives you've considered
Label to help navigate screen reader to the h1 tag.

## Additional context
It may mean that TwoColumnLayout will have to be altered to become a three column layout, or the H1 tag added to the AboutHeader, maybe.

### LINKED ISSUE #3693: Selected page isn't highlighted in the About page navigation
## Package
app-content-pages

## Describe the bug
https://www.zooniverse.org/about/publications

'Publications' should be bold and underlined, but is styled like the other navigation links.

### PR DESCRIPTION
**Pull request by MaysaB**
## Package
app-content-pages

## Linked Issue and/or Talk Post
- closes #3584.
- closes #3693. 

## Describe your changes
Made the Publications heading and content tag its own section so that screen readers can navigate the page. This (however) has slightly altered the layout.

See screenshot below:
Screenshot 2022-09-05 at 10 13 00

### Updates 23rd September 2022
- top-level page navigation uses [`aria-current`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) and shows the active page visually, closing #3693.
- Publications filters are marked up as a list, to match the filters on the Team page.
- Every filter is a link with a document fragment identifier, giving each section its own URL eg.
  - http://localhost:3000/about/team#the-adler-planetarium
  - http://localhost:3000/about/publications#nature

## How to Review
- Go to about, [Publications]( http://localhost:3000/about/publications) and use VoiceOver or tab through the links observe how a screen reader navigates the page.
- Reload the page after selecting a filter from the sidebar. The filtered category should be remembered across reloads.

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Page: (http://localhost:3000/about/publications?env=staging)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

### CODE REVIEW

**Review by eatyourgreens — DISMISSED** [review]
The changes look good to me. The Team page also uses `TwoColumnLayout`, so you'll have to update that to pass the page heading down as `heading`.

**Comment by seanmiller26** [comment]
So, the main change (visually) is the 'Publications' header and subtext is now left aligned with the left-hand column. I think this would be ok as long as the other FEM about pages follow suit. As of now only 'Our Team' looks like it has moved to FEM. That being said, all of these About pages will eventually be getting a redesign, but there is no timeline at the moment. So for now I'm wondering is there an option to keep that header aligned with the right column? I just am curious what other options are possible.

**Comment by eatyourgreens** [comment]
I've added some updates to this:
- Publication categories are marked up as a list, just like the Team categories.
- Teams and Publications have URLs that can be bookmarked and linked now eg.
  - http://local.zooniverse.org:3000/about/publications#nature
  - http://local.zooniverse.org:3000/about/team#the-adler-planetarium

**Comment by eatyourgreens** [comment]
@seanmiller26 How about this layout? I've kept the content (and reading order) as
1. Zooniverse page header
2. About section navigation
3. Publications page header
4. Publications category filter
5. Filtered publications list

so that the category list isn't read out of context (#3584.)

Screenshot of the publications page where the header section is aligned to the width of the main content.

**Comment by eatyourgreens** [comment]
Working on this, I spotted that the active page isn't highlighted in the navigation menu (#3693.) I've also fixed that here.

**Comment by seanmiller26** [comment]
Looks good! Thanks @eatyourgreens

I noticed the specific page links still take me to the root page (see screenshot). But is this because the links aren't live yet?
Screen Shot 2022-09-23 at 12 19 46 PM

**Comment by eatyourgreens** [comment]
Yeah, that feature is only on this branch at the moment. I'll merge this so that you can try it out on staging.

**Review by eatyourgreens — APPROVED** [review]

**Comment by eatyourgreens** [comment]
Give this about ten minutes to be staged and it should be available on https://frontend.preview.zooniverse.org/about/publications

**Comment by eatyourgreens** [comment]
Should be working now. Try this link. 
https://frontend.preview.zooniverse.org/about/publications#physics

**Comment by seanmiller26** [comment]
Took a little longer, but works!

**Pull request merged**
