### PR TITLE
Clean up the Docker builds

### PR DESCRIPTION
**Pull request by eatyourgreens**
After building the libraries and apps, remove `node_modules` and `src` from each package before installing only the production dependencies.

This should cut the size of the image by removing unnecessary files like the storybook packages and so on.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
All of them

## How to Review
Run a Docker build and check the size of the final image.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

### CODE REVIEW

**Comment by eatyourgreens** [comment]
The changes here were a workaround for an old bug in Yarn. If you were to do the following, then dev dependencies wouldn't be deleted from `node_modules`, as expected. Instead, you'd have to manually delete `node_modules` before running the production install.

```sh
# Test and build with dev dependencies.
yarn install --frozen-lockfile
yarn test
yarn build
# Run the built app with only the production dependencies.
yarn install --production --frozen-lockfile
yarn start
```

I'm not sure if that bug is still an issue. If not, the production install will remove all installed packages, then install only the production `node_modules` needed to run the app. The manual `rm -rf` step isn't needed.

**Comment by goplayoutside3** [comment]
Just linking the relevant Slack thread with detailed information on why this type of clean up was investigated: https://zooniverse.slack.com/archives/CANKLB50E/p1699300287300439

**Comment by goplayoutside3** [comment]
As per the Slack convo linked above, these changes did not affect the size of the Docker image. Any reason not to close this PR?

**Comment by eatyourgreens** [comment]
It's worth double checking whether a local `yarn install --production` deletes dev dependencies from inside individual package directories, but I think this can be closed. Something like `du -dh packages/app-project/node-modules` before and after a production install should tell you if `node-modules` gets smaller.

**Comment by goplayoutside3** [comment]
I'm going to close this for now, but will make to myself to refer to it during the whole FEM package re-org process.

**Pull request closed without merging**
