### PR TITLE
Classifier: check classification and step before rendering Tasks

### LINKED ISSUE #2154: Engaging Crowds: changing workflow, while the classifier is mounted, crashes the classifier
## Package
lib-classifier

## Describe the bug
https://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify

Select a workflow and subject set to get started. Now, click 'Classify' (in the project navigation) in order to open the workflow selector again. Select a different workflow, and subject set, and the classifier will crash while loading the new workflow.

Sentry error from my development build: https://sentry.io/share/issue/3b2302e0866a47b9ba7857c632c9d031/

Screenshot of the classifier showing the error message: e.step is undefined

## Additional context
Found while reviewing #2141. It can't be reproduced in the dev classifier, because changing the props there involves re-loading the page. To investigate it, you must build the classifier, then run it in the NextJS project app. Try changing the classifier's props, while the classifier is mounted, and you should run into this bug.

The underlying cause seems to be that `Tasks` uses `workflowSteps.active` without checking that it's defined. When the active workflow changes, there's a couple of renders where `workflowSteps.active` is undefined.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Package:
lib-classifier

Closes #2154.

The `Tasks` component will crash the classifier if it renders while `workflowSteps.active` or `classifications.active` are undefined. That condition can be triggered by changing the active workflow while the classifier is mounted (#2154.)

This PR fixes that bug by checking for `classification` and `step` before calculating the `isComplete` prop. ~~It also adds a default value for the `step` prop, so that `step.tasks` doesn't crash the classifier.~~ The `Tasks` component also waits until `classification` and `step` are defined, before rendering.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I think this needs #2141 to be merged before it can be properly tested.

**Comment by shaunanoordin** [comment]
Code read looks good; the readiness-checks seem to be in the right places.

I was initially worried that `annotatedSteps.latest` could return undefined (e.g. if AnnotatedSteps.steps = {}) but then again, the initial code never checked for that and we didn't encounter any issues.

Testing begins!

**Review by shaunanoordin — COMMENTED** [review]
## PR Review

Packages: `app-project`, `lib-classifier`
Fixes #2154 
Follows #2141

This PR attempts to fix an issue where, if we've loaded Workflow X to the Classifier, _and then switch to Workflow Y,_ (e.g. by clicking on the 'Classify' link to open the WF selection menu, for a multi-workflow Project) the Classifier will proceed to crash.

- As noted in 2141, the issue is likely that - in the twilight between unloading WF X and loading WF Y - there are periods in the logic flow where Tasks for _Workflows that no longer exist_ are still referenced memory.
- This PR attempts to fix the issue by adding more logic checks.

Code read looks good, but I'm running into issues with tests.

### Testing

Testing follows [the same procedures as before.](https://github.com/zooniverse/front-end-monorepo/pull/2141#pullrequestreview-652885167) Special care has been taken to 1. ensure that the `master` (with PR 2141 merged) has been merged into this PR, and 2. that `yarn bootstrap` has been run, since we're testing changes to lib-classifier by running app-project.

(Refresher) URLs used for testing:
- (A) ~~[Project home](http://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service?env=production&demo=true)~~ _not used_
- (B) [General classify page](http://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify?env=production&demo=true)
- (C1) [Specific workflow+subject set classify page](http://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/18109/subject-set/82738?env=production&demo=true) - WF 18109, SSet 82738
- (C2) [Specific workflow+subject set classify page for a _different_ WF+SSet](http://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/18110/subject-set/83397?env=production&demo=true) - WF 18110, SSet 83397

Basic tests look fine:
- Loading up the Classifier _once_ in [Scenarios 1, 2, 3, 4](https://github.com/zooniverse/front-end-monorepo/pull/2141#pullrequestreview-652885167) look good 👍 
- Loading up the Classifier with _the same WF + SSet again_ in Scenario 5a also looks good 👍 

Problems arise when I try to change to the second workflow.

**Scenario 5:**
- Go directly to (C) specific classify page of _first workflow_
- Click on the 'Classify' link to go to the (B) general classify page
- Choose a _different_ WF + SSet_
- I'm taken to the (C2) specific classify page for the _second workflow_ ...
  - The Classifier crashes with the error, `TypeError: Cannot read property 'nextStepKey' of undefined` ❌ 
  - Previously, the error was: `TypeError: Cannot read property 'isComplete' of undefined`. I'm still counting this as an improvement!

### Status

I think the fixes in this PR are on the right path, but there are probably more gotchas down the line that need to hammered as they pop up.

My earlier comment about `annotatedSteps.latest` being _undefined_ miiight(?) have been closer to the mark than I expected, but I haven't debugged enough of this to provide more useful info.

brb, gonna dig into AnnotatedStep's hasNextStep() to see if this is where things are failing.

**Comment by eatyourgreens** [comment]
@shaunanoordin thanks for jumping on this so quickly. That `nextStepKey` error could be coming from `workflowSteps.active.nextStepKey(annotations)` when the active step hasn't been set yet. The nav buttons make checks like that when deciding whether to show Next or Done.

The `latest` step can be undefined, between first starting a subject and the classification being created. I'd hoped to guard agains that by wrapping it in a check for `classification` and `step`.

**Comment by eatyourgreens** [comment]
@shaunanoordin I've removed the default step, and updated the tests. `Tasks` should now render null while the workflow step and the classification are changing.

I rebased onto the latest master, so you might have to delete your local branch and pull down a fresh copy of this one.

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

Nice! I've re-pulled and re-bootstrapped this branch, and I can confirm that all functional tests (Scenarios 1 to 5, and all variations thereof) are looking good! 👍 

This PR has now properly fixed the issue where the Classifier _was_ crashing whenever a user switched workflow. LGTM, approved!

**Pull request merged**
