### PR TITLE
Adjust preview thumbnail size

### PR DESCRIPTION
**Pull request by eatyourgreens**
Set the maximum subject thumbnail size to 270px width, 200px height.

See #1152.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && yarn bootstrap` and app works as expected?
- [ ] Can you run a [production build](https://github.com/zooniverse/front-end-monorepo#getting-started) of the app?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This might introduce large gaps between the preview images on large viewports. See the screenshots in this discussion: https://github.com/zooniverse/front-end-monorepo/pull/1017#discussion_r320628438

**Comment by eatyourgreens** [comment]
Here's PH-TESS on a reasonably large viewport, where the grid column width is ~ 350px but the image width is 270px.

The Recent Subjects box on a large viewport, where each preview has a large, white gap to the right.

**Comment by beckyrother** [comment]
Honestly this whole page looks rough at that wide of a viewport. Can we do like we do on the non-logged-in home page and set a max width for the page? Here's the widest I've designed for: https://projects.invisionapp.com/d/main#/console/12924056/344288108/preview

**Comment by eatyourgreens** [comment]
Screenshot showing heavily pixelated previews of 19th Century manuscript pages.
Transcription projects look particularly bad at 270px by 200px, because the thumbnail is resized down to 200px wide, then stretched out to 270px.

**Comment by beckyrother** [comment]
Sorry I don't understand what that means? It starts square at 200x200 and is resized back up to 270?

**Comment by eatyourgreens** [comment]
I think it looks much better if the thumbnails are sized to a 400x400px square, then cropped inside a 270x200px window with `overflow: hidden`.
Screenshot showing previews for 3 manuscript pages, where the images are resized down rather than up in the browser.

**Comment by eatyourgreens** [comment]
>Sorry I don't understand what that means? It starts square at 200x200 and is resized back up to 270?

Yep, if you give the thumbnail server dimensions of 270x200, it will give you back a thumbnail that fits inside that box. In this case, that means it will reduce the height down to 200px.

**Comment by eatyourgreens** [comment]
@beckyrother you can see the pixelation that causes in the preview images on the[ Worlds of Wonder home page](https://www.zooniverse.org/projects/lbeiermann/worlds-of-wonder).

**Comment by beckyrother** [comment]
Got it, thanks! Agreed that the 400x400 option looks much better.

**Comment by rogerhutchings** [comment]
On smaller screen sizes, the preview image comes out at 400 x 400: 

Screenshot 2019-09-26 10 33 22

**Comment by eatyourgreens** [comment]
Good point. Maybe the thumbnail size should be 700x700.

**Comment by rogerhutchings** [comment]
It might be a good place to use a `srcSet`?

**Comment by eatyourgreens** [comment]
Maybe, but that would be a change to the shared Media component. I've already got some fixes for sizing in that component in #1160.

**Comment by eatyourgreens** [comment]
@rogerhutchings thumbnails should be fixed on tablet-sized screens now.

**Comment by eatyourgreens** [comment]
Over in #1131, I'm experimenting with using CSS values, not numbers, for `height` and `width`.

**Comment by srallen** [comment]
I would be supportive of adding `srcSet` to the `Media` component. :+1:

**Pull request merged**
