### PR TITLE
Update grommet and related dependencies

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-grommet-theme, lib-react-components, app-project, app-content-pages, lib-classifier

Updates grommet, grommet-icons, and styled-components before bumping the version and publishing the zooniverse grommet theme again. I also changed a few dependencies that were using caret to tilde for consistency. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && yarn bootstrap` and app works as expected?
- [ ] Can you run a [production build](https://github.com/zooniverse/front-end-monorepo#getting-started) of the app?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Ignore me. Travis CI says no.

**Comment by srallen** [comment]
You can manage dependencies across packages with yarn's `workspaces` command

**Comment by eatyourgreens** [comment]
```
TypeError: Cannot read property 'extend' of undefined
608    at /home/travis/build/zooniverse/front-end-monorepo/node_modules/grommet/components/FormField/FormField.js:64:32
```

**Comment by srallen** [comment]
It's the styled-components update. I'm going to do redo the grommet update in isolation.

**Pull request closed without merging**
