### PR TITLE
Bug Fix: Markdownz ordered lists

### PR DESCRIPTION
**Pull request by goplayoutside3**
## Package
lib-react-components

## Linked Issue and/or Talk Post
https://github.com/zooniverse/front-end-monorepo/issues/3039

## Describe your changes

The root of the ordered list bug lies in FEM's `remark` version. Given the following input
 ```jsx
Ordered list:
1. item one 
2. item two 
3. item three
```

remark version 11 processes it to:

```jsx
Ordered list:
1\ item one 
2\ item two 
3\ item three
```

and it's rendered as a paragraph.

We want the original input to be processed to:

```jsx
Ordered list:

1. item one 
2. item two 
3. item three
```

I upgraded to remark version 12 to fix this issue, but v12 drops support for using footnotes in markdown. 

**Footnotes:**
I installed `remark-footnotes` to patch that. In order to get multi-line footnotes to work in this PR, I added 2 spaces (1 tabspace) to the example in storybook. I could not find live FEM projects that use footnotes and would potentially be affected by this upgrade. Markdown guides in the project builder don’t mention footnotes either, so I’m fairly confident the addition of remark-footnotes will go unnoticed.

**List Styling**
In our Grommet theme, elements that typically precede a list (such as Text, Heading, Paragraph, etc) all have a `margin-bottom`. FEM wasn't adding any themed styling to lists, so the default browser styling applied to `<ul>` and `<ol>` included a `margin-top`. The combined margin settings resulted in double-space above every list, and list items were rendered at 18px rather than the standard Zooniverse 14px. I fixed list styling in Markdownz component.

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
 
I did a lot of comparing between live FEM projects and this branch locally. 

Make sure to run `yarn bootstrap`, and projects that included unordered bullet lists in their About Pages will see a minor styling change with the new margin styling. See Beyond Border’s [Research](https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/about/research) page on the live site and [locally](https://local.zooniverse.org:3000/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/about/research?env=production).

See an ordered and unordered list on Mark's test project: https://local.zooniverse.org:3000/projects/markb-panoptes/digileap-testing/about/research
 
- Which storybook stories should be reviewed?
 
Markdownz's storybook includes ordered and unordered lists. I modified the example markdown by removing whitespace preceding a list. View the story locally: http://localhost:6007/?path=/story/components-markdownz--light-theme-default&globals=locale:en;locales.en:English;locales.test:Test+Language
 
- Are there plans for follow up PR’s to further fix this bug or develop this feature?
 
When time allows, I plan to follow up with a refactor of Markdownz’s stories and unit tests to remove the legacy knobs code.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [x] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Linking #2607 to this. I think 12 is the latest version we can upgrade to without breaking changes.

**Review by eatyourgreens — APPROVED** [review]
Looks good to me. Let’s get this out onto staging.

**Comment by goplayoutside3** [comment]
> Looks good to me. Let’s get this out onto staging.

Awesome! I trust that you've looked at the code changes 😄 but please use the reviewer checklist too. I want to keep our team in the habit of using it to catch bugs by running PR branches locally, testing other browsers, etc thanks!

**Comment by eatyourgreens** [comment]
I read through the changes on my phone. They look innocuous but do wait for a second opinion if they need to be checked in a browser.

**Review by mcbouslog — APPROVED** [review]
LGTM! List item text styling looks better now too.
Confirmed issue, tested on noted projects and a few extra, including:
- https://local.zooniverse.org:3000/projects/markb-panoptes/digileap-testing/about/research
- https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats/about/team?demo=true
- https://local.zooniverse.org:3000/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/about/research?env=production
- https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/about/research?env=production&demo=true
- https://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/about/faq?env=production&demo=true

**Pull request merged**
