### PR TITLE
Classifier: improvements to the Finished popup

### PR DESCRIPTION
**Pull request by eatyourgreens**
Some small improvements to the popup that disables the task area for finished subjects.
- check `subject.alreadySeen` instead of `subject.already_seen`.
- close the popup when Next Available is pressed.
- close the popup when Select a Subject is pressed.
- close the popup when `isOpen` is false.

This fixes a few small bugs that @mrniaboc found while testing.

https://local.zooniverse.org:8080/?project=12268&workflow=18504&subjectSet=96699&subject=64213748&env=production&demo=true

Package:
lib-classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by shaunanoordin — COMMENTED** [review]
## PR Review

This PR tweaks the behaviour of the `<DisabledTaskPopup>` component.

- Context: this component only appears on specific projects/workflows that allow users to select individual subjects, and only when the selected subject is "finished"
- Clicking "Choose a New Subject" or "Next Available Subject" should hide the popup. (See Testing, though)

Code read looks good, though I have limited testing functionality.

### Testing

Tested on localhost, macOS + Chrome.

- Testing URL: https://local.zooniverse.org:8080/?project=12268&workflow=18504&subjectSet=96699&subject=64213748&env=production&demo=true&finished=true with a _forced "Finished" popup_
- Clicking "Choose a New Subject" closes the popup as expected
- Clicking "Next Available Subject" does close the popup, but after proceeding to the next Subject, the popup appears again (...because of the forced ?finished flag)

I can't fully replicate the actual behaviour given the circumstances, but I'm confident enough that things will work as expected, based on the limited test and good code read.

### Dev Notes

❗ That said, @eatyourgreens you made this comment:
> check subject.alreadySeen instead of subject.already_seen

However, I don't see `already_seen` or `alreadySeen` changed anywhere in this PR. Was there supposed to be a change in TaskArea.js, line 35, that was missed in this PR?

```
const finished = (subject && URLParams?.finished) || subject?.retired || subject?.already_seen  // Here?
```

### Status

New behaviour tweaks work fine, but I have a question about the `subject.already_seen` comment.

**Comment by eatyourgreens** [comment]
Argh. Yes, that line was supposed to change. I must have lost it while resetting some debug logs.

**Comment by shaunanoordin** [comment]
Cool, just pop that back in and this PR is good to go! 👍

**Review by shaunanoordin — APPROVED** [review]
LGTM! 👍

**Pull request merged**
