### PR TITLE
lib-classifier: Fix survey task Confusion drop positioning

### LINKED ISSUE #5112: Confused With Modal - design improvements
## Package
lib-classifier

## Is your feature request related to a problem? Please describe.

This Issue stems from this Talk [post](https://www.zooniverse.org/talk/17/3015323). In that post, the volunteer explains that in FEM, they have a difficult time classifying workflows that use the survey task. 

The "Confused With" modal is part of the survey task area, and when the modal is opened it overlaps the example image of the currently selected choice. In contrast in PFE, the modal always opens below its button regardless of where the volunteer has scrolled the page to.

Examples using Snapshot Wisconsin:
Screenshot 2023-08-03 at 3 01 21 PM
Screenshot 2023-08-03 at 3 01 56 PM

As far as I understand, the "confused with" modal was designed this way to keep it in view while still being able to see the actual subject image. On a common desktop viewport size, if the “confused with” modal appeared lower on the screen and the volunteer needing to scroll down to it the subject image would be hidden at the top of the screen.

The volunteer also provided screenshots in their Talk post. From those screenshots it's obvious that they use a really large computer monitor. In their viewport, the subject image is always visible even with a very tall task area with lots of survey options:
image

Also in FEM, the "confused with" modal jumps from above its button to below its button as the volunteer scrolls down the page. I think it was initially built that way to keep the modal in view. See example video:

https://github.com/zooniverse/front-end-monorepo/assets/23665803/33db34c3-2004-4f56-9c69-61cbeae00cdc

## Describe the solution you'd like

1. Should the "confused with" modal positioning be adjusted to match PFE's behavior? Should it always open below its button? 

2. Should it open above its button, but be draggable (like the field guide)?

## Additional context

Note that any update to this feature in FEM's classifier should be followed up by a post in the volunteer's Talk thread linked above.

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- lib-classifier

## Linked Issue and/or Talk Post
- closes #5112 

## Describe your changes
- positions Confusion drop below ConfusedWith button
- prevents repositioning Confusion drop per browser view height, affixes Confusion drop below ConfusedWith button
- fix `characteristic.values` type warning, similar to #6087 

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
  - https://local.zooniverse.org:8080/?project=1634&env=staging&workflow=2434
- What user actions should my reviewer step through to review this PR?
  - in [an existing survey task](https://frontend.preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify/workflow/2434?env=staging) and locally, compare:
  - click a survey task choice confusion, note the confusion drop positioning
  - with the confusion drop open, scroll up and down
- Which storybook stories should be reviewed?
  - http://localhost:6006/?path=/story/tasks-survey-choice--default
- Are there plans for follow up PR’s to further fix this bug or develop this feature? no

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by mcbouslog** [comment]
@seanmiller26 - let me know when and I think I can deploy this using the fem branch deploy for you to review.

**Comment by seanmiller26** [comment]
@mcbouslog I can review anytime today!

**Comment by seanmiller26** [comment]
Looking good, but I'm getting this odd bug:

Screenshot 2024-09-05 at 1 53 51 PM

Screenshot 2024-09-05 at 1 54 18 PM

If I open the modal with it mostly offscreen, only the visible portion gets a drop shadow. If I am scrolled down the page when opening, it gets the full shadow.

**Comment by seanmiller26** [comment]
I'd like for us to match other FEM modals regarding `box-shadow` 
Value pulled from transcription modal: (0, 0, 0, 0.3) 0px 12px 24px

**Comment by mcbouslog** [comment]
Thanks @seanmiller26 !

I can confirm the strange drop shadow behavior, but unfortunately there's nothing we're doing in our code to change, I believe that's a Grommet bug.

I've updated the box-shadow to match the "transcription modal" which I think comes from the [lib-react-components Modal](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-react-components/src/Modal/Modal.js#L33) in [3676975](https://github.com/zooniverse/front-end-monorepo/pull/6267/commits/36769754411c94f6516949edb8468f408169ecc2).

**Review by seanmiller26 — APPROVED** [review]
Design looks ok!

**Comment by shaunanoordin** [comment]
I'm tagging in to review this! Code read looks pretty straightforward, so I expect a quick turnaround.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: lib-classifier

This PR is primarily a styling update for the Survey Task's "Confused With" popup.

- Now, when the popup appears, it will always appear _below_ the  button that summons it. (Instead of above/below, depending on available space.)
- Also, some React prop types have been updated.

Screenshot: the "confused with" popup for "Ocelot" appears BELOW the "Ocelot" button.

image

Code changes look straightforward, and UI changes look good in my browser. Tested with macOS + Chrome on app-project on WildCam Darien on [localhost](https://local.zooniverse.org:3000/projects/wildcam/wildcam-darien/classify/workflow/3033?env=production).

### Dev Notes

@mcbouslog : I took a look at the "clipped shadow" bug that Sean encountered, and I have some notes. These can be addressed in a later PR if you'd like - or, if you just want the potential solution without the jibba jabba, then jump to the part marked 💡. 

OK, so, long anaysis: the `<ConfusedWith>` component creates `<StyledDropButton>`s with `dropProps.elevation = 'xlarge'`, and thats where the shadows are coming from.

Problem is, the popup that's created by DropButton has a dynamically-created div (i.e. dynamically inserted into the DOM) _with a fixed height that depends on the viewport at the time it's created,_ and the shadow is applied to that _container,_ instead of the actual _content._

Or to put it in a screenshot: the red is the container div (which pulls from `DropButton`'s dropProps) with _fixed_ height, and the blue part is the actual content with the actual content height (i.e. DropButton's dropContent, i.e. i.e. `<Confusion>`)

image

The shadow is attached to the red bit, instead of the blue bit.

💡 One possible solution then is...

- `<ConfusedWith>`: set `dropProps.elevation='none'` (must set to none, because the container has a default elevation)
- `<Confusion>`: add `elevation='xlarge'` OR turn Confusion's Box into a StyledBox with the specific shadow style Sean wanted.

This ensures the shadow is applied to the content, not the container.

### Status

LGTM!

**Comment by mcbouslog** [comment]
Thanks @shaunanoordin! I've updated as suggested, the `xlarge` elevation is the same as noted.

**Pull request merged**
