### PR TITLE
[VSLCV] Responsive grid

### LINKED ISSUE #1548: [VSLCV] Fallback for small screen sizes
**Package** lib-classifier

One of the ideas from the last discussion with the variable star researchers is to have a message come up on small screen sizes that states that this data is best viewed on tablets and desktop rather than try to come up with a responsive view of the data. We need to make a few decisions:

- What's the screen size cut off for this?
- What should the message say?
- How should the message be displayed?

This effectively scopes this project to not be able to be participated on with mobile users so we should confirm this is ok before designing for it.

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

Closes #1548

Describe your changes:
This add's vx's `withParentSize` HOC to the `VariableStarViewer` to get the parent container's width as a prop. If the parent container width is less than or equal to 768, then we fallback to a single column layout. This isn't great, but it's better than nothing and we can consider additional messaging or alternatives based on if we get feedback about it during the beta.

stacked-layout

This can be viewed by running `yarn bootstrap` first from the parent repo folder, then going into the `app-project` folder and running `yarn start` and going to http://localhost:3000/projects/adamamiller/stellar-sleuths/classify. Then you can use dev tools to switch to any phone or tablet layout.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by beckyrother — APPROVED** [review]
Nice!

**Comment by ErikOstlund** [comment]
On initial page load, all charts look good. When I resize the window below 1407px, the charts layout change to single column. But, if I resize the window greater than 1407px, the top right chart extends under the task component. This also happens if I resize the window from a large size to a smaller size, but not yet hit the single column breakpoint.
I'm not sure what the best solution would be? Maybe consider only using a single column layout any any screen size?
Screen Shot 2020-10-01 at 12 21 06 PM

**Review by ErikOstlund — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by srallen** [comment]
@ErikOstlund I fixed this by wrapping the bar charts in a Grommet `Box` (this is a component that auto applies flex box styling to a div) and set the wrapper's flex-basis to 1/2. Could you have a look again? Thanks!

**Review by ErikOstlund — APPROVED** [review]
The fix is looking good! Charts are now responsive and do not extend under the task component.
All tests are passing locally.
👍🏽

**Pull request merged**
