### PR TITLE
Classifier: localise drawing subtasks

### LINKED ISSUE #3313: Transcription popups don't show text task instructions
## Package
lib-classifier

## Describe the bug
On staging, task instructions are missing from the text task popup when you transcribe a line.

## To Reproduce
1. Load a transcription workflow, eg. https://frontend.preview.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters/classify/workflow/18542
2. Click a couple of times to add a new line.
3. The task instruction is missing from the text task in the popup.

## Expected behavior
If you compare staging with production, you can see that the text task instructions are shown in production.

## Additional context
Since #3193 merged, task instructions are now read from `task.strings.instruction`, but drawing sub-tasks haven't been updated to use translation strings. #3223 adds translations to drawing sub-tasks, which will fix this.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Add `task.setToolTaskStrings(stringsSnapshot)` to drawing and transcription tasks. It parses individual task strings from `stringsSnapshot` for each drawing tool, then applies those snapshots to each tool subtask in `tool.tasks`.
- Run `self.setToolTaskStrings` whenever a drawing task's language strings change.
- Add tests.

- Based on #3193.
- Closes #3313.

## Package
lib-classifier

## How to Review
Each drawing tool in the storybook has a subtask story, which can be used to check that the task instructions and questions are displayed correctly. Compare with #3193, where the questions and instructions are missing.

#3198 adds localised answers for the question tasks.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [x] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## New Feature
- [x] The PR creator has listed user actions to use when testing the new feature
- [x] Unit tests are included for the new feature
- [x] A storybook story has been created or updated
  - Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetutorial--default)

### CODE REVIEW

**Review by goplayoutside3 — COMMENTED** [review]
Can confirm this solves Issue #3313, and I can see the transcription subtask instructions in Maria Edgeworth project run locally. A couple things to address though:

1. Storybook - I don’t see subtask instructions in the Drawing Tools / Transcription Line story, and I don’t see subtask instructions on the Tasks / Transcription story.
2. Is there a live project (or test project) with 2+ languages you used with this PR to test that the subtask instructions are correctly translated in a browser? For example, dual language [dropdown workflow](https://local.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/classify/workflow/3339) was a good test for that task type.

**Comment by eatyourgreens** [comment]
I've gone through the drawing/transcription stories and made sure the mock workflow for each story has `workflow.strings`. It was set to an empty object by default, which explains why you couldn't see any text in any of the stories. All the tasks and the drawing tools should have text in the storybook now.

**Comment by goplayoutside3** [comment]
> I can see task instructions for Maria Edgeworth Letters ('Transcribe the line of text that you've marked.') in the dev classifier, but not when I build the classifier and load it into the NextJS app.

Oh interesting. I was just going to comment that the storybook looks good now, and that I can see translated subtask instructions on your monorepo drawing tools workflow + Maria Edgeworth project locally.

If I draw points on the monorepo drawing tools workflow and change the locale, progress is lost though.

**Comment by eatyourgreens** [comment]
Yeah, any project with prioritised workflows is broken until #3273 merges.

**Comment by eatyourgreens** [comment]
>I can see task instructions for Maria Edgeworth Letters ('Transcribe the line of text that you've marked.') in the dev classifier, but not when I build the classifier and load it into the NextJS app.

I've pulled down the latest code, rebuilt the libraries and apps and I'm seeing the transcription task work now. I must have been looking at an outdated build earlier.

**Review by goplayoutside3 — APPROVED** [review]

**Pull request merged**
