### PR TITLE
Project: set UPP loading state after refreshing from Panoptes 

### LINKED ISSUE #5008: Intermittent bug: Workflow choices and Classifier aren't displayed
## Package
app-project

## Describe the bug
I'm not sure how to trigger this, but it's possible to load the project app in such a state that neither the classifier nor the workflow selector components are shown to a logged-in user.

## To Reproduce
I've run into this on Gravity Spy. @snblickhan has triggered it on How Did We Get Here? and I think @mcbouslog might have managed to trigger it too.

I think it happens when `appLoadingState` in the project app is never set to 'success', so the workflow selector and classifier are permanently waiting for a user session to sign in.

## Expected behavior
Once authentication is complete, and any user resources are loaded, workflow choices should display on the home page and the classifier should display on the project Classify page(s).

## Screenshots
Screenshot of the Gravity Spy home page, with a white space where the workflow menu should be.
Screenshot of the Gravity Spy Classify page, with a white space where the classifier should be.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Ensure that the UPP loading state is set to 'success' after refreshing preferences for an existing user. If it is set to anything other than 'success', the classifier and workflow choices will not be shown to a signed-in user.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

- closes #5008.

## Package
app-project

## How to Review
Check that workflow choices show on the home page, and that the classifer loads properly, even when the page loads with a cached user from browser session storage.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Review by goplayoutside3 — DISMISSED** [review]
Running this locally, I'm not able to visit the classify page for production FEM projects. I get the following error: 

Screenshot 2023-07-13 at 1 52 29 PM


On i-fancy-cats, the task area intermittently does not load:

Screenshot 2023-07-13 at 1 53 19 PM

**Comment by eatyourgreens** [comment]
That error has been happening in dev mode for a while now. I’ve definitely run into it before. I’m pretty sure it’s not introduced by the changes here, since they don’t touch the classifier. 

I would love to know what’s causing it. Is it limited to this branch? 


In terms of the change request, what should I be looking at changing?

**Comment by eatyourgreens** [comment]
#5010 might fix the task area. There’s a bug with UPP and project roles never resolving to null if you aren’t logged in, which means UPP loading state is never set. I don’t know if that affects tasks.

**Comment by eatyourgreens** [comment]
Project app loading state seems to be working as expected, so I've left this unchanged. I still can't reproduce #5008 on this branch.

**Comment by eatyourgreens** [comment]
I used the wrong screenshot in the PR description. 🤦. I'll fix it. The screenshot is a different bug, where the classifier loads but the subject and workflow aren't shown.

**Review by goplayoutside3 — APPROVED** [review]
I wasn't able to replicate the bug on `master` or this branch deploy, but I think okay to merge.

**Comment by eatyourgreens** [comment]
I think one way to reliably reproduce the bug would be to edit the stored user, in session storage, and change the preferences loading state to something other than ‘success’.

**Pull request merged**
