### PR TITLE
Refactor classifier user authentication

### LINKED ISSUE #4119: Must do sign-out process twice
## Package
app-project?

## Describe the bug

I initially noticed this bug because the FavouritesButton and CollectionsButton are supposed to be enabled or disabled based on whether a user is signed in. Currently if a user is viewing the classify page such as [Poet & Lovers](https://www.zooniverse.org/projects/pmlogan/poets-and-lovers/classify/workflow/21362/subject-set/104809), all four meta tools buttons are enabled. However, if they sign-out the four buttons are still enabled.

Then I realized that refreshing the page after "first" sign-out shows that I'm still signed in to my account. Only after going through the sign-out process a second time and refreshing the page do I know that I'm signed-out for sure.

## To Reproduce

1. Go to [Poets & Lovers](https://www.zooniverse.org/projects/pmlogan/poets-and-lovers/classify/workflow/21362/subject-set/104809) classify page (or any FEM project)
2. Sign in if you're not already.
3. Signed-in UI: All four meta tools buttons are enabled, you can see your stats and recent classifications, your username is in the ZooHeader.
4. Sign out using the ZooHeader.
5. The ZooHeader will show you're signed-out, as does Recent Classifications and Stats. However, MetaTools still shows all four buttons enabled.
6. Refresh the page and everything shows the signed-in UI again.
7. Use the ZooHeader to sign-out again.
8. Refreshing the page will show that you're truly signed out this time.

## Expected behavior

Authentication with ZooHeader menu should work immediately.

### Desktop (please complete the following information):
 - OS: MacOS
 - Browser: Brave Incognito Window or Safari

### PR DESCRIPTION
**Pull request by eatyourgreens**
Refactor the `usePanoptesUser` hook to subscribe to changes in the auth client session, which matches how PFE handles login and logout. Remove SWR for fetching user sessions from the Panoptes Auth API.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
lib-classifier

## Linked Issue and/or Talk Post
- Closes #4119

## How to Review
Sign in and sign out on a project's classify page. Signing in should enable personalisation features in the classifier eg. personalised subject queues, QuickTalk, collections and favourites. Signing out should turn personalisation features off and start an anonymous classification session.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
With the changes here, logging out should trigger a state change in the classifier that sets the logged-in user to null.

**Comment by eatyourgreens** [comment]
I’ve deployed this branch to kubernetes. After very quick testing, I’m seeing #4119 fixed on https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess

**Comment by goplayoutside3** [comment]
Looking good! This refactor solves the issue of needing to sign-out twice in some instances, and it also solves the QuickTalk bug mentioned by Shaun in #4119.

However, when I sign-out after having used the MetaTools to favourite a subject, the disabled meta button still shows "Added to Favorites":
Screenshot 2023-01-21 at 11 46 14 AM

Would you like to look into that bug in this PR to completely close #4119 or rather open an issue specifically for the MetaTools component?

**Comment by eatyourgreens** [comment]
That bug’s not related to this PR. ☹️

If you look in the Subject model, there’s a ‘favourites’ flag that’s set on your personal queued subjects. It shouldn’t be present on subjects that are fetched for an anonymous user, so that bug is in the subject selection code somewhere.

**Comment by eatyourgreens** [comment]
My best guess is that subject selection isn’t running when you log out. 🤔

**Review by goplayoutside3 — APPROVED** [review]
> 
My best guess is that subject selection isn’t running when you log out. 🤔

Ah I see, that makes sense!

**Comment by eatyourgreens** [comment]
I wonder if the code that resets the subject queue, when the logged-in user changes, got removed at some point? Or maybe just stopped working and we didn’t notice.

**Comment by eatyourgreens** [comment]
Definitely worth fixing that in another PR.

**Pull request merged**
