### PR TITLE
WIP Revert client side routing reversion ♽

### PR DESCRIPTION
**Pull request by rogerhutchings**
Reverts zooniverse/front-end-monorepo#1043

The original PR was https://github.com/zooniverse/front-end-monorepo/pull/1038. This fixed client-side routing being broken on the project app, but in production resulted in a 404 on the `_app.js` bundle. 

To the best of my knowledge there's nothing wrong with the code; it was tested locally without problems. My prime suspect is a caching issue, with the rendered HTML pointing to an out-of-date bundle; I'm leaving this as WIP until I can confirm it.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I tested #1038 using `docker-compose up` to run a local dev server. Should I have tested a production build?

**Comment by rogerhutchings** [comment]
I did, and it looked okay to me. Mind casting a second pair of eyes over it to confirm?

**Comment by eatyourgreens** [comment]
No problem.

**Comment by eatyourgreens** [comment]
I've built and started a production server with:
```sh
docker-compose run --rm dev build
docker-compose run --rm --service-ports dev start
```
but http://localhost.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/classify is rendering `an unexpected error has occurred` instead of the classifier.

**Comment by eatyourgreens** [comment]
I can also reproduce that error by running the Next app in node locally.
```
yarn build
yarn start
```
then browse to PH-TESS on locahost.zooniverse.org:3000 and I get a 404 error for the project.

**Comment by eatyourgreens** [comment]
Navigating from About to Classify requests `classify.js` but does not change the window location or the rendered page.

**Comment by eatyourgreens** [comment]
This seems pretty much completely broken to me. How did you run it to get it to work?

**Comment by rogerhutchings** [comment]
`yarn build` / `yarn dev`. Didn't you get it to work too during review?

**Comment by rogerhutchings** [comment]
Also, I'm getting this on master, so something's up

**Comment by eatyourgreens** [comment]
I can run the dev server without problems: `docker-compose up` then browse http://localhost.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/classify?env=production

**Comment by eatyourgreens** [comment]
`yarn build && yarn start` definitely isn't working. 😞

**Comment by rogerhutchings** [comment]
This feels like there's something else going on here, will move this to slack

**Comment by srallen** [comment]
I've just updated this branch with the production docker setup and the classify HTML page is returning a 404. The other network requests are successful.

**Comment by rogerhutchings** [comment]
That's weird, given that it doesn't touch `_app.js`... :/

**Comment by rogerhutchings** [comment]
Sod it. I'll close this, I'll bump the Next.js version to 9 and we won't need dynamic routing anyway 🎉

**Pull request closed without merging**
