### PR TITLE
Classifier: Add support for inactive (private) workflows

### PR DESCRIPTION
**Pull request by eatyourgreens**
- swap `project.links.workflows` for `project.links.active_workflows` when validating workflow IDs in `app-project`.
- add `usePanoptesAuth`, `usePanoptesUser` and  `useProjectRoles` hooks to the classifier.
- move `useStores` into the `hooks` directory.
- check project roles during workflow selection in the classifier. Allow owners, testers and collaborators to select any project workflow. Otherwise, restrict selection to a project's active workflows.

To test this PR, add an inactive workflow to a project, in the project builder, then load that workflow directly by ID in either the dev classifier or the project app. It should load, if you are logged in as a user that has permission to view all project workflows. If not, you should see the usual error in the browser console: `unable to load workflow X for project Y.`

Package:
app-project
lib-classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Here's our previous discussion about [the Panoptes user resource in the classifier](https://github.com/zooniverse/front-end-monorepo/discussions/2362).

**Comment by ErikOstlund** [comment]
Adding myself to the PR because this is related to some work I'm doing with the Solar Jets project and I'd like to be familiar with these updates. I will add a review, but because I'm just walking into this, it may be a good idea to have @shaunanoordin do a review.

**Comment by ErikOstlund** [comment]
Initial UI review:

The goal is to see an inactive workflow in a project.
In project 16201, I have two workflows:
18675 (active)
21160 (inactive)

Without being logged in and going to url:
`localhost:8080/?env=production&project=16201&workflow=21160`
I get the error: `unable to load workflow 21160 for project 16201`
This is expected. So far so good! ✅

Next, I log in and go to the same url:
`localhost:8080/?env=production&project=16201&workflow=21160`
The workflow loads! I can see the subject and the Tasks. I can submit a classification! ✅

Changing the workflow using the UI drop-down, does not update the url. ❌
If I'm at:
`localhost:8080/?env=production&project=16201&workflow=21160`
and use the Change workflow drop-down to select workflow `#18675`, the url is not updating:
Screen Shot 2022-03-28 at 12 03 51 PM

**Comment by ErikOstlund** [comment]
All unit tests are passing. ✅

**Comment by ErikOstlund** [comment]
PR #2993 looks good and is approved. With this update, I believe this PR is good to go. 
@shaunanoordin, do you have time to double check this one?

**Review by ErikOstlund — APPROVED** [review]

**Pull request merged**
