### PR TITLE
Expand WorkflowMenuModal stories

### PR DESCRIPTION
**Pull request by eatyourgreens**
This expands the WorkflowMenuModal stories to include 3 stories:
- Choose A Workflow
- Choose A Subject Set
- Choose A Subject

The API for indexed subjects isn't mocked, yet, for subject selection, so the subject selection data table in the last story shows up as empty.

Component props should all be editable in the 'Controls' panel for each story, so you can change the properties of the passed workflow and subject set.

Package:
app-project

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This might be useful for mocking the subject search API. https://gist.github.com/lkrych/ad537915c69f09ad597767655d2b9211

**Review by srallen — COMMENTED** [review]
I would expect the `ChooseASubject` story would display a list of subjects:

Screen Shot 2021-09-07 at 10 56 33 AM

The mock appears to have subjects defined, so something isn't working here? I'm not sure.

**Comment by eatyourgreens** [comment]
Yeah, the API for the subject index isn't mocked yet, in the browser. The gist I linked to above looks like it might be useful for mocking `window.fetch` but I haven't had time to look into it further.

**Review by srallen — APPROVED** [review]
Oops, the opening already said that. Thanks. I would be very wary of mocking `window.fetch` even just for a story. Is there an alternative? Can the component be written such that it doesn't fire off fetch and data can be loaded by prop or another mechanism if defined?

**Comment by eatyourgreens** [comment]
Yeah, it can probably be rewritten to take the table data from a prop. It is bugging me that neither this story nor the subject picker story have mock subjects at the moment.

**Pull request merged**
