### PR TITLE
Migrate storybooks from `storiesOf` to `CSF`

### PR DESCRIPTION
**Pull request by eatyourgreens**
- [x] Migrate existing stories with `npx sb migrate storiesof-to-csf --glob="**/*.stories.js"`
- [x] Tidy up remaining stories by hand.

## Package
app-project
lib-classifier
lib-react-components

The best way to test this is probably to start the storybooks, with `yarn storybook`, and compare against the published storybooks at https://zooniverse.github.io/front-end-monorepo

### CODE REVIEW

**Review by mcbouslog — APPROVED** [review]
This LGTM! This is great.

Noting we can remove the `storiesOf` and maybe some add-on imports in:
- lib-classifier
    - DataImageViewer
    - ScatterPlotViewer
    - VariableStarViewer
- lib-react-components
    - ZooHeader

I noticed sometimes in the Docs heading tab, the Show code button on stories doesn't work in app-project, but there's the Story tab at the bottom anyway so doesn't matter, might not even be related.

not related to this PR, but there's not a video in the SingleVideoViewer story, not sure if that's something @ErikOstlund can add though it's not a high priority.

**Comment by eatyourgreens** [comment]
Here’s an example where the docs page says ‘No code available’ on the live storybook. 
https://zooniverse.github.io/front-end-monorepo/@zooniverse/fe-project/index.html?path=/docs/project-app-screens-project-home-recent-subjects--carousel-view

I’m not sure what’s happening there, but the docs page should replace the story-source addon long term.

**Comment by eatyourgreens** [comment]
Knobs need to be replaced by controls, in those stories that use them. 
https://github.com/zooniverse/front-end-monorepo/issues/2370

Controls can be automatically generated for component props, so hopefully that won’t be a lot of work.

**Comment by eatyourgreens** [comment]
If we want to take advantage of generated controls and docs in our stories, then we should move away from classes and write new components as functions with destructured default arguments.

**Pull request merged**
