### PR TITLE
Fix grommet theme bundling

### PR DESCRIPTION
**Pull request by rogerhutchings**
Remove Neutrino for straight webpack, and ensure module is bundled properly

### CODE REVIEW

**Comment by rogerhutchings** [comment]
NEGATIVE DIFF ➖

**Comment by rogerhutchings** [comment]
I removed Neutrino for the classifier library, as I couldn't work out how to modify the Neutrino config to run a app-based project in development and generate a library for distribution. I felt it was probably best to keep our build tools consistent.

We'll still need a tool to bundle and uglify the project for distribution...

**Comment by srallen** [comment]
@rogerhutchings I'm for keeping tools consistent, I just am unsure if it's really needed here since all this is is just a object of constants being exported. No new javascript features are being used. This isn't a blocker for me, though.

**Comment by rogerhutchings** [comment]
Okay - I'll merge for now, but I'm totally happy to remove any unneeded tooling a bit further down the line.

**Pull request merged**
