### PR TITLE
Classifier - TESS Light Curve Viewer - Feedback Response (29 Jan Demo)

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview
package: lib-classifier
Requires / targets #394

This PR is addresses feedback from the live demo given to the science team on 29 Jan. 

- Colours have been changed to be consistent with the current [Planet Hunters project.](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify)

screen shot 2019-01-29 at 12 58 32
_Newly updated TESS Light Curve Viewer_

screen shot 2019-01-29 at 13 00 11
_Current Planet Hunters project_

### Status
Safe to review, but further tweaks are ongoing to clean up the code.

PR target chain: #394 -> #385 -> `master`

### CODE REVIEW

**Comment by srallen** [comment]
@shaunanoordin before you get too far in changing colors, please check with @beckyrother. I'm not sure if it is a good idea to use Planet Hunter's colors since that was from a specific look/design that may not work with current classifier design, particularly considering the light and dark themes.

**Comment by shaunanoordin** [comment]
The colour change was requested by Chris, Suzanne, and Nora during today's demo. The rationale is as follows:

1. the science team found it more difficult to see the light curve data (the points blended together at glance?) with the teal-on-white colours.
2. the science team wants to maintain the white-on-navy colours, so volunteers will have an easier time transitioning into this next phase of Planet Hunters.

**Comment by shaunanoordin** [comment]
DANGIT! Forgot one more. This wasn't part of the formal rationale from the science team, but still worth noting:

3. related to point 2, each Light Curve Subject will contain a JSON (displayed in the LightCurveViewer) and a generated static PNG (used in Talk) - it would make more sense for these to look similar to one another.

Side note: I have an update lined up to make the setting colours easier by passing style settings to the the LightCurveViewer, i.e. `<LightCurveViewer chartStyle={{ color: teal, background: white }}>`, which may come handy should we eventually revise the style. (Or implement light/dark theme switching, or Invert Colours, into the LCV)

**Comment by shaunanoordin** [comment]
One more thing:

- One point of feedback that was **not** addressed today is the ability to have a **Zoom in the Y-axis.**
  - For the launch of the LCV + Planet Hunters, we will only have X-zoom, as is the current implementation.
  - As we discussed, the X-zoom makes more sense since it gives proper context for comparing data points (i.e. we want to see all brightness-points in a given time period)
  - A standard (X and Y) zoom makes less sense, as it clips too much data out from the zoomed view window. (i.e. by zooming into a given time period, we'd also exclude brightness points that are too high/too low from our current view)
  - A Y-zoom only becomes necessary if a Light Curve has very odd outliers in its brightness - e.g. 99% of the graph averages at -5 to 5 brightness, but one brightness-point sits at a staggering +1000, causing the rest of the light curve graph to "clump" to the bottom of the chart, making comparisons difficult.

There IS a solution IF we find out that Y-zoom is necessary: build custom Y-zoom buttons (i.e. a **separate Y-zoom controller** - separate from the mouse wheel scroll, and separate from the standard zoom used by the Classifier) into the LCV component.

This means the mouse wheel and the Classifier zoom in/out buttons control the X-zoom as it currently stands, and the Y-zoom can be controlled separately. _Notable things to look out for: resizing the brushes(?) on Y-zoom change, storing the separate Y-zoom (in the store? locally on the component?), separating the custom Y-zoom from the built-in D3-zoom data_

We currently have no dev plans to pursue this solution, but will come back to it if the new data from TESS requires a Y-zoom.

**Comment by beckyrother** [comment]
Thanks for tagging me @srallen. @shaunanoordin I understand the rationale, but I wonder if there's some middle ground closer to the Zooniverse brand. Are there other colors [here](https://projects.invisionapp.com/dsm/zooniverse/primary-brand/folder/colors/5bbd0dbcd018e900118186e8) that might work?
My worry is that other project owners will see custom colors in the project builder and ask for custom CSS for their projects, which in general we don't encourage.

**Comment by chrislintott** [comment]
Can we see what dark teal looks like? Alternatively I think white points on a zooniverse colour background might work, @beckyrother?

**Comment by beckyrother** [comment]
Dark teal with either white or light gold would be nice. The more contrast the better, keeping colorblind users in mind.

**Comment by srallen** [comment]
@shaunanoordin I like the idea of having props for configuring styling so the viewer is usable in a CFE with a different design. Is the idea that this object gets passed to a style prop? I would rather have specific props for specific configurable styles and encourage devs to also use styled-components for customization rather than pass in a style object.

**Comment by srallen** [comment]
@shaunanoordin about the y-axis zoom, perhaps this could be an enhancement for a generalized scatter plot viewer (based on this initial LCV). Could you open an issue with this request and details?

**Comment by shaunanoordin** [comment]
@srallen 

**y-axis zoom:** 👍 https://github.com/zooniverse/front-end-monorepo/issues/401

**style object:** at the moment, I've set up the Light Curve Viewer to accept specific styles like so:

```
var customStyle = {
  color: (isDarkTheme) ? '#fff' : '#000',
  background: (isDarkTheme) ? '#000' : '#fff',
  fontFamily: 'inherit',
  fontSize: '0.75rem'
}

render () {
  <LightCurveViewer chartStyle={customStyle}>
}
```

This small object works fine in the context of the Light Curve Viewer (even then, I'm honestly thinking of removing the fontFamily and fontSize options) but when we move into the general ScatterPlotViewer, the number of possible values that we might need to cram into the style object can get bonkers - colorOfActiveBrush, colorOfInactiveBrush, labelFont, dataPointFont, selectedDataPointFont, etc etc ad infinitum 🤔 

> I would rather have specific props for specific configurable styles and encourage devs to also use styled-components for customization rather than pass in a style object.

Do you mean you prefer this?

`<LightCurveViewer color='#fff' background='#000' fontFamily='inherit' fontSize='0.75rem'>`

If so, can do.

Why I'm using a style object: the custom styles are passed around a lot between the various functions in the `LightCurveViewer/d3` folder, and it was simpler for me to write code for  `d3/addAnnotationLayer(props.style)` vs `d3/addAnnotationLayer(props.color, props.background, props.fontFamily, props.fontSize)` esp. when the styles I needed to pass around _kept changing in development._

That said: now that the LCV is less in a state of development flux, passing around the style object vs passing individual style values isn't as much of a problem, and might be worth it if it's easier for other devs to read. It'll still be a _bit faffy_ since some of those /d3 functions will require 10+ arguments, mind you.

Side note: I haven't explored using `styled-components` in the context of the D3 charts, so I can't weigh in on that yet - at least in the context of the LCV. Give me an idea of what you'd like to do for the general ScatterPlotViewer and I'll experiment.

**Comment by shaunanoordin** [comment]
@beckyrother @chrislintott @noraeisner

--------

Current style - **"Nora Classic"**
screen shot 2019-01-29 at 17 42 05

--------

**"White on Teal"**
screen shot 2019-01-29 at 17 45 26

--------

**"Teal on White"**
screen shot 2019-01-29 at 17 44 53

--------

**"Golden Combo"**
screen shot 2019-01-29 at 17 41 09

--------

**"Stars at Night"**
screen shot 2019-01-29 at 17 42 41

--------

**"Retro"**
screen shot 2019-01-29 at 17 53 12

--------

**"Evil Tomato"**
screen shot 2019-01-29 at 18 00 47

--------

I can do this all day.

**Comment by beckyrother** [comment]
Evil tomato, no question!

Thanks for putting all these together Shaun, this is really helpful. I actually prefer the white/teal combos. Will switching to dark mode change the graph as well?

**Comment by rogerhutchings** [comment]
I'd also suggest using a separate colour for the axis / tick labels to differentiate them from the points.

**Comment by srallen** [comment]
@shaunanoordin thanks for the explanation of how the style prop is being used. I still have a bit of a disconnect in my head about the LCV and think of it as a react component rather than a d3 component wrapped by react, so how you propose to handle this makes sense for d3. I think configurable props for the specific styles for the various elements (i.e. something like `point: { color: pointColor, size: pointSize }`, `axis: { color: axisColor, size: fontSize }`, `background: { color: backgroundColor, ...otherConfigs }`) could be made more specific at the refactor stage of this and a single style prop would work for now.

**Comment by rogerhutchings** [comment]
@shaunanoordin is there anything outstanding on this PR, or is it okay to merge?

**Comment by shaunanoordin** [comment]
I still need to fix the colours as Becky requested - **white on teal**. Just gimme a second!

Note: for the following items, I'll need to open an issue for later revision:
- allow TESS LCV to have a dark mode (future, not in current milestone)
- add option for configuring axis/labels styles
- revise the style props passed to the LCV (should organise by elements, as Sarah suggested)

**Comment by shaunanoordin** [comment]
👍 The styles have been updated to use White-on-Teal.

I'm going to go ahead and merge this to `tess-lcv-2-button-remove` (#394), then figure out the merge conflicts on `tess-lcv-1-brush` (#385)

As always, thank you everyone for the feedback!

**Pull request merged**
