### PR TITLE
Remove --exit from classifier tests

### PR DESCRIPTION
**Pull request by eatyourgreens**
## Package
lib-classifier

## How to Review
Run the classifier tests.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Tests just hang without that flag. I'm not sure why.

**Comment by eatyourgreens** [comment]
Classifier tests aren’t properly cleaning up after themselves. 
https://stackoverflow.com/questions/50372866/mocha-not-exiting-after-test

#4145 should ensure that we don’t have any dangling API requests (or Caesar requests either.)

**Comment by eatyourgreens** [comment]
@mcbouslog the project app tests are fetching unread conversations in several places. This is from the logs for this PR. 

Mocha test logs showing a blocked request to the Talk API.

**Comment by goplayoutside3** [comment]
@eatyourgreens @mcbouslog is this PR still needed?

**Comment by eatyourgreens** [comment]
I think this can be closed. There’s still an issue where the project app tests are fetching unread messages in several places.

**Pull request closed without merging**
