### PR TITLE
refactor(classifier): survey task Choice model

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add a Choice model to the survey task. Model choices as a Map of Choice types, mapped by choice ID. Update the tests where they were testing a task snapshot rather than a task model.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier/plugins/tasks/survey

## Linked Issue and/or Talk Post
- #6085
- #6086

Similar to #6086, this refactors `task.choices` to use `types.map(Choice)` , rather than `types.frozen({})`.

## How to Review
I used the storybook to test the changes here. Snapshot Wisconsin (project slug `zooniverse/snapshot-wisconsin`) is also useful for checking if a survey task works.

https://localhost:8080/?project=zooniverse/snapshot-wisconsin&env=production

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook.

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [x] The refactored component(s) continue to work as expected

### CODE REVIEW

**Review by goplayoutside3 — COMMENTED** [review]
When running this branch app-project locally, I see a few console errors for a survey task like Squirrel Mapper: `Warning: Failed prop type: Invalid prop "choices.enhancer_" of type function supplied to ConfusedWith, expected object.` Same warning for `confusion.confusions.enhancer_` and `confusions.enhancer_`. Related to chanages made here? Could this PR fix those warnings if not?

**Comment by eatyourgreens** [comment]
`characteristics` generate the same warning too, now that they're a Map.

**Comment by eatyourgreens** [comment]
Both MobX and React now expect you to use TypeScript for type checking, so there isn't a React PropType for ES6 Maps. MobX exports a legacy `PropTypes`, which includes `observableMap`, so I've switched the prop type definitions over to use that.

>PropTypes aren’t commonly used in modern React. Use TypeScript for static type checking.

https://legacy.reactjs.org/docs/typechecking-with-proptypes.html

**Review by mcbouslog — APPROVED** [review]
Thank you for the refactor! Changes look good, storybook and local workflow with survey task continue to work as expected 👍

**Pull request merged**
