### PR TITLE
Wait before refreshing the subject queue

### LINKED ISSUE #4847: On sign in, classifier fetches subjects before the user is signed in
## Package
lib-classifier

## Describe the bug
After signing in on the Classify page, the subject queue is refreshed but the new subjects are fetched before the new user is signed in. The subjects request has an empty Authorization header.

The browser console for Gravity Spy during user sign-in. The new subject is fetched before the Panoptes bearer token has been received from the API.
## To Reproduce
1. Go to the Classify page for a project.
2. Sign out (if already signed in.)
3. Sign in.
4. Examine the console log to see that the first subject loads before the new user is signed in.

## Expected behavior
The subject queue should refresh after the new user has signed in (#4838.)

### PR DESCRIPTION
**Pull request by eatyourgreens**
Wait for sign-in to complete before refreshing the subject queue, when the auth'ed user changes.

Screenshot of the dev console for Gravity Spy, after a new sign-in, showing that the first new subject loads after the new user is signed in.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
lib-classifier

## Linked Issue and/or Talk Post
- closes #4847.

## How to Review
Load the Classify page while signed out, then sign in. The first request for queued subjects should be made with your Authorization header.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Weirdness I discovered in the Panoptes JS Client:
- `auth.signIn()` fires a `change` event before resolving the user promise, leading to #4847.
- `auth.signOut()` resolves the user promise after signing out, then fires a `change` event, which is the behaviour I was expecting from the client.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: `lib-classifier`

This PR fixes an issue where, when a user logs in, the Subject queue is fetched _but as if the user was anonymous._

- What we actually wanted: 1. when the subject queue is fetched (i.e. Panoptes's /queued endpoint is hit), it should contain the Authorization info in its headers, indicating the _current user._ 2. when a user logs in (i.e. state of the "current user" changes), the Subject queue should be re-fetched. 2a. ditto when the user logs out.
- The problem: the `authClient`'s "change" event doesn't necessarily trigger when the "current user" change action _completes,_ but rather... when it _starts?_ 🤨 Hence, the "fetch subjects" action is triggering too early, and Subjects are requested as the _previous user._ 
- The solution: when the "user change" event triggers, _wait for the "current user" change event to actually complete_ before triggering a subject queue fetch.

Code changes are really straightforward. Testing was much more involved, but everything looks good 👍 

### Testing

Tested with macOS + Chrome, using `app-project`, on the Classify page of a random test workflow.

populateQueue() and _onUserChange() have also been tagged with additional console.log() debug info, to observe when each function triggers. This is done in conjunction with monitoring requests on the Network tab.

Testing steps and **results, before PR fix:**

- Open new Incognito window
- Open Classify page as anonymous
  - populateQueue() called. (/queued endpoint hit, no Authorization in header ✔️ )
- Login as any user (e.g. darkeshard)
  - onUserChange() called, then populateQueue(). (/queued endpoint hit, NO AUTHORIZATION HEADER ❌ )
- Logout
  - onUserChange() called, then populateQueue() TWICE. ❔ (/queued endpoint hit 2x, no Authorization in header ✔️ )

- Prepare for next run.
- Login as any user (e.g. darkeshard)
- Close tab and open a new one within same Incognito session (i.e. stay logged in, thanks)

- Open Classify page as any user (e.g. darkeshard)
  - populateQueue() called TWICE. ❔ (/queued endpoint hit 2x with Authorization in header ✔️ )
- Logout
  - onUserChange() called, then populateQueue() TWICE. ❔ (/queued endpoint hit 2x, no Authorization in header ✔️ )

Testing steps and **results, after PR fix:**

- Open new Incognito window
- Open Classify page as anonymous
  - populateQueue() called. (/queued endpoint hit, no Authorization in header ✔️ )
- Login as any user (e.g. darkeshard)
  - onUserChange() called, then populateQueue(). (/queued endpoint hit with Authorization in header ✅ )
- Logout
  - onUserChange() called, then populateQueue() TWICE. (/queued endpoint hit 2x, no Authorization in header ✔️ )

- Prepare for next run.
- Login as any user (e.g. darkeshard)
- Close tab and open a new one within same Incognito session (i.e. stay logged in, thanks)

- Open Classify page as any user (e.g. darkeshard)
  - populateQueue() called TWICE. ❔ (/queued endpoint hit 2x with Authorization in header ✔️ )
- Logout
  - onUserChange() called, then populateQueue() TWICE. ❔ (/queued endpoint hit 2x, no Authorization in header ✔️ )

**Observations:**

(1) We can see a major improvement when a user logs in on the Classify page - the Subject queue is now correctly fetched with the appropriate auth headers.

Prior to this, we can imagine User X going to Classify, logging in, then being incorrectly served 10 Subjects an _anonymous user,_ then after 10 classifications is served 10 Subjects _for User X..._ which might result in duplicate Subjects, because Panoptes didn't realise both batches of 10 Subjects were headed to the same person.

(2) We'll also note that if a user is already logged in when they visit the Classify page, then the auth headers are always sent correctly.

(3) Not sure what's the deal with the populateQueue() being called twice, though. I'm not sure if using a small WF with only 6 Subjects could have contributed to wonkiness, but in any case, it's extant prior to this fix and has no bearing on the auth headers, so it's likely a separate quirk.

### Status

LGTM 👍

**Comment by eatyourgreens** [comment]
The auth client uses a singleton pattern, so the static import imports the same object, each time that it runs. That means that the listener in the classifier is listening for `change` events fired by both the classifier and also the Classify page. That might explain the event being fired twice. 🤔

```js
import authClient from 'panoptes-client/lib/auth'
```

**Comment by eatyourgreens** [comment]
#4803 might fix those double fetches, by removing unnecessary calls to `auth.checkCurrent()`. It might be worth running the same tests on that branch to see if that bug still exists. 

As you say, it’s not a big deal on randomised queues, but I’m wondering how this plays out on ordered queues.

**Comment by eatyourgreens** [comment]
One question @shaunanoordin: is the double fetching bug extant on the `production-release` tag?

**Pull request merged**
