### PR TITLE
Upgrade app-content-pages to NextJS 13

### PR DESCRIPTION
**Pull request by eatyourgreens**
Bump the content pages app to NextJS 13. Turn off hoisting for Storybook or Next.js packages, so that each app has its own `node_modules` directory (one for Next.js 12 and one for Next.js 13.)

- Includes #3887.

The project app should build and deploy with NextJS 12/React 18.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
app-content-pages
app-project

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
- What user actions should my reviewer step through to review this PR?
- Which storybook stories should be reviewed?
- Are there plans for follow up PR’s to further fix this bug or develop this feature?

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Maintenance
- [x] If not from dependabot, the PR creator has described the update (major, minor, or patch version, changelog)

### CODE REVIEW

**Comment by eatyourgreens** [comment]
`app-project` storybook builds are broken because they can't resolve `next/future/image`, which is included with Next 12 but not with Next 13.

**Comment by eatyourgreens** [comment]
Client-side navigation links are broken wherever we've wrapped a Grommet Button or Anchor in `<Link href={uri} passHref>`. Setting the [`legacyBehavior`](https://nextjs.org/docs/pages/api-reference/components/link#legacybehavior) flag fixes all the broken navigation links but I'm not sure how useful that is long-term.

This will be a much bigger problem in the project app.

**Comment by eatyourgreens** [comment]
Other than [`passHref`](https://nextjs.org/docs/pages/api-reference/components/link#passhref) not seeming to work like it did before, I'm not seeing any problems with the Team page or Publications page in Next 13.

**Comment by eatyourgreens** [comment]
I spoke too soon. 'Sign In' appears to be broken.

**Comment by eatyourgreens** [comment]
[Panoptes Client 5.5.6](https://github.com/zooniverse/panoptes-javascript-client/releases/tag/v5.5.6) should fix sign in here.

**Comment by eatyourgreens** [comment]
Sign in and out is fixed now, so this is ready for review.

https://github.com/zooniverse/front-end-monorepo/assets/59547/c2544e09-3edb-4435-8a5c-83a58058e379

**Review by goplayoutside3 — APPROVED** [review]
Looks good! I ran both app-project and app-content-pages, as well as their storybooks.

Just to follow-up on the `next/link` changes you mentioned at standup - I think using the legacy flag for now is totally fine. It is probably worth documenting a future refactor in either an Issue or in the FEM structure discussion: https://github.com/zooniverse/front-end-monorepo/discussions/5089

**Pull request merged**
