### PR TITLE
Update newrelic to version 7 in preparation of node 14 update

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: app-project, app-content-pages

Describe your changes:

The newrelic package has to be updated to version 7 to support node 14. I'm not sure how to test this other than check that the docker containers build, which they do for me.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by eatyourgreens — APPROVED** [review]
CI builds are working. Looks good to me.

**Comment by eatyourgreens** [comment]
`app-content-pages` doesn't seem to be using `newrelic`, so maybe that can be removed?

**Comment by srallen** [comment]
@eatyourgreens not sure what you mean. [I see it it on new relic.](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMub3ZlcnZpZXciLCJpc092ZXJ2aWV3Ijp0cnVlLCJyZWZlcnJlcnMiOnsibGF1bmNoZXJJZCI6Im5yMS1jb3JlLmV4cGxvcmVyIiwibmVyZGxldElkIjoibnIxLWNvcmUubGlzdGluZyJ9LCJlbnRpdHlJZCI6Ik1qTTJNVGw4UVZCTmZFRlFVRXhKUTBGVVNVOU9mRE14T1RBek56YzVPUSJ9&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNak0yTVRsOFFWQk5mRUZRVUV4SlEwRlVTVTlPZkRNeE9UQXpOemM1T1EiLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoiYXBtLW5lcmRsZXRzLm92ZXJ2aWV3IiwiaXNPdmVydmlldyI6dHJ1ZX19&platform[accountId]=23619&platform[timeRange][duration]=1800000&platform[$isFallbackTimeRange]=true)

**Comment by eatyourgreens** [comment]
How weird. It's not used in the content pages server code or Next config, only in the project app. https://github.com/zooniverse/front-end-monorepo/search?q=newrelic
There's a `newrelic.js` config file in the `app-content-pages` package, but the newrelic client itself is never loaded.

**Comment by eatyourgreens** [comment]
Those search results completely missed out the content pages server config. 😳 
https://github.com/zooniverse/front-end-monorepo/blob/ce85b5e0c168acc327efb5c5f4a6cfe0c589ee9b/packages/app-content-pages/server/server.js#L1-L3

**Pull request merged**
