### PR TITLE
When transcription task, use the hard coded colors for transcription line

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

This finishes the refactor on the `TranscriptionLine` mark to make it fully flexible between its usability with the drawing task and the transcription task.

- [x] We need to confirm with @beckyrother which colors should be used for the state. Should we use ASM's colors? Drawing tool colors which they're mostly set to now? A different set of colors? Regardless whichever are used will be moved to the theme and this refactored to use the theme.
- [x] Need to finish updating the tests to test for which colors are applied depending on if the task is transcription or drawing

Right now this can be previewed at http://local.zooniverse.org:8080/?project=1764&workflow=3392 or using the storybook's `TranscribedLines` story which can preview all four state colors in the now interactive story using a transcription task. Alternatively, the transcription line color can be previewed in the `TranscriptionLine` story where it is using the drawing task and the task is set to use the drawing-orange color to make it obvious its the drawing task. Here are some screenshots:

Transcription Task, ASM staging, with lines with the default, active, transcribed, and complete states:
Screen Shot 2020-05-14 at 5 13 17 PM

Transcription Task, ASM staging, all four state colors, but the active one has the subtask open:
Screen Shot 2020-05-14 at 5 13 26 PM

Transcription Line in the Drawing Task story:
Screen Shot 2020-05-14 at 5 13 34 PM

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
@beckyrother here's how those colors look with an ASM subject in context:

Screen Shot 2020-05-15 at 3 35 34 PM

**Comment by beckyrother** [comment]
Thank you @srallen! That yellow is a challenge to see, can we change to #FF40FF (pink)? Sorry for the back and forth.

**Comment by srallen** [comment]
@beckyrother here's what this looks like:

Screen Shot 2020-05-19 at 1 35 33 PM

**Comment by beckyrother** [comment]
Looks great! Good to go on my end.

**Comment by srallen** [comment]
@wgranger could you review this? Thanks!

**Pull request merged**
