### PR TITLE
Add app-content-pages notifications

### LINKED ISSUE #1093: Zoo header: notifications aren't shown
**Package**
lib-react-components (I think)

**Feature or Issue Description**
I have one unread notification at the moment. When I go to the content-pages app or to the PH TESS classify page, that notification is not shown at the top of the page.

Zooniverse projects page showing one unread notification at the top of the page.

Zooniverse publications page showing no new notifications at the top of the page.

### LINKED ISSUE #3692: Add Notifications and Messages unread functionality to app-content-pages header
## Package
- app-content-pages (iteration on #2459)

## Is your feature request related to a problem? Please describe.
Notifications and Messages in the content pages site header should be wired up to a sugar notification channel so that users can be aware when someone has messaged.

## Describe the solution you'd like
Implement [user personalization for notifications in app-project](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.js) in app-content-pages.
Similar to #3396.

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- app-content-pages 

## Linked Issue and/or Talk Post
- closes #1093 
- closes #3692 

## Describe your changes
- moves User store
- adds UserPersonalization store
- adds Notifications store

Note
- duplicative to app-project related code, I'm thinking I should at minimum open a GitHub issue or discussion if or how this duplicative code could be consolidated
- mirrors app-project stores, with UserPersonalization store, but I don't think any other user personalization will be needed in app-content-pages, so I'm not sure if better to simplify or keep consistent

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
  - https://local.zooniverse.org:3000/about/team?env=production
- What user actions should my reviewer step through to review this PR?
  - if you don't have unread notifications or messages, let me know and I can send you a message
- Which storybook stories should be reviewed? n/a
- Are there plans for follow up PR’s to further fix this bug or develop this feature? update app-project Notifications and Notifications.spec similarly

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## New Feature
- [x] The PR creator has listed user actions to use when testing the new feature
- [ ] Unit tests are included for the new feature

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Discovered while I was testing out the main branch today: there's no local HTTPS server for production builds of `app-content-pages`, so you can't log in with a local production build.

**Comment by eatyourgreens** [comment]
Also, you don't really need to duplicate the server in a `dev-server` script. Add an if block to server.js that returns `https.createServer(options, server).listen()` for local development or `server.listen()` otherwise.

**Comment by mcbouslog** [comment]
This branch no longer includes the pre-squashed commits from #4004 , now reflects commits and code changes only related to refactoring the user store and adding notifications for app-content-pages.

**Comment by goplayoutside3** [comment]
While reviewing this PR, I noticed there's a bug on master related to dev environment auth. With this branch or master I did the following steps:
- I followed the link to [https://local.zooniverse.org:3000/about/team?env=production](https://local.zooniverse.org:3000/about/team?env=production)
- I'm initially signed-out
- I click "Sign In" in ZooHeader, but the browser throws an error `TypeError: Cannot read properties of null (reading 'getRootNode')`
- I can't sign-in to review this notifications-related PR

Just wanted to check here if that error is unique to my local machine before creating an issue, and @mcbouslog if you think we should look into https://github.com/zooniverse/front-end-monorepo/pull/4108 first?

**Comment by eatyourgreens** [comment]
Here’s the Sentry log for that error, with a stack trace. 
https://sentry.io/organizations/zooniverse-27/issues/3873888799/?project=1492498&query=is%3Aunresolved&referrer=issue-stream

**Comment by eatyourgreens** [comment]
This seems to be the same error, but on staging. 
https://sentry.io/organizations/zooniverse-27/issues/3874880055/?project=1492498&query=is%3Aunresolved&referrer=issue-stream

**Comment by eatyourgreens** [comment]
I’m not seeing that error in Sentry when I log in to the project app on staging.

**Comment by mcbouslog** [comment]
@goplayoutside3 - I also see the error you note when logging in on https://local.zooniverse.org:3000/about/team?env=production. I'll plan to take a look at #4108 asap (tomorrow?) unless someone beats me to it or there's a different preference.

**Comment by goplayoutside3** [comment]
I just encountered the same error when I clicked "Sign In" on https://github.com/zooniverse/front-end-monorepo/pull/4064's branch. Maybe the error is not isolated to app-content-pages, but instead could be caused by adding devcert to an additional app on our local machines when it was already setup for app-project.

**Review by goplayoutside3 — APPROVED** [review]
Looks good! I'm able to see correct notification numbers in the ZooHeader when logged in on app-content-pages.

**Comment by eatyourgreens** [comment]
Here’s that error on a staging project. 
https://sentry.io/organizations/zooniverse-27/issues/3870114865/?project=1492691&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d

#4121 includes fixes for Grommet form fields. Since the error is thrown by `onFocus`, I would guess that it’s caused by autofocus on the username/email input.

**Pull request merged**
