### PR TITLE
app-project: Use shared AuthModal component

### PR DESCRIPTION
**Pull request by goplayoutside3**
## Package
app-project
lib-react-components

## Linked Issue and/or Talk Post
Similar to https://github.com/zooniverse/front-end-monorepo/pull/5657
Toward: https://github.com/zooniverse/front-end-monorepo/issues/5364

Closes: https://github.com/zooniverse/front-end-monorepo/issues/5646
Closes: https://github.com/zooniverse/front-end-monorepo/issues/5631

## Describe your changes

- Delete AuthModal component from app-project, and its translation keys
- Import AuthModal from lib-react-components instead
- Convert ZooHeaderWrapper into PageHeader for consistency with app-root and app-content-pages. The main different between app-project and the other two apps is that the user resources is in a mobx store as opposed to simple React context.
- Added `onSignIn()` to AuthModal to handle updating the mobx store in app-project when a user signs in or out.
- In several components I renamed `isAdmin` to `adminMode`. This prop is a boolean and is true only when admin mode is enabled. I think `adminMode` communicates that concept better than `isAdmin` because a signed-in user can be an admin, yet not have admin mode enabled via the footer toggle
- Added a translation key for the `<header>` aria-label

## How to Review

Run app-project locally and visit project pages while signed-in and signed-out. I tested the Register modal manually by creating a new account.

Note that I removed the url params for sign-in/register. See comment here: https://github.com/zooniverse/front-end-monorepo/pull/5657#issuecomment-1831785380

Also note that you might see https://github.com/zooniverse/front-end-monorepo/issues/5748 while testing sign-out on the classify page. That bug has been around for several months, but I recently documented it more thoroughly and it's unrelated to AuthModal.

⚠️  I will manually move the AuthModal translation keys between projects in Lokalise post-merge!

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [x] The refactored component(s) continue to work as expected

## Post-merge
- [ ] This PR adds translations keys to English dictionary(s). See guidance for pulling new keys to Lokalise [here](https://github.com/zooniverse/how-to-zooniverse/blob/master/Translations/lokalise.md#lokalise-and-fem).

### CODE REVIEW

**Review by mcbouslog — APPROVED** [review]
Changes to lib-react-components largely related to adding `onSignIn` callback and renaming `isAdmin` to `adminMode` ✅ 

Optionally to this PR -> note changes in an Unreleased section in lib-react-components CHANGELOG.

Changes to app-project include removing AuthModal and related components and translations ✅ . Replacing with PageHeader and lib-react-components AuthModal and ZooHeader ✅ . As noted these changes remove `?login=true` and `?register=true` query params as intended.

I tested locally, signing in and out, accessing Sign In and Register modals - works as expected 👍 .

**Comment by mcbouslog** [comment]
Other than seeing the black and yellow page border, is there something I can try accessing to confirm `adminMode` is working? I can't think of anything.

**Comment by goplayoutside3** [comment]
> note changes in an Unreleased section in lib-react-components CHANGELOG.

Good catch! I'll do this before merging.

> Other than seeing the black and yellow page border, is there something I can try accessing to confirm adminMode is working?

The admin page link should appear in ZooHeader and a link to a project's admin page appears in ProjectHeader. I did a double check of both just now, and it's working as expected 👍

**Comment by goplayoutside3** [comment]
For some reason the Admin link in ZooHeader doesn't appear when I toggle `adminMode` to true on production after deploying this PR, such as https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess. Yet, I can't reproduce that bug by running locally either in dev mode or production mode 🤔 The link to a project's admin page in ProjectHeader works just fine... will have to think about why that might be

**Pull request merged**
