### PR TITLE
Add page_size to subject set queries

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add `page_size` to subject set queries, and set it to the number of linked set IDs for a workflow.

This should allow us to show more than 20 linked sets for a workflow. The query runs on every request for grouped workflow page props, so be careful about making these queries too big/slow.

This workflow lists 20 subject sets on master, but should show 40 on this branch.
https://www.zooniverse.org/projects/bogden/scarlets-and-blues/classify/workflow/18504

Package:
app-project

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by zwolf — APPROVED** [review]
What does this page look like with over twice as many entries in the modal? Ultimately this should be paginated, since this doesn't put a cap on the value and will load in a single request however many exist for that workflow. This may cause unexpected behavior later.

From Panoptes point of view, this is fine for now. The page_size parameter is capped at 200 on production, and while I wouldn't recommend going anywhere near that for practical purposes, below 50 shouldn't be a problem--with the caveat that this doesn't apply any restriction or pagination and if that max is approached, and if this value climbs, a different scheme will be required.

**Comment by shaunanoordin** [comment]
Code read looks very good, of course. Just give me a second while I bootstrap and test this out!

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: `app-project`
Project: Engaging Crowds

This PR enhances the "Subject Set selection" menu, which appears on workflows with selectable subject set.

- New behaviour: the number of selectable Subject Sets shown on the menu is no longer limited to the Panoptes-default of 20 items.

### Testing

Tested on localhost with macOS + Chrome

Test URL: https://local.zooniverse.org:3000/projects/bogden/scarlets-and-blues/classify/workflow/18504?env=production

- On the `master` branch, the Subject Set selection menu for Scarlets & Blues shows **20 items**
- On this branch, the menu shows **46 items**, which if I'm reading the (ever-changing) project settings correctly, is pretty much _all_ Subject Sets currently associated with this workflow.

### Status

LGTM. 👍  Also, Zach already made very pertinent points about _"let's not let project owners add too many darn active Subject Sets to a workflow",_ so I second what he said.

Also, @zwolf , if you're curious:
> Q: What does this page look like with over twice as many entries in the modal? 
> A: With the current UI implementation, there's an overflow scroll.

image

**Comment by eatyourgreens** [comment]
Let's see how this goes on staging. Listing all sets for a workflow makes me nervous too.

**Comment by eatyourgreens** [comment]
I discovered that there’s a page size of 250 workflow subject sets coded into the project builder and now I don’t feel so bad about writing this PR. 

https://github.com/zooniverse/Panoptes-Front-End/blob/2c8bc7071db2635a70d005cb73c63b649632915c/app/pages/lab/workflow.cjsx#L572

**Comment by zwolf** [comment]
Perhaps that should be more of a warning than a lesson

02614231-34EB-4299-B70C-0EC75EA8981E


https://github.com/zooniverse/Panoptes-Front-End/pull/3546#pullrequestreview-25491991

**Comment by eatyourgreens** [comment]
Yep.

**Comment by eatyourgreens** [comment]
From that same PR, this was written 4.5 years ago (March 2017):
>it's estimated a page_size of 250 will give enough room to work with until a better solution can be implemented within the near future.

That makes me nervous about putting this change in as a short-term patch just to get Scarlets & Blues launched. These short-term patches seem to stick around forever.

**Pull request merged**
