### PR TITLE
Add drop shadow to transcribed lines

### PR DESCRIPTION
**Pull request by eatyourgreens**
- add a drop shadow to all previously transcribed lines.
- darken the grey, completed lines to `light-4`.

Screenshot of completed lines with a drop shadow in the storybook
Screenshot of completed lines with a drop shadow in the dev classifier.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier

## Linked Issue and/or Talk Post
- towards #5291.

## How to Review
You can use the Transcribed Lines story, in the Classifier storybook, to view the new styles.

You can also see them on Davy Notebooks:
https://localhost:8080/?project=humphrydavy/davy-notebooks-project&env=production&workflow=24822

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## New Feature
- [x] The PR creator has listed user actions to use when testing the new feature
- [x] Unit tests are included for the new feature
- [x] A storybook story has been created or updated
  - Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetutorial--default)

### CODE REVIEW

**Comment by goplayoutside3** [comment]
Code changes look good to me! 

@snblickhan and @seanmiller26 would you like to see this PR branch deployed for review? You won't be able to view the storybook mentioned in the description because storybook must be run locally on your laptop to incorporate the changes here.

**Comment by seanmiller26** [comment]
This seems like a step in the right direction but yes, @goplayoutside3 I'd like to take a closer look if possible

**Comment by eatyourgreens** [comment]
I’ve run the storybook deploy for this branch, so you should be able to see the changes in the storybook when it finishes running. 
https://github.com/zooniverse/front-end-monorepo/actions/workflows/deploy_storybook.yml

**Comment by eatyourgreens** [comment]
Or maybe not. Looks like that script always checks out the main branch, even if you specify a different branch when you run the workflow.

**Review by goplayoutside3 — APPROVED** [review]

**Pull request merged**
