### PR TITLE
Refactor subtask to use MovableModal

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-react-components, lib-classifier

Describe your changes:
Swaps out the Layer and ReactRnd component in the sub-task with the new MovableModal. Here's how it's looking in the transcribed lines story:

Screen Shot 2020-06-16 at 11 38 08 AM

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
WIP, double checking tests' success/fail

**Comment by srallen** [comment]
Ok this is ready for review.

**Comment by shaunanoordin** [comment]
I'm testing this on the old Subtask testing workflow (http://localhost:8080/?env=staging&project=1898&workflow=3396, mac OS 10, Chrome) and everything's looking good. 👍 

Code refactor looks A-OK too, so I'm going to see if there's any niche interactions I can try to break. brb!

**Comment by srallen** [comment]
>  I understand that certain parts of the automated tests have been disabled, because it's screwing up with our integration tests? And there's a follow up planned once our jsdom dependency gets upgraded?

To clarify, the tests are passing if I switch to using `mount` for a subset of them, but it's causing an error to be thrown my jsdom. These errors do not cause the tests to fail, but they clutter up the output of the test running, so I thought best to temporarily disable them until the next patch version of jsdom is released with a fix for this. This should be soon, so I'll open an issue to track this.

**Pull request merged**
