### PR TITLE
Add CSS helper for styled-components

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: all where applicable

For #1469

Describe your changes:
Fixes where we have nested templates for css to use the css helper. Might help with the memory issue. ~WIP because I haven't found all the places that need fixing yet.~ 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
I think I've caught all of the instances where the `css` helper should be used. The tests are now passing. There still needs to be a thorough check against the staged deployment for any visual regressions.

**Comment by eatyourgreens** [comment]
Locally, you can check against the production build (same as a staged deploy) by making sure that you have rebased to the latest master, then running `docker-compose up --build` in the root directory. The build takes a while but it runs production version of both the project and content apps with bootstrapped libraries.

**Comment by eatyourgreens** [comment]
CI tests fail for me, running the apps in Docker.
```
yarn_1        |   1119 passing (33s)
yarn_1        |   7 pending
yarn_1        |   1 failing
yarn_1        | 
yarn_1        |   1) Component > ZoomingScatterPlot
yarn_1        |        data boundary constraints
yarn_1        |          when zooming
yarn_1        |            should not zoom in beyond maximum zoom configuration:
yarn_1        |      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/usr/src/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js)
yarn_1        |       at processImmediate (internal/timers.js:439:21)
```

Nothing to do with this PR, as far as I can tell, but that particular test seems to fail intermittently.

**Comment by eatyourgreens** [comment]
I couldn't figure out why the local production build of the content pages app doesn't work, so I've opened #1499.

**Comment by srallen** [comment]
I haven't seen that failure before, but maybe related to the performance issue. I've noted it in #1346

**Pull request merged**
