### PR TITLE
Use contentful category titles

### PR DESCRIPTION
**Pull request by rogerhutchings**
cc #876

This changes the store to return the category titles from Contentful, rather than translate them in the app. This means that everything on that page can be edited via the CMS.

Once a language selector is in place, we'll need to send the language code along with the request in Contentful, or store translations locally (probably more likely) - this is captured in #877

### CODE REVIEW

**Comment by camallen** [comment]
I can't help but feel like this might make life harder for us in the future as it's fragmenting our translations setups.

**Comment by rogerhutchings** [comment]
Yes, it would be fragmenting translations. However:

 - We're talking about 5-10 proper nouns, so manually adding these wouldn't be too much pain (especially since to my knowledge, I think this page only has one other translation)
- The point of using a CMS was to get away from requiring people to submit PRs to change stuff like this
- While it does split up where translation strings are stored, it could still use a common interface (with some changes to Pandora).

I think it's worth it.

**Comment by eatyourgreens** [comment]
Just noting that Pandora is an app specifically for project translators, so doesn't handle UI labels anyway.

**Comment by rogerhutchings** [comment]
I've just tested this out again locally, and it looks fine - can someone give it a 👍 or 👎?

**Pull request merged**
