### PR TITLE
Cache yarn installs across builds

### PR DESCRIPTION
**Pull request by eatyourgreens**
Preserve the yarn cache, and Next build caches, across builds, in GitHub actions. Hopefully, this should speed up CI builds by [caching yarn installs](https://github.com/actions/cache/blob/main/examples.md#node---yarn) unless yarn.lock changes. Next build caching is adapted from [Next's caching example for GitHub Actions](https://github.com/vercel/next.js/blob/master/errors/no-cache.md#github-actions).

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
In the action logs, the Next builds warn about caching those builds too.
```
yarn workspace v1.22.10
yarn run v1.22.10
$ PANOPTES_ENV=${PANOPTES_ENV:-production} next build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
production https://talk.zooniverse.org
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
info  - Creating an optimized production build...
```
We could do that by [caching the `.next/cache` directories](https://github.com/vercel/next.js/blob/master/errors/no-cache.md#github-actions) across builds.

**Comment by srallen** [comment]
@zwolf should be reviewer on this since GA actions is what he's working on right now.

**Comment by zwolf** [comment]
What's the purpose of this workflow? Is this intended to replace Travis for running CI tests? As it stands, it's not going to get run automatically and can't be run manually (no `on:` or `workflow_dispatch:`). Setting up Actions to replace/improve threads of our CI/CD pipeline is already happening, but I'm not clear on what the goal is here.

**Comment by eatyourgreens** [comment]
The build warnings are gone, from the Next builds, but I'm not sure the builds are that much faster than usual. 🤷‍♂️

**Comment by srallen** [comment]
Let's maybe circle back to this when we've migrated other jenkins task to GA? We might see some improvements w/ optimization when we have several CI/CD tasks running on GA then?

**Comment by eatyourgreens** [comment]
Agreed. The [Next error page](https://github.com/vercel/next.js/blob/master/errors/no-cache.md) seemed to imply that we would see large improvements in build times.

**Pull request closed without merging**
