### PR TITLE
Fix tutorial

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

Package: lib-classifier

Fixes a regression introduced by #2198. A refactor was included among the feature which swapped the store connection over to a separate connector file using the newer mobx-react API, however, not all the data needed was copied over. Since `tutorial` was missing, the tutorial has never rendered correctly in the tabbed view:

Screen Shot 2021-07-29 at 3 54 51 PM

I added a smoke test for the connector using react-testing-library. Actually testing that the tutorial is viewable should come later via more refactoring on the test strategy on child components since this will necessarily have to be an integration test, so that will come later.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by goplayoutside3 — COMMENTED** [review]
Looks good! I ran this branch locally and used my own staging project to test the tab view tutorial. I now see the tutorial steps in the tab view. Tests are passing locally 👍 

However, I noticed that several of the stories in the **Tasks** folder do not load at all. This is true on master too. Is a fix for the stories in the scope of this PR?

**Comment by srallen** [comment]
@goplayoutside3 if broken on master, then I'd prefer to fix in a separate branch. It's possible those are broken for a different reason. Thanks for catching those.

**Comment by eatyourgreens** [comment]
That’s my fault. #2198 added the active subject to `Tasks`. I don’t think the task stories have an active subject, just a workflow.

**Comment by goplayoutside3** [comment]
> @goplayoutside3 if broken on master, then I'd prefer to fix in a separate branch. It's possible those are broken for a different reason. Thanks for catching those.

Sounds good!

**Review by goplayoutside3 — APPROVED** [review]

**Pull request merged**
