### PR TITLE
[WIP] Toolbar tooltips

### LINKED ISSUE #76: Add helper labels for image toolbar buttons
**Package**

`lib-classifier`

**Feature or Issue Description**

Following on from https://github.com/zooniverse/front-end-monorepo/pull/74, the Invision designs have a hover state with a text label that needs to be added:

screenshot 2018-07-11 14 57 13

I suggest adding a delay before showing the label, or it could get quite visually noisy.

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-classifier

Closes #76.

Describe your changes:
Started this a while ago, so now just finishing up. This is a refactor of both the buttons and their icons to use more of Grommet and native browser behavior and css where it makes sense. I ended up not using the `Tooltip` component I wrote a while ago and added to the react-components lib because Grommet v2 ended up releasing with a `DropButton` which almost does what we want it to except it's currently breaking keyboard interaction and I have an open issue with them about it. We may want to choose to wait for them to fix that. 

There's also a slightly odd behavior with the focus, but I'm not sure if that's related to the tabindex issue I've already reported with them. 

TO DO
- [ ] Fix any broken tests
- [ ] Wait for Grommet fix

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## PR Mini Review
I understand that this PR is still a WIP, but a quick review of the code as it looks fine, although there are quirks, which I think you're already aware of.

**Overall:** This PR adds tooltips to the Classifier's Toolbar buttons on mouse hover:
screen shot 2019-01-15 at 15 33 28

LGTM 👍 

Note: there is no **keyboard focus** since there's no keyboard navigation on the Classifier yet.

**Quirk 1:** _Sometimes,_ when the Toolbar button loses _mouse_ focus, the hovering tooltip disappears, but there's an odd quirk where the shape of the button enters a "limbo state" because it still has some sort of UI focus. Clicking somewhere else on the page (i.e. resetting the UI focus) fixes this.
screen shot 2019-01-15 at 15 33 47

Also: if the mouse once again hovers over the button that's in a "limbo state", the tooltip does NOT appear as expected.

I assume the above is what was meant with this comment:
> There's also a slightly odd behavior with the focus, but I'm not sure if that's related to the tabindex issue I've already reported with them.

**Quirk 2:** The tooltip has an oddity with its height when the browser window is too narrow.
screen shot 2019-01-15 at 15 34 11

This seems to trigger at browser window widths of 768px and below.

Tested on OSX+Chrome on localhost.

**Comment by rogerhutchings** [comment]
@srallen is this still WIP?

**Comment by srallen** [comment]
Yeah because there's a bug in Grommet with the tabindex for Drop/DropButton... Let me check on the status of the issue with them.

**Comment by srallen** [comment]
Closing for now. We'll have to circle back to this as it's not absolutely essential.

**Pull request closed without merging**
