### PR TITLE
Fix SubjectSetProgressBanner stories

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove `Provider`. Render `SubjectSetProgressBanner`, not `Banners`. Wire up story controls to component props.

Since #2402, the stories are broken with
```
MobX Provider: The set of provided stores has changed. See: https://github.com/mobxjs/mobx-react#the-set-of-provided-stores-has-changed-error.
```

The controls should be updating component props, not generating a new MobX store, when they change.

Package:
lib-classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by shaunanoordin — COMMENTED** [review]
## PR Review

Package: `lib-classifier`
Tangentially Related Projects: Engaging Crowds (EC)

This PR is a minor update to the SubjectSetProgressBanner (which is usually seen on EC projects, which have indexed Subject Sets). No major functional changes to the component, and only thing to test are the Storybook updates.

Code read looks good, give me a second to run tests.

**Comment by eatyourgreens** [comment]
I forgot to link the original bug report, but it was found in this PR comment: https://github.com/zooniverse/front-end-monorepo/pull/2470#issuecomment-940441531

Changing any of the story controls generates a new store on master, which then breaks the story `Provider`.

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

This PR LGTM 👍 

- Running `yarn storybook` on _lib-classifier_ allowed me to view the SubjectSetProgressBanner story with no issues
- Running `yarn dev` on _app-project_ and checking out [Scarlets & Blues](https://local.zooniverse.org:3000/projects/bogden/scarlets-and-blues/classify/workflow/18504?env=production) showed that the SubjectSetProgressBanner continues to work fine.

Sorry for the long test period, but I fell into a hole where I realised I couldn't run `yarn dev` on _lib-classifier_ (Error: _[webpack-cli] Unable to load '@webpack-cli/serve' command. TypeError: options.forEach is not a function_ ) and tried to debug that. I can confirm the issue is extant on master (7f49dc0622d35699d3f60380bb0adaa20e4cc957) so it's not an issue with this PR.

PR approved, going to look at the other bug tomorrow.

**Comment by eatyourgreens** [comment]
Sounds like you might have some outdated dependencies installed.

**Pull request merged**
