### PR TITLE
Transcription workflows: adjust subtask position

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Change the minimum popup height to 200px.
- Include the visible window in position calculations.
- When the popup is below the transcribed line, place the top left corner on the bottom of the transcribed line's bounding box, not in the middle of the line.
- When the transcribed line is towards the bottom of the screen, position the popup above the transcribed line, allowing an offset for the minimum popup height and the transcribed line's bounding box.

## Package
lib-classifier

## Linked Issue and/or Talk Post
Towards #2233. (I'm not sure if the changes here would close that issue for all possible transcription documents and workflows.)

## How to Review
https://localhost:8080/?project=mariaedgeworthletters/maria-edgeworth-letters&env=production

Try transcribing some lines towards the top or the bottom of the viewport. The popup shouldn't appear outside the visible viewport any more, and should be better positioned to avoid obscuring the written lines.

Screenshot of the transcription task, with a purple line at the bottom of the window and the text task popup positioned toward the centre of the visible window area.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I've assumed that `clientHeight` for the SVG line is roughly equivalent to the line height on the written page, but that seems to mostly work.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: `lib-classifier`

This PR fixes an issue with the **vertical placement** of the Transcription Task's subtask popup.

- Baseline: for a project with a Transcription Task, after either (1) a volunteer places a line (click to place start point, then end point) OR (2) clicks on an existing/aggregated line, the **subtask popup** appears.
  - This popup (with a Text sub-Task) _should_ appear in a position that easily allows volunteers to view the text box and being/continue transcribing text.
  - At the moment however, the popup appears in such a way that its top-left corner is positioned at the mid-point between the start point and end point.
- The problem: if the transcribed line appears **near the bottom of the screen (viewport)**, then the subtask starts appearing "off screen"
    Screenshot 2022-06-15 at 21 28 09
    _Pictured: we created a transcription line at the bottom of the screen, causing the subtask popup to be "cut off at the bottom". master branch._
- The fix: PR fixes the issue by simply switching the position of the Subtask Popup to appear ABOVE the line, IF Subtask would appear off screen (below the viewport).
    Screenshot 2022-06-15 at 22 12 42
    _Pictured: same, we created a transcription line at the bottom of the screen, but the subtask popup appears above the line, meaning it's still in view of the user. This PR's branch._

Tests look good to me, specifically when it comes to constraining **the vertical position,** and the vertical position only.

⚠️ One thing to note is that this PR is reviewed with the following knowledge:
_Jim, via Slack: ... It’s more an improvement on the existing code, which can position the popup outside the visible window, rather than an attempt to fix all possible positioning scenarios._

I'll still document all the other _(incredibly unlikely and very niche)_ scenarios that are not covered by this PR in the Dev Notes (below), but those notes should _not_ count against this PR.

### Testing

Tested on lib-classifier on localhost with macOS +Chrome 102

- Testing URL: https://localhost:8080/?project=mariaedgeworthletters/maria-edgeworth-letters&env=production - a project/WF with one standard Transcription Task.
- I placed transcription lines on various places and observed the position where the Subtask Popup appears.
- Placed a _standard horizontal transcription line_ on the page, with the viewport positioned so that the line appears _near the top of the screen._
  - Subtask appears below the line, within the visible screen. 🆗 
- Placed a _standard horizontal transcription line_ on the page, with the viewport positioned so that the line appears _near the bottom of the screen._
  - Subtask appears above the line, within the visible screen. 🆗 
  - ❔ ~~The Subtask popup _can_ appear directly in front of (blocking) the green line in some cases (see picture above), but I don't think this is a notable issue.~~ _This only occurs at wonky zoom levels + screen sizes._
- Same as above, but RTL instead of LTR
  - Same results 🆗 

Looks good! 👍 

### Dev Notes

Here are a few scenarios that _aren't_ covered by this PR's fix. The following are NOT blocking comments - just read 'em and then file 'em away in your mind palace.

- Subtask doesn't compensate for limited horizontal space, e.g. on mobile (portrait) view
    Screenshot 2022-06-15 at 21 28 47
    _Above: window was narrowed horizontally until the layout of the classifier switched into mobile/portrait mode, then a standard horizontal line was placed. Theoretically it's possible to compensate the xOffset and popupWidth, but that's for another PR._
- Subtask popup position acts _slightly_ differently for _vertical lines_ placed near the bottom of the screen: specifically, for _tall_ vertical lines vs _short_ vertical lines.
  - For a short vertical line, the popup appears near the line:
      Screenshot 2022-06-15 at 22 07 48
  - For a tall vertical line (from bottom _up to_ 50% viewport height), there's a big gap between the line and the popup.
      Screenshot 2022-06-15 at 22 07 29
  - This is due to the yOffset calculating for markHeight: the taller the line, the higher the popup appears.
  - This is in practice a non-issue, though. Even if the position might be a bit odd, the popup is still vertically bound to the visible viewport.
  - This might only mildly bother somebody who's working with a really tall vertical monitor.
- Subtask position calculations don't work when viewport is too small. ...because of course. Why did you make your window so small? (I still tested it anyway.)

### Status

LGTM! 👍 Let's get this merged for the volunteers.

**Comment by eatyourgreens** [comment]
A refinement could be to check the aspect ratio of the SVG mark’s bounding box, then have different behaviour for horizontal and vertical boxes.

**Comment by eatyourgreens** [comment]
Another refinement would be better tests. The current tests check that the `x,y` coordinates are numbers but they could test a mocked box against the mocked window height and width. We have a helper for out-of-bounds shapes which might be useful here.

**Pull request merged**
