### PR TITLE
[VSLCV] Add in basic specs for getting JSON subject

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

Describe your changes:
This adds basic specs for the container lifecycle and requesting for the JSON data from the JSON subject for the variable star viewer. This is similar to how the scatter plot and bar chart does it too that we may abstract out later. 

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
There are a couple of changes in #1533 that I'd like to move into this branch instead, so I'm going to move this back to WIP.

**Comment by srallen** [comment]
Ok, @wgranger this is ready for review.

**Comment by srallen** [comment]
@wgranger I just rebased and the stories appear to be working again. I think that's correct with the issue being I must've accidentally left something in here that used the other code in the other PR. These last few PRs are essentially cherry-picked commits out of a bigger branch I have locally because I'm trying to submit smaller ones for review and it's hard to make sure I'm keeping them independent units of change.

**Comment by wgranger** [comment]
LGTM

**Pull request merged**
