### PR TITLE
Upgrade to React 18

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Bump `react` and `react-dom` to 18.2.
- Bump `@testing-library/react` to 14.0.
- Remove `@testing-library/react-hooks`.
- Disable `React.StrictMode` for `ClassifierContainer` (see https://github.com/reactwg/react-18/discussions/19.)
- Wrap all our stories (and associated tests) in the new, stricter strict mode.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
app-content-pages
app-project
lib-classifier
lib-react-components

## How to Review
There are a few options. Pick the one you're most comfortable with:
- [Build and start both NextJS apps locally in Node](https://github.com/zooniverse/front-end-monorepo/#with-node-and-yarn) to verify that they still build and run.
- [Build and start a Docker image](https://github.com/zooniverse/front-end-monorepo/#docker), then check both NextJS apps on localhost.
- [Build and deploy a Docker image of this branch](https://github.com/zooniverse/front-end-monorepo/actions/workflows/deploy_branch.yml), then check the project app on https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess. There's no branch preview on kubernetes for the content pages app.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Maintenance
- [x] If not from dependabot, the PR creator has described the update (major, minor, or patch version, changelog)

### CODE REVIEW

**Comment by eatyourgreens** [comment]
NextJS builds fail with:
```
Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
```

**Comment by eatyourgreens** [comment]
The project app fails with the same error. The build succeeds, but the React app fails in the browser.

**Comment by eatyourgreens** [comment]
Builds are fixed and deployed to kubernetes for testing:
https://fe-project-branch.preview.zooniverse.org/projects/zooniverse/gravity-spy

**Comment by eatyourgreens** [comment]
The various fix commits on this branch should be pulled out into their own PR, so that they can be applied to the React 17 deploys too.

**Comment by eatyourgreens** [comment]
NextJS development mode is broken on this branch, because of https://github.com/mobxjs/mobx/issues/3669. 

Production builds should work without problems.

**Review by mcbouslog — COMMENTED** [review]
Tested on a lot of live FEM projects per [FEM active projects](https://docs.google.com/spreadsheets/d/1X9345vQ_xNX6BJf9_xwVCQCjxjbWWErGmV7Xe8WpHZo/edit#gid=0) spreadsheet (see column M for links to) `fe-project-branch.preview` without issue. ✅ 
Tested app-project locally without issue. ✅ 
Tested app-content-pages locally without issue. ✅ 

Noted the following errors/warnings on app-project and app-content, but I think expected as per [React upgrade docs Other Breaking Changes section](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#other-breaking-changes) Stricter hydration errors:
- Warning: An error occurred during hydration.
- Uncaught Error: There was an error while hydrating. [link](https://legacy.reactjs.org/docs/error-decoder.html/?invariant=423)

Also see the following error, though I think fixed with NextJS 13 upgrade:
- Uncaught Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering. [link](https://legacy.reactjs.org/docs/error-decoder.html/?invariant=407)

Not blocking, but lib-classifier/dev/index.js could be refactored with `import { createRoot } from 'react-dom/client'` per [this note in React upgrade docs](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis).

This is a core dependency upgrade so I presume at least one other dev should also review? Otherwise looks good to me. eatyourgreens++ !!

**Comment by eatyourgreens** [comment]
The classifier tests still fail in strict mode, so I’m going to leave that disabled for the moment.

**Comment by eatyourgreens** [comment]
Good catch, re. upgrading the dev classifier to the new API!

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Packages: `app-content-pages`, `app-project`, `lib-classifier`, `lib-react-components`

This PR is a **major dependency update** that also adds StrictMode when rendering in local dev.

- Code read looks straightforward, but as with all major dependency updates, functional/feature tests are the main determinator for "is this OK?".
- Testing on `app-project` and `lib-classifier` indicates that the Zooniverse website mostly works as normal. 👍 
- ❗ However, a notable _StrictMode + React 18_ issue was noted when testing the LightCurveViewer on local development _on lib-classifier's local development_ specifically. This does **not** affect the LCV (i.e. the Planet Hunters TESS project) on production, nor on app-project local development.

### Testing

Tested on localhost with macOS + Chrome 116

**lib-classifier**

Testing Steps
- Open the Classifier on the Planet Hunters TESS **(LightCurveViewer)** main workflow: https://local.zooniverse.org:8080/?env=production&project=nora-dot-eisner%2Fplanet-hunters-tess&workflow=11235&demo=true
  - ❗ ERROR: the LightCurveViewer isn't displayed. The D3 chart is rendered with 0 data points.
      Screenshot 2023-08-31 at 22 46 57
  - Removing `<StrictMode>` from the `src/components/Classifier/Classifier.js` file will "fix" the issue (or more accurately, avoid the situation that triggers the error).
- Open the Classifier on any random workflow with a **Text Task:** https://local.zooniverse.org:8080/?env=staging&project=darkeshard%2Ftest-project-2022&workflow=3596
  - I'm able to type in answers and submit Classifications (confirmed with network submission)
- Open the Classifier on any random workflow with a **Question Task:** https://local.zooniverse.org:8080/?env=staging&project=darkeshard%2Ftest-project-2022&workflow=3582 
  - I'm able to select answers and submit Classifications (confirmed in network)

**app-project**

Testing Steps:
- View a random **simple test project:** https://local.zooniverse.org:3000/projects/darkeshard/test-project-2022/
  - I can see the home page, login, and logout
- View a random **simple test workflow:** https://local.zooniverse.org:3000/projects/darkeshard/test-project-2022/classify/workflow/22164
  - I can make & submit classifications
- View **Planet Hunters TESS, a Light Curve Viewer project**: https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?env=production
  - ✅ I can view the light curve data, I can pan & zoom the viewer, I can make/delete/edit annotations, and I can submit classifications
  - _Dev note: my assumption is that app-project uses the built/"packaged" version of the classifier, so StrictMode isn't kicking in for the component. Or maybe app-project's Classifier Page is missing a StrictMode. Hmmmm._ 
- View **SuperWASP Black Hole Hunters, a ScatterPlotViewer project:** https://local.zooniverse.org:3000/projects/hughdickinson/superwasp-black-hole-hunters
- View **HMS NHS, a project with Subject Set Selection:** https://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service
- View **Davy Notebooks, a transcription project:** https://local.zooniverse.org:3000/projects/humphrydavy/davy-notebooks-project
  - For SuperWASP, HMS NHS, and Davy Notebooks, I'm able to navigate to the Classify page, view the data, and make some annotations.

### Status

I'm giving this PR a 👍 since Planet Hunters TESS and the Light Curve Viewer continues to work in every scenario _except_  lib-classifier on local development. The practical effect to this is that, if devs want to tweak the LCV on local, they need to disable StrictMode.

The more long-term effect is that LCV needs to be upgraded to fit React 18 + StrictMode, OR replaced with ScatterPlotViewer. I'll open a new issue to address this.

**Pull request merged**
