### PR TITLE
Fix Next.js build warnings and errors

### LINKED ISSUE #5409: Next 13: build errors
## Package
_Choose from the list:_
- [x] app-content-pages
- [x] app-project

## Describe the bug
A couple of build errors since upgrading to Next 13:
- `eslint-config-next` errors during project builds.
>info  - Linting and checking validity of types ..error - ESLint: Failed to load parser './parser.js' declared in '.eslintrc » eslint-config-next/core-web-vitals » /Users/odonnell/zooniverse/front-end-monorepo/node_modules/eslint-config-next/index.js': Cannot find module 'next/dist/compiled/babel/eslint-parser' Require stack: - /Users/odonnell/zooniverse/front-end-monorepo/node_modules/eslint-config-next/parser.js - /Users/odonnell/zooniverse/front-end-monorepo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

- [`modularizeImports`](https://nextjs.org/docs/architecture/nextjs-compiler#modularize-imports) is stable, not experimental, in Next 13.4.

## To Reproduce
Build the Next.js apps. Both errors are logged to the console.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- fix `eslint-config-next` errors when `app-project` builds.
- move `modularizeImports` up to the top level in the `app-content-pages` config.
- fix a build error in the project `Head` that stops the app from building. 
- closes #5409.

## Package
- app-content-pages
- app-project

## How to Review
With a clean install of the monorepo, both Next.js apps should build and start without the build errors from #5409.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I'll bump this to 13.5.4.

**Comment by eatyourgreens** [comment]
Bumped to Next.js 13.5.4.

**Comment by eatyourgreens** [comment]
13.5.4 seems to have broken storybook builds.
>ModuleNotFoundError: Module not found: Error: Can't resolve 'next/dist/shared/lib/router-context' in '/Users/odonnell/zooniverse/front-end-monorepo/packages/app-content-pages/node_modules/@storybook/nextjs/dist'

**Comment by eatyourgreens** [comment]
I've removed the upgrade to 13.5 from this PR and put it in #5449.

**Review by goplayoutside3 — APPROVED** [review]
Looks good!

**Pull request merged**
