### PR TITLE
Movable field guide

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-classifier

Describe your changes:
This implements the `MovableModal` for the use with the field guide in the classifier. 

Demo using the dev classifier:

movable-field-guide

~WIP because specs need updating and I'd like to do some additional refactoring.~ 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
Ok, this is ready for review. This can be tested using the dev classifier, running `yarn dev` in the lib-classifier folder and navigating to https://localhost:8080/?project=4878&workflow=16135&env=production. This is the project I used to make the gif. 

@ErikOstlund many of the changes in this PR were part of #1975 and already reviewed and approved. Since that merge, I've included some additional refactors and changes that fix the resizing issue you brought to my attention. I had to use the `onResize` event handler available for the underlying react-rnd dependency used by the `MovableModal` to manually control the height because we want the modal to open at an initial 415px but be resizable at will by the user. 

cc @beckyrother this implements the original design concept of allowing users to move and resize the field guide!

**Comment by srallen** [comment]
@ErikOstlund one additional thing to note is that I added the `ResponsiveContext` to the component to detect what size screen we're on and to fallback to standard `Modal` component for mobile sizes rather than a resizable and movable `MovableModal`.

**Review by beckyrother — COMMENTED** [review]
WOO! When you close and re-open, does it reappear in the location you closed it from?

**Comment by srallen** [comment]
@beckyrother it doesn't. It will always open up on the far right hand side centered. Tracking the position it was last rendered could be a bit tricky. We'd probably want to disallow partially off screen positions? I'm not sure. Maybe something to consider for a future iteration?

**Review by ErikOstlund — APPROVED** [review]
Looks good! Field guide is movable and resizes as expected. All unit tests pass.

**Review by beckyrother — APPROVED** [review]
I think in the future it would be worth looking into saving the position, but not necessary for MVP. I'm actually ok with it going off the edge of the screen, in case someone has a small screen and still wants to leave it open while working.

**Pull request merged**
