### PR TITLE
Classifier: refactor subject set store and allow for undefined workflows

### LINKED ISSUE #2033: Error: [mobx-state-tree] Cannot resolve a reference to type 'SubjectSetResource' with id: '85304' unambi...
Sentry Issue: [FEM-APP-PROJECT-J2](https://sentry.io/organizations/zooniverse-27/issues/2210820358/?referrer=github_integration)

```
Error: [mobx-state-tree] Cannot resolve a reference to type 'SubjectSetResource' with id: '85304' unambigously, there are multiple candidates: /workflows/resources/16807/subjectSets/resources/85304, /workflows/resources/16852/subjectSets/resources/85304
  at promiseReactionJob ([native code])
...
(22 additional frame(s) were not displayed)
```

### LINKED ISSUE #2034: Engaging Crowds: ReferenceError: No workflow ID available
Sentry Issue: [FEM-APP-PROJECT-HZ](https://sentry.io/organizations/zooniverse-27/issues/2208895729/?referrer=github_integration)

```
ReferenceError: No workflow ID available
  at Promise ([native code])
  at n ([native code])
  at mu ([native code])
  at eu ([native code])
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by eatyourgreens**
Subject sets can be shared across workflows, but identifiers can only be stored once in the state tree. This leads to crashes if I try to work on the same subject set in two different workflows during the same classification session (#2033.) This PR refactors the subject store so that each set is stored in one place and workflows carry references to the currently selected set. Note that each workflow may have a different selected set. 

I've also updated the classifier so that it checks for a workflow ID before changing the active workflow on props change (#2034.)

To test this, you'll need to build the classifier, then run the new classifier inside a production build of the project Classify page. `yarn build` and `yarn start` inside `packages/app-project`. `yarn dev` for the project app reloads the classifier whenever you click a link, which means you can't trigger either bug in development.

Test URL:
http://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/16852/subject-set/85304
Click 'Classify' in the top menu to trigger #2034. Choose a new workflow and subject set from the workflow menu to trigger #2033. Both should be fixed on this branch.

Package:
lib-classifier

Closes #2033.
Closes #2034.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Testing underway, but I'm a bit slow since my Chrome and Firefox have both decided to raise those "invalid HTTPS response" errors again, yaargh! I'm not sure why it's so inconsistent. (Current workaround: hack app-project's webpack.dev.js to set https:false)

**Comment by shaunanoordin** [comment]
I'm confirming that I can see the issue on `master` (78b017f450ce15795a84ad0622c65da68c485e13) for the NHS project (which is configured to have multiple choosable Workflows and Subject Sets), but with some minor footnotes.

- Opening the Classify page directly works fine. http://localhost:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify
  - ❔ This is notable because I had previously complained that I'd get the "No Workflow ID available error" as seem in #2034 
  - No errors, good.
- Trying to replicate the error described in this PR lets me confirm 2033 and 2034. Replication steps:
  - Step 1: I open the [Classify page,](http://localhost:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify) then choose Workflow A, then choosing Subject Set C
  - Step 1.5: I'm now taken to the the Classify page
    - ❔ ...but sometimes the Subject wouldn't load properly. (Not sure what's up with this, but I'm ignoring it for tests for now)
  - Step 2: I click on the 'Classify' link _then wait a few seconds_
    - The "No Workflow ID available error" appears, consistent with #2034
    - ❔  (I'm not sure why my ol' error is only visible when clicking on the Classify link from certain pages. I mean, I can't even trigger 2034 by clicking on the Classify link from the [project home page!](http://localhost:3000/projects/msalmon/hms-nhs-the-nautical-health-service) )
  - Step 3: I choose Workflow B, then Subject C.
  - Step 3.5: I'm taken to the Classify page
    - ...and I see error #2033, with the `Cannot resolve a reference to type 'SubjectSetResource' with id: '82738' unambigously` message.

I've got a two ❔ question marks in the replicability of my testing method, but eh, it's time to get into the PR itself. I've established for myself how to test for the described errors, at least.

(note: I've modified `lib-application`'s `yarn dev` to use PANOPTES_ENV=production because otherwise the ?env=production gets lost during some page transitions on localhost testing.)

**Comment by eatyourgreens** [comment]
I’m pretty sure that the workflow ID error is caused by `componentDidUpdate`. The trigger is the workflow ID changing to `undefined` during a props change. As far as I can tell, that can’t be triggered in dev mode because the dev mode Next app always reloads the page, mounting a new classifier. 

The production build re-renders the loaded page, which passes down new props to the already mounted classifier.

**Comment by shaunanoordin** [comment]
Oh nooo goddammit does this mean I need to have an additional test set for a _production environment?_ Because holy heck Next is driving me nuts.

At the moment I'm able to replicate the Workflow ID is missing _on this branch_ by performing the following:

**Setup:**
- Package: `app-project`
- `export PANOPTES_ENV=production ; yarn dev`
- Project: HMS NHS
- Using localhost, macOS10+Chrome88

**Scenario 1: start from root Classify page**
- Open the root Classify page: `http://localhost:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify`
  - You will now see the WF selection menu.
- Choose any Workflow. Choose any Subject Set.
  - You will now see the Classify page for a specific WF + SS, e.g. http://localhost:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/16807/subject-set/82738
  - ❔ (Note: sometimes, the Subject image and Tasks might not load. This is a very odd quirk.)
- Click on the 'Classify', then _wait a few seconds_
  - Expectation: I should see the WF selection menu again.
  - Actual: "ReferenceError: No workflow ID available" (See #2034)
- Close the error popups. Choose a **different workflow** and the **same subject set**
  - Expectation: specific Classify page should display
  - Actual: "Error: [mobx-state-tree] Cannot resolve a reference to type 'SubjectSetResource' with id: '82738' unambigously (sic)" (see #2033)

**Scenario 2: start from a specific Classify page**
- Open a specific Classify page: `http://localhost:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/16807/subject-set/82738`
- Proceed with the rest of the steps in Scenario 1
- Same results
  - ❕  ...with one small footnote: if I open a specific Classify page, I don't encounter the "missing Subject image, missing Tasks" quirk I described in Scenario 1.

**Comment by shaunanoordin** [comment]
Wait, I just realised why my tests may not be working properly. The major change is in `lib-classifier` (the classifier's new `. selectWorkflow()` code adds the safety for when Workflow ID is undefined...

BUT I've been testing on `app-project`, which appears to be pulling an older version of the Classifier. Hmm, I'm going to need to update the app-project to pull the most recent code from lib-classifier... brb, gonna re-bootstrap and re-build.

**Comment by eatyourgreens** [comment]
Yeah, I recommend building the classifier *and* the project app, then using `yarn start` to serve the project. Reason being, I think hot reloading interferes with reproducing the bug.

**Comment by eatyourgreens** [comment]
Also, I rebuilt the classifier stores to fix the duplicate subject set error. So that would need a rebuild of the classifier too.

**Comment by eatyourgreens** [comment]
Based on your comments here, I think this might be a different bug, which you’re also running into: https://github.com/zooniverse/front-end-monorepo/issues/2034#issuecomment-779220577

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Packages: `lib-classifier`, `app-project`

This PR fixes two issues related to the classifier when it comes to projects with multiple selectable Workflows + multiple selectable Subject Sets.

- When accessing a the root Classify page, there's a chance of encountering a "Workflow ID not defined" error (#2034)
- When viewing the specific Classify page for Workflow A + Subject Set C, you'd receive an error if you then try to change the page to view Workflow B + Subject Set C (#2033)

Code changes look good, and testing actually turned out really well. I just faffed about for longer than usual because I didn't pay attention to the changes happening across two packages that required a bootstrap/rebuild - this PR turns out to be incredibly straightforward and functional 👍 

### Testing

**Setup:**
- Package: `app-project`
- bootstrap everything first!
- `export PANOPTES_ENV=production ; yarn dev`
- Project: HMS NHS
- Using localhost, macOS10+Chrome88

**Main Scenario: HMS NHS project**
- Open the root Classify page: `http://localhost:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify`~~
- Choose any Workflow. Choose any Subject Set.
- Click on the 'Classify', then _wait a few seconds_
  - If the "ReferenceError: No workflow ID available" error would appear, it would have appeared here (See #2034)
- Close the error popups. Choose a **different workflow** and the **same subject set**
  - If the "Error: [mobx-state-tree] Cannot resolve a reference to type 'SubjectSetResource' with id: '82738' unambigously (sic)" error would appear, it would have appeared here (see #2033)

**Appendix: Basic Test Project**
- Performed some baseline tests on another test project, `http://localhost:3000/projects/darkeshard/engaging-the-crowds-2020`, with various configurations
- Project with multiple workflows:
  - Going to /classify opens the Workflow selection menu.
  - Navigating to/from the Classify pages works correctly
- Project with single workflow:
  - Going to /classify correctly redirects to that one workflow
- Project with no workflow:
  - Going to /classify displays the "Nothing to Classify" message
- Attempting to view a workflow that doesn't exists
  - 404 page

No issues detected. 👍 

### Status

LGTM!

**Comment by shaunanoordin** [comment]
> Based on your comments here, I think this might be a different bug, which you’re also running into: #2034 (comment)

Yup, I was running into a two different bugs, but good news is that this PR fixes them both! 👍

**Comment by eatyourgreens** [comment]
Thanks for taking a look. I’ve not been able to reproduce the bug on master with `yarn dev`, so I’d be careful about testing in development mode.

**Pull request merged**
