### PR TITLE
Add storybook docs pages for documented components

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Add `tags: ['autodocs']` to any component that has prop types with docgen comments. Bonus points for any that also have a component description!
- Correct any inline JS comments, `/*`, that were incorrectly written as docgen descriptions, `/**`. That makes components with docgen documentation easier to find.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- app-project
- lib-classifier
- lib-react-components

## How to Review
Open up the storybooks. Components that have docgen comments should now have Docs pages with those comments describing the components and, in some cases, a description for the component too.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate

## New Feature
- [ ] The PR creator has listed user actions to use when testing the new feature
- [ ] A storybook story has been created or updated
  - Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetutorial--default)

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I'm going to set this to draft because I'm not seeing our docgen comments in the storybook. Eg. The subject set picker should have descriptions for both the component and each of its props, in the project storybook, but I'm not seeing them. 🤔

**Comment by goplayoutside3** [comment]
@eatyourgreens I’m doing a little bit of research into Storybook docs again and wanted to make sure I understand the changes to code comments here. In this PR and in PR #5042 you mentioned that `/** */` is reserved for JSDoc and docgen. The comments in the spec files are changed to `/* */` here because we don't use anything that incorporates docgen for spec files - is that correct?

I did a bit of digging and experimenting with our storybook files to try for consistent descriptions and docgen comments, but am out of luck. Adding tags: ['autodocs'] does create a docs page, but I haven't had success using JSDocs to render a component description 😞 I'll keep this issue in mind going into the fall, and perhaps during the scheduled ZTM FEM Documentation session we can write up with an ideal Storybook Docs page for each component would look like.

**Comment by goplayoutside3** [comment]
@eatyourgreens checked in to see if you'd like to continue with this PR or close it for now?

**Comment by eatyourgreens** [comment]
Probably not worth fixing the conflicts on this.

**Pull request closed without merging**
