### PR TITLE
Upgrade NextJS to 9.4.1

### PR DESCRIPTION
**Pull request by eatyourgreens**
Package:
app-content-pages
app-project

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Changes look legit. Let me run `panic` and `bootstrap` to make sure everything compiles fine, brb

**Comment by eatyourgreens** [comment]
I don't think this is related to this update as such, but I'm seeing errors on Galaxy Zoo because social media links are being treated as internal links.

Screenshot of Galaxy Zoo, with an error thrown because `https://twitter.com/galaxyzoo` is not a valid URL for the project router.

**Comment by eatyourgreens** [comment]
I've fixed the unhandled exception for project links, and I couldn't see any other problems when testing with a live project, but this maybe needs another review.

**Comment by srallen** [comment]
I'm doing a quick check right now to make sure the production images build locally. Ran into a weird docker error for the content-pages app, but I'm mid rebuild right now, so might not be an issue for the upgrade.

**Pull request merged**
