### PR TITLE
WIP Fix content pages links

### LINKED ISSUE #1054: Content pages app breaks the back button/browser history
**Package**
app-content-pages

**Feature or Issue Description**
Navigate to the new publications page, then use the back button or browser history to navigate back to a previous page. The window location changes but the browser still displays the publications page.
Screenshot showing the publications page displayed but the location is /projects.

### PR DESCRIPTION
**Pull request by rogerhutchings**
Adds a prop to `AboutHeader` links to determine whether they should be rendered on PFE or the content pages app. This should stop the issue where the content pages app tries to render pages that aren't there, breaking the back button.

Fixes #1054

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
The code changes look A-OK, but I can't seem to replicate the _original issue_ reported in #1054 on _master._

### Testing

1. Basic setup: `git checkout master` (commit 8139b9f79f25ffc16caaf902f7974e54ce420c2d), `yarn bootstrap`, `cd packages/app-content-pages/`, `yarn dev`
2. Start at the team page: `http://localhost:3000/about/team` -> I see the Team page
3. Click 'Publications' in nav bar to navigate to `http://localhost:3000/about/publications` -> I see the Publications page
4. Press the 'Back' button on my browser to return to the previous page -> I see the Team page, as expected.

Tested on macOS 10 + Chrome 78

I've tried a few variations...

- For step 3, type in 'http://localhost:3000/about/publications' into the browser nav bar instead of clicking 'Publications'
- Starting at Publications, clicking on FAQ (leading to a 404), then pressing the Back button
- Starting at FAQ (a 404), typing in the publications URL, then pressing the Back button

...but I can't seem to replicate the issue.

This PR doesn't break any functionality, but I can't confirm if it's solving the problem it's intended to... I'm probably missing something obvious here.

**Comment by shaunanoordin** [comment]
Oh no! I just realised, is this one of those problems that I can't test unless it's on production when all the components are assembled? I re-examined Jim's screenshot from 1054 and saw that the the URL showing the incorrect page is `https://www.zooniverse.org/project`

**Comment by shaunanoordin** [comment]
## PR Review (Update)

I'm following up on the investigation on issue #1054 - essentially, I think the problem may lay with the _routing_ between NextJS modules (i.e. `monorepo/app-projects` and `monorepo/app-content-pages`) and the classic PFE module (i.e. we're still using `Panoptes-Front-End` for rendering the home page and Projects page) 

Please see comment https://github.com/zooniverse/front-end-monorepo/issues/1054#issuecomment-552457204 for more details.

**Comment by srallen** [comment]
@rogerhutchings is this still WIP? Should this be passed on to someone else or closed?

**Comment by eatyourgreens** [comment]
We're seeing this same bug on the project home page. See #1377.

**Comment by srallen** [comment]
I still don't know if this is WIP or not, so closing.

**Pull request closed without merging**
