### PR TITLE
Fix style regression from #1871

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-react-components, app-project

This fixes a style regression I introduced when I removed the default margin top from the shared `MetaToolsButton`. The margin was interfering with the styles in the context I was using it in, but I missed replacing an alternative with its use in the project app's recent subjects. 

Before:
Screen Shot 2020-11-10 at 2 57 26 PM

After:
Screen Shot 2020-11-10 at 2 53 45 PM

This can be tested first by running  `yarn bootstrap` to build the packages,  then go to the app-project folder and run `yarn storybook`. The relevant story is Classify > Recent Subjects. I also added some basic stories for the react-components library  storybook for `MetaToolsButton` so we can preview and adjust it more easily in the future. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by srallen** [comment]
@ErikOstlund if it's at all possible, it'd be helpful to have this reviewed before we want to deploy the app. Usually we do this on Wednesdays, but could push to Thursday if needed.

**Review by ErikOstlund — CHANGES_REQUESTED** [review]
All tests pass. The margin issue is fixed in Storybook.
@srallen The 'Add to Favorites' and 'Add to Collections' links are underlined when a user hovers over the link. The 'Discuss on Talk' link does not. Should it?
image

**Comment by srallen** [comment]
@ErikOstlund yes, that appears to be a style bug as well, but I don't think introduced by my change from #1871. Would you be ok with me tracking it in a separate issue to keep this one scoped to fixing the regression I introduced?

**Review by ErikOstlund — APPROVED** [review]
The scope of this PR is good to go!
The hover state for the 'Discuss on Talk' link will be fixed in a different PR.

**Pull request merged**
