### PR TITLE
Render the NextJS apps with Million.js

### PR DESCRIPTION
**Pull request by eatyourgreens**
Install [`million`](https://million.dev/), a virtual DOM replacement for React 16+ that promises to be almost as fast as vanilla JavaScript, and add it to both NextJS apps and the dev classifier. 
https://million.dev/docs/install

You should see a marked speed improvement for interactive components on this branch. For example, no lag after clicking buttons in survey tasks.

https://github.com/zooniverse/front-end-monorepo/assets/59547/9cf45503-63e9-4ae2-b4a7-19762723fd73

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- app-content-pages
- app-project
- lib-classifier

## Linked Issue and/or Talk Post
- includes #3887.

## How to Review
There are a few options. Pick the one you're most comfortable with:
- [Build and start both NextJS apps locally in Node](https://github.com/zooniverse/front-end-monorepo/#with-node-and-yarn) to verify that they still build and run.
- [Build and start a Docker image](https://github.com/zooniverse/front-end-monorepo/#docker), then check both NextJS apps on localhost.
- [Build and deploy a Docker image of this branch](https://github.com/zooniverse/front-end-monorepo/actions/workflows/deploy_branch.yml), then check the project app on https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess. There's no branch preview on kubernetes for the content pages app.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Maintenance
- [ ] If not from dependabot, the PR creator has described the update (major, minor, or patch version, changelog)

### CODE REVIEW

**Comment by eatyourgreens** [comment]
It would be interesting to see if this has any effect on dragging DOM nodes (#5110.)

**Comment by eatyourgreens** [comment]
This PR might reduce the time it takes for both Next.js apps to mount and run in the browser. They’re both quite slow at the moment.

**Review by shaunanoordin — COMMENTED** [review]
The code changes look really straightforward, so at a glance, I don't have any issues. 👍 At the moment, I'm trying to formulate a proper test (targeting app-project) so we can really capture the before/after performance difference.

brb.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Packages: app-project (Next.js), app-content-pages (Next.js), lib-classifier (local dev server only)

This PR updates 3 of our packages to use [Million.js,](https://million.dev/) which is supposed to make our React code faster (render DOM elements faster?)

- Code changes look fine
- I'm able to build & run app-project locally as a Next.js app, so basic build functionality looks fine.

Everything looks fine, though I couldn't properly figure out a good way to run performance benchmarks/tests to see _how much better_ Million.js makes our code. Ah well!

### Testing/Dev Notes

Tested with app-project on localhost, with macOS + Chrome, on a local dev server. Several actions were performed and timed, comparing the `master` with the `react-million` branch. `yarn bootstrap` was run whenever branches were switched; a new Chrome incognito window was opened every time a test was run. Network anomalies not accounted for.

**Test 1: what's the performance diff on a standard test project?**

- clear Next cache, build app-project, run app-project as Next app: `rm -fr .next ; yarn build ; yarn start`
- Open test project's home page in a new Incognito window: https://local.zooniverse.org:3000/projects/darkeshard/test-project-2022
- (timer start)
- go to About 
- go to Classify, select 
- submit 1 Question and 1 Text task
- (timer end)

`master`
00:00:24.32
00:00:22:03
00:00:23:57
= 23.3s average

`react-million`
00:00:21.92
00:00:20.50
00:00:20.09
= 20.8s average

Notes:
- There's a small but noticeable improvement here; I think this was most noticeable when _switching pages._
- The PR notes said that _"You should see a marked speed improvement for interactive components on this branch. For example, no lag after clicking buttons in survey tasks.",_ so let's see if there are any noticeable improvements with survey tasks (i.e. complicated tasks that update the DOM/UI a lot, but not switch pages.)

**Test 2: what's the performance diff on complicated tasks that update the DOM/UI a lot, but not switch pages?**

- clear Next cache etc
- Open WildCam Gorongosa's Classify page with a Survey Task: https://local.zooniverse.org:3000/projects/zooniverse/wildcam-gorongosa/classify/workflow/11459?demo=true&production=true
- close Tutorial
- (timer start)
- Choose 'Aardvark', 1 (how many), Resting, yes (young present) OK
- Repeat for Hippopotamus, Reptiles, Baboon, Honey Badger, Rodent
- Submit
- (timer end)

`master`
00:00:37:70

`react-million`
00:00:37.00
00:00:37.64

Notes:
- No noticeable difference here, though I did only run a few tests. At a personal level, I didn't feel much improvement in speed - but nothing was worse either, so that's fine.

### Status

There are probably better benchmark tests that I can run, but honestly the PR works as is, and any additional time spent on testing would just be for extra documentation. LGTM! 👍

**Pull request merged**
