### PR TITLE
Project app: Refactor subject picker data fetching

### PR DESCRIPTION
**Pull request by eatyourgreens**
- refactor `fetchStatuses` to remove the callback and translation arguments.
- set state directly in the `SubjectPicker` component, after fetching data from APIs.
- refactor `useEffect` to make its dependencies explicit in the subject picker.
- refactor subject statuses to use the `useTranslation` hook in the parent component.

#3571 highlighted bad tests in the `SubjectPicker` component, which failed when we upgrade to NextJS 12.2. Here, the `fetchStatuses` helper is refactored to fetch new data and return it to the parent component. Previously, it used a callback to set state in the parent component, which led to problems when tests mocked the `setRows` function.

## Package
app-project

## How to Review
`yarn build` shouldn't generate any warnings for the `SubjectPicker` component. Many of the other build warnings are fixed in #3628.

Tests should still pass with the new code, and subject selection should still work on those projects that use it.

Test URL:
https://local.zooniverse.org:3000/projects/profdrrogerlouismartinez-davila/deciphering-secrets-unlocking-the-manuscripts-of-medieval-spain/classify/workflow/19276/subject-set/106935?env=production

Subject statuses should be correctly translated too:
https://local.zooniverse.org:3000/projects/es/profdrrogerlouismartinez-davila/deciphering-secrets-unlocking-the-manuscripts-of-medieval-spain/classify/workflow/19276/subject-set/106935?env=production

Subject selection in Spanish, showing each subject as 'Disponible'.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [x] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [x] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by goplayoutside3** [comment]
I can put this on my list to review, but @eatyourgreens do you want to use this PR to refactor the unit tests to RTL?

**Comment by eatyourgreens** [comment]
The test doesn't render a React component, just runs a function and checks the result.

**Comment by eatyourgreens** [comment]
On the other hand, the tests are using `mount` so that might be a very quick rewrite. 🤔

**Comment by eatyourgreens** [comment]
@goplayoutside3  I’ve made a quick pass at removing Enzyme from the tests. A couple of them query inside the Grommet `DataTable` component, but I think that’s ok as we expect certain accessible names and roles to exist, regardless of implementation eg. there should be a table row for each processed row of subject data.

**Comment by eatyourgreens** [comment]
Tests pass when I run them in isolation on my laptop but are failing in CI. 🤔

**Review by goplayoutside3 — APPROVED** [review]
Looks good!

**Comment by eatyourgreens** [comment]
Cheers!

**Comment by eatyourgreens** [comment]
Also noting here: [Mocking APIs in stories](https://storybook.js.org/docs/react/writing-stories/build-pages-with-storybook#mocking-api-services), as the subject picker stories are currently missing mock subjects to populate the data table.

**Pull request merged**
