### PR TITLE
Add isComplete to textAnnotation model

### PR DESCRIPTION
**Pull request by mcbouslog**
Package: lib-classifier

As noted in https://github.com/zooniverse/front-end-monorepo/pull/1799#pullrequestreview-511979311

Describe your changes:
- refactors tests for textAnnotation with value of (not empty) string and default (empty string)
- adds `isComplete` view to textAnnotation model

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by mcbouslog** [comment]
The ASM Staging project (https://localhost:8080/?project=1764) drawing task with required text subtask now works as expected, but with these changes a standalone text task throws focus from the task `textarea` to the `body` after first character (I think on keydown), see https://local.zooniverse.org:8080/?project=1693&workflow=3430.

**Review by eatyourgreens — DISMISSED** [review]
Looks good to me!

**Comment by eatyourgreens** [comment]
Changing `annotation.isComplete` from `true` to `false` (or vice versa) on the annotation prop is unmounting and remounting the `DefaultTextTask` component. `autoFocus` is `false`, so focus goes back to the window on unmount.

**Comment by eatyourgreens** [comment]
The focus bug is down to my terrible code in the `Tasks` component, which is mounting a new task component whenever props change. I can roll the fix into #1859, which adds `useEffect` so that set-up code only runs once for a task.

**Comment by eatyourgreens** [comment]
I've updated #1859 to fix the mounting/unmounting bug (in e649f2e7f3e28e38e243f32c888c8530fcc887ef.) I cherry-picked the changes here into that branch and that commit does fix the focus problem.

**Review by srallen — APPROVED** [review]
LGTM. This fixes the scope of the reported issue. Thanks to @eatyourgreens for the focus bug fix in the other PR. There's some Grommet issues, but we have a plan to upgrade that to see if those issues are fixed then.

**Comment by eatyourgreens** [comment]
While testing this, I found a weird (but cosmetic) drawing bug when you go back to a drawing task and interact with previous marks. I'm going to write up a separate issue for that because I think it can be reproduced on master.

**Pull request merged**
