### PR TITLE
Update react-rnd

### PR DESCRIPTION
**Pull request by srallen**
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ 

Package: lib-react-components

Describe your changes:
Updates react-rnd to 10.1.10. Tested with the MovableModal story in the react-components library and the drawing tools stories from the classifier storybook. The drawing tool stories should open the subtask when the story runs and they aren't for some reason. If you click on the mark, that should open it. I'm pretty sure this is an issue with the story itself, but out of scope of this PR and I'd like to wait for the upgrade to merge anyway.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I haven't checked but #1922 might help with subtask stories.

**Review by eatyourgreens — APPROVED** [review]
Changes look good. `yarn.lock` needs to be rebuilt after the recent updates to the storybook.

**Comment by eatyourgreens** [comment]
#1932 might have fixed the crashing Transcription Line stories. I'm not seeing them crash when running the storybook locally.

**Comment by srallen** [comment]
I'm not sure what to do about this. As far as I can tell, the issue is this again: https://github.com/webpack/webpack/issues/6522 and we have the recommended workaround setup for the react components library for webpack 4. I think the issue is in a dependency of a dependency not bundling correctly for umd due to this bug.

**Pull request closed without merging**
