### PR TITLE
App-project: Pass language query param to PFE nav links (Talk, Collections, Recents)

### PR DESCRIPTION
**Pull request by goplayoutside3**
## Package
app-project

## Linked Issue and/or Talk Post
https://github.com/zooniverse/front-end-monorepo/projects/15

This PR is built on PFE behavior where inserting a query parameter, such as `language=fr`, will display the page in French.
Example: https://www.zooniverse.org/projects/zookeeper/galaxy-zoo?language=fr

## Describe your changes
In order to preserve current locale when navigating from FEM --> PFE pages, we have to insert a `language` query param. This PR updates the `addQueryParams()` helper function to handle locale when navigating specifically to PFE. Noting that this behavior is only needed while Talk, Collections, and Recents are PFE pages.

## How to Review
To review project navigation in a language other than English, run TESS locally and visit its [French home page](https://local.zooniverse.org:3000/projects/fr/nora-dot-eisner/planet-hunters-tess?env=production). Hover over the links to Talk, Collections, and Recents. The href should be formatted with query params `?env=production&language=fr`.

To review a project in English without a specified env, run i-fancy-cats locally and visit its [home page](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats). Hover over the links to Talk, Collections, and Recents. The href should not include an `env` or `language` query parameter.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## New Feature
- [ ] The PR creator has listed user actions to use when testing the new feature
- [ ] Unit tests are included for the new feature

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by eatyourgreens** [comment]
You can pass the locale in the URL for FEM projects that link to PFE. Try it out here with Talk in French. 
https://www.zooniverse.org/projects/fr/nora-dot-eisner/planet-hunters-tess

This PR might not be needed.

**Comment by goplayoutside3** [comment]
> You can pass the locale in the URL for FEM projects that link to PFE. Try it out here with Talk in French. https://www.zooniverse.org/projects/fr/nora-dot-eisner/planet-hunters-tess

You're right! I forgot we already addressed this navigation. Can you remind me - is it handled by an nginx config I can link here?

**Comment by eatyourgreens** [comment]
It was a change to the PFE router. Basically duplicating the project block but with a locale parameter. I’ll look up the PR.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/Panoptes-Front-End/pull/6145

**Comment by goplayoutside3** [comment]
Got it, thank you!

**Pull request closed without merging**
