### PR TITLE
Drawing: disable touch panning

### PR DESCRIPTION
**Pull request by eatyourgreens**
Restrict touch actions to pinch-zoom on the drawing canvas. I _think_ this will fix drawing on touch screens, by disabling scrolling and dragging when you move your finger.

At the moment, if you visit https://frontend.preview.zooniverse.org/projects/penguintom79/seabirdwatch/classify with a mobile device that supports pointer events, you should find that placing and dragging a mark fails. The whole page is scrolled/dragged when you move your finger.

Package:
lib-classifier

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Trying this out again in Safari on iOS 13, I'm unable to reproduce the buggy behaviour where dragging a mark would scroll the page up and down. This PR might not be needed after all.

**Comment by shaunanoordin** [comment]
Let me give this a whirl on my Android+Chrome

**Comment by shaunanoordin** [comment]
On Android + Chrome , at the current deployed version of https://frontend.preview.zooniverse.org/projects/penguintom79/seabirdwatch/classify,

- 👍 I can click to place a new Point mark.
- 👍 I can click on a Point mark's delete button to delete a mark. 
- 💀 Attempting to move an existing Point mark by dragging it problematic - the browser window scrolls instead.
- 💀 Attempting to pan/move the Subject in the Subject viewer by dragging is problematic - the browser window scrolls instead.

This PR _may_ be needed after all - do we have a version on staging?

Otherwise I need to figure out how to connect my phone to my machine's localhost server... or maybe use the Chrome emulators, hmm. That may be a smarter idea.

**Comment by shaunanoordin** [comment]
On Android + Chrome , at the current deployed version of https://frontend.preview.zooniverse.org/projects/penguintom79/seabirdwatch/classify,

- 👍 I can click to place a new Point mark.
- 👍 I can click on a Point mark's delete button to delete a mark. 
- 💀 Attempting to move an existing Point mark by dragging it problematic - the browser window scrolls instead.
- 💀 Attempting to pan/move the Subject in the Subject viewer by dragging is problematic - the browser window scrolls instead.

This PR _may_ be needed after all - do we have a version on staging?

Otherwise I need to figure out how to connect my phone to my machine's localhost server... or maybe use the Chrome emulators, hmm. That may be a smarter idea.

**Comment by eatyourgreens** [comment]
>💀 Attempting to pan/move the Subject in the Subject viewer by dragging is problematic - the browser window scrolls instead.

The subject image might also need to be styled with `touch-action: none;` or `touch-action: pinch-zoom;`. I hadn't thought of that. This PR only modifies the styles for the drawing components.

**Comment by shaunanoordin** [comment]
Unfortunately, `InteractionLayer.StyledRect.touch-action = pinch-zoom` isn't sufficient to solve the 'dragging-a-mark-also-scrolls-the-browser' window issue. (Tested on macOS+Chrome in touchscreen emulation)

You may be right about other things requiring touch-action: none or touch-action: pinch-zoom, but I'm still trying to figure out what specifically

**Comment by eatyourgreens** [comment]
I can't remember if we still have a browserstack account, but you can use browserstack.com to browse localhost from a phone or tablet. Real devices too, I think, not emulators.

**Comment by shaunanoordin** [comment]
(EDIT: this comment was supposed to have gone up an hour ago 😞 )

I've found one possible solution, but it has a serious caveat. Basically, I tried moving the `touch-action:none` to the _SVG's container element._

```
// In SingleImageViewer.js (and also for each other viewer type, I guess)

const Container = styled.div`
  ...
  touch-action: pinch-zoom;
  OR
  touch-action: none;
`
```

The Good:

- On localhost + Chrome (emulating touch devices) I'm able to drag to move the Subject in the Subject Viewer. (view panning)
- On localhost yadda yadda, I'm able to place new Points and Rectangles by clicking.
- On yadda yadda, I'm able to move Points by dragging.

The bad:

- On localhost + Chrome (emulating touch devices), attempting to MOVE or RESIZE a Rectangle (or anything with drag handles) results in weird behaviour, such as triggering a resize before the drag-move action at the same time.

Notes:

- Maybe I should just try setting `<svg style={{ touchAction: 'none' }}>`, hmm.

**Comment by eatyourgreens** [comment]
Thanks Shaun!  This was meant to be a quick fix so I wouldn’t spend a lot of time on it. I remember vanishing down the rabbit hole of `touch-action` styles when I looked at this for PFE and it can take over quite a lot of your life.

**Comment by shaunanoordin** [comment]
I'm revisiting this PR because the pull reminder app is hounding me about it.

So far: the current solution of adding `touch-action: pinch-zoom` to `DrawingToolMarks` wasn't sufficient to solve the problem of "drag actions scroll the viewport on mobile instead of moving drawing tool marks". I'm sure there's a solution to the problem, but it may be a bit more involved than a simple fix.

@eatyourgreens Do we want to close this PR and revisit the fix again later, or continue efforts right here/now? Either way, I'm happy to pair with you on this.

**Comment by eatyourgreens** [comment]
Maybe put this on hold, but leave it open? I think we'll need to solve this problem sooner, rather than later, because so many people want to contribute from tablets.

**Comment by shaunanoordin** [comment]
👌 Righto, we'll get this sorted.

**Comment by eatyourgreens** [comment]
It's definitely fixed on PFE, at least for iOS 13. I just checked Penguin Watch and could drag marks around without any scrolling. I should remind myself how the fix for that worked. It might involve adding handlers to the document root and calling `event.preventDefault()` there.

**Comment by eatyourgreens** [comment]
```js
event.nativeEvent.stopImmediatePropagation()
```
might help here.

**Comment by srallen** [comment]
Is this still being worked on?

**Comment by eatyourgreens** [comment]
Yep!

**Comment by srallen** [comment]
It's unclear to me if this is ready for another review.

**Comment by srallen** [comment]
@eatyourgreens are you available to work on this or should someone else follow up on it?

**Comment by eatyourgreens** [comment]
I'm not going to get back to this any time soon, but here are a couple of useful links.

- https://github.com/zooniverse/Panoptes-Front-End/pull/5411 which fixed this for drawing in PFE.
- [`touch-action`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), the standard technique to disable touch scrolling.

**Comment by eatyourgreens** [comment]
iOS 13 lets me draw without problem on Planet Four. Android needs checking but maybe this PR isn’t needed.

**Comment by eatyourgreens** [comment]
D’oh! That’s PFE, where this is fixed.

**Comment by srallen** [comment]
@wgranger do you have any time this week or next to have look at this? It's unclear to me what still needs to be done with it.

**Comment by srallen** [comment]
@eatyourgreens is anything going to happen with this? If not, can we just close this and track in issue? This PR is pretty far behind.

**Comment by eatyourgreens** [comment]
Done! I've opened https://github.com/zooniverse/front-end-monorepo/issues/1912 to track it, and noted that this a regression from PFE.

**Pull request closed without merging**
