### PR TITLE
@zooniverse/classifier: improvements to output bundle size

### PR DESCRIPTION
**Pull request by eatyourgreens**
- add webpack bundle analyser
- import only the `lodash` utilities that are used in the code.
- mark `i18next` and `react-18next` as external dependencies.
- mark MobX dependencies as external.
- replace `superagent` with `fetch`.
- import only the `d3` modules that are used in the code.
- load `d3` modules as external dependencies.

Should reduce the output bundle size by ~400k.

## Package
lib-classifier

## How to Review
Build the classifier and the output bundle size should have dropped from ~1.5MB to ~1.1MB. The built classifier should still work when loaded into the Classify page of the project app.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

**Comment by goplayoutside3** [comment]
When I run `yarn bootstrap` on this branch, and visit PH TESS [locally](https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess?env=production), I get an error when I click the workflow selector on the home page:

`ReferenceError: unable to load workflow 11235 for project undefined`

I also suggest adding a note to lib-classifier's readme about how to run webpack bundle analyzer (including that `new BundleAnalyzerPlugin()` needs to be uncommented in webpack.dist.js).

**Comment by eatyourgreens** [comment]
I’ve deployed this branch and the classifier loads for PH-TESS. 
https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235

**Comment by eatyourgreens** [comment]
I thought I’d added a comment to the webpack development config, about uncommenting the bundle analyser plug-in. The plug-in itself has some documentation in its [Readme](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/README.md).

**Comment by eatyourgreens** [comment]
>When I run yarn bootstrap on this branch, and visit PH TESS [locally](https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess?env=production), I get an error when I click the workflow selector on the home page:
>
>```
>ReferenceError: unable to load workflow 11235 for project undefined
>```

I'm not sure how to debug that. Can you give any steps to reproduce it? The build is working fine on kubernetes, as far as I can tell (see the link above.)

**Comment by eatyourgreens** [comment]
Here's the Classify page running on my laptop. I've bootstrapped the monorepo from this branch and I'm running the NextJS app with `yarn start:dev`.

Screenshot of the PH-TESS Classify page, served from localhost.

**Comment by eatyourgreens** [comment]
The only error I see is #3618, a warning about invalid i18next config when the app builds.

**Comment by eatyourgreens** [comment]
@goplayoutside3 this just occurred to me: were you running the NextJS app in development mode? You’ll need to run it in production mode when you’re testing it. Development mode is only for development work on the NextJS  app code. 

I think you might uncovered a race condition in either `ClassifierContainer` or `Classifier`. I’m not sure why it shows up here but not on the main branch.

**Comment by eatyourgreens** [comment]
#3873 should make sure that the project is loaded before workflow selection runs.

**Comment by eatyourgreens** [comment]
Closing this in favour of #3900.

**Pull request closed without merging**
