### PR TITLE
Add default query parameters

### LINKED ISSUE #28: panoptes.js default params for requests
The current API client has some default params. Should we add that here?

https://github.com/zooniverse/panoptes-javascript-client/blob/4ef31ecdfa5fb8f4617be408dc52a5c4ece940ad/lib/config.js#L59-L61

### PR DESCRIPTION
**Pull request by srallen**
Closes #28. This adds default query params for `http_cache` which the current client has defined and I believe is for the db read replica. Also adds check and param for `admin` which is currently in PFE's code base, but it makes sense to move into the client itself.

### CODE REVIEW

**Comment by srallen** [comment]
I should add this to the docs before merging

**Comment by eatyourgreens** [comment]
I'm not sure if that `http_cache` parameter was ever used by the API, in the end. No harm in leaving it in, though.

**Comment by camallen** [comment]
`http_cache` is used to turn http caching on/off by the client - http caching generally is not functioning server side as it needs some more work and testing. See
https://github.com/zooniverse/Panoptes/blob/af2e49ea802c0636ef7902605893f7bd2cbf1b02/app/controllers/concerns/json_api_render.rb#L11
and https://github.com/zooniverse/Panoptes/blob/af2e49ea802c0636ef7902605893f7bd2cbf1b02/lib/json_api_controller/indexable_resource.rb#L6

**Comment by srallen** [comment]
OK, it may not do anything yet, but it's probably fine to leave the param for now.

**Comment by srallen** [comment]
I'll update the docs after #45 merges since I renamed the main docs file to readme so it would render correctly on github.

**Comment by rogerhutchings** [comment]
Also, I notice the tests run forever without exiting..

**Comment by rogerhutchings** [comment]
I take it back, it just takes ages for mocha to exit after the tests complete. Have you experienced this @srallen?

**Comment by srallen** [comment]
Thanks for fixing the linting stuff. I've been lazy and haven't installed anything to do with standard in my editor yet. 

I noticed the slow exit too. It's superagent-mock, but I haven't figured out what exactly causes it.

**Comment by srallen** [comment]
Going to squash and merge this since #57 was merged.

**Pull request merged**
