### PR TITLE
lib-user: add user_group actions, related components for local dev

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- lib-user

## Linked Issue and/or Talk Post
- towards user stats and group stats efforts

## Describe your changes
- add user_group actions for create, update, and delete
- add initial MyGroups component

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What user actions should my reviewer step through to review this PR?
  1. from `lib-user/` run `yarn dev`
  2. go to `https://local.zooniverse.org:8080/?users=[your staging user login here]/groups`
  3. note your groups, if you have any
  4. create a group (at the bottom)
  5. go to your new group at `https://local.zooniverse.org:8080/?groups=[new group id here]`
  6. edit your group display_name (towards the bottom)
  7. (optional) delete your group (towards the bottom)
- Which storybook stories should be reviewed? none yet
- Are there plans for follow up PR’s to further fix this bug or develop this feature? yes, see linked GitHub project FEM Stats Efforts

### CODE REVIEW

**Comment by goplayoutside3** [comment]
I think I might be doing something incorrectly.. When I run lib-user locally on this branch and visit `https://local.zooniverse.org:8080/?users=goplayoutside3/groups`, I don't see a "Create a group" option. I just see:
Screenshot 2023-11-13 at 4 12 13 PM

I'll note too that I initially visited the /groups page while not signed in, got a bunch of runtime errors, visited the lib-user root page, signed in, and then tried to navigate to /groups again. I can't seem to get my /stats page to show real data either. Am I doing something wrong as far as sign-in?

**Comment by mcbouslog** [comment]
> I don't see a "Create a group" option.

This is a mistake - if you don't have any groups I'm returning the noted message without the create group component [here](https://github.com/zooniverse/front-end-monorepo/pull/5582/files#diff-06eea4abd4f09ef147c18f8371105dbf9003274814a14a5fdaa5579751e03ea0R55). I'll fix accordingly...

**Comment by mcbouslog** [comment]
I also often get the oauth errors on initial dev app load, I think related to sign-in, but am having trouble recreating. Once I refresh the page, the dev app seems to work as expected with login/logout. I'm going to restart, maybe work on a different branch, and try again to see if recent code changes have fixed the error or if I can recreate the issue and add a debugger. Very open to suggestion with this initial error though, I'm not sure about next steps.

Otherwise, I've refactored so the create group input should show regardless of if you're in any user groups.

**Comment by goplayoutside3** [comment]
### PR Review Steps
I checked out this branch again and followed the steps:

1. from lib-user/ run `yarn dev`
- I'm able to run the app
2. go to `https://local.zooniverse.org:8080/?users=[your staging user login here]/groups`
- After I login, I can view this page and there's a button to create a group
3. note your groups, if you have any
- My login doesn't belong to any groups, so I see "You are not an active member of any groups"
4. create a group (at the bottom)
- I typed "goplayoutside" into the text field and clicked "Create Group". The component refreshes, but nothing populates in the "MyGroups" list. I'm not sure if it's supposed to?
6. go to your new group at `https://local.zooniverse.org:8080/?groups=[new group id here]`
- At this point in testing when I go to https://local.zooniverse.org:8080/?groups=goplayoutside, I see an error. Should I be finding the group id as a number somewhere instead?
Screenshot 2023-11-24 at 9 18 06 AM

___
### Intermittent OAuth error
> I also often get the oauth errors on initial dev app load, I think related to sign-in, but am having trouble recreating.

I'm having trouble recreating this too, but saw it when I downloaded and ran this branch. It was an oath error saying it can't get info from the url when I first visit https://local.zooniverse.org:8080, but once I close the error modal and click "Login" to lib-user, I never see the error again. 

I think what's happening whenever I run a lib-user PR branch for the first time is I'm already signed in to Zooniverse staging in my browser (from other dev work or any other ?env=staging url), and when I first visit a lib-user url, it should show the following screen:
Screenshot 2023-11-13 at 4 17 55 PM
But instead of that oath screen I get the runtime error.

Unable to tell if this is a fix because of reproducibility, but would the following work for App.js? 
```
  useEffect(async () => {
      setLoading(true)

      try {
        const userAuth = await oauth.init('357ac7e0e17f6d9b05587477ca98fdb69d70181e674be8e20142e1df97a84d2d')
        setUserAuth(userAuth)
        setLoading(false)
      } catch (error) {
        console.error(error)
        setLoading(false)
      }
  }, [])
```
I don't think a function `initAuthorization()` needs to be defined and then called immediately inside useEffect().

**Comment by mcbouslog** [comment]
@goplayoutside3 - there might be an issue trying to create a user_group named `goplayoutside` conflicting with an existing user_group of the same name, as user_groups are created for every user. When you click "Create group" do you see a network request like following:
user_group_post_request
With a payload similar to: `{ user_groups: {display_name: "MB Test Group 456", name: "MBTestGroup456" }}`?

**Comment by mcbouslog** [comment]
The user_group page would be with the ID (not name), like `https://local.zooniverse.org:8080/?groups=1326952` where 1326952 is the ID for user_group "MB Test Group 456". User stats page is with login (sorry it is indeed confusing!).

**Comment by mcbouslog** [comment]
Refactoring the useEffect as noted results in the following console warning:
```
Warning: useEffect must not return anything besides a function, which is used for clean-up.

It looks like you wrote useEffect(async () => ...) or returned a Promise. Instead, write the async function inside your effect and call it immediately:
```

I've tried refactoring it more though, as I think you're correct the issue is related to the useEffect. Based on some of the error messages noting "cannot read properties of null" trying to read parentNode and contentWindow, it feels like the oauth code is trying to do things the browser hasn't defined yet, so maybe the refactor will help 🤞 .

**Comment by eatyourgreens** [comment]
`useEffect` must be synchronous. You can’t pass it an async function.

**Comment by goplayoutside3** [comment]
> useEffect must be synchronous. You can’t pass it an async function.

Ah shoot, that's a good reminder. 

This time when I checked out this branch to run locally, I didn't get any errors!

I was able to use the "Login" button, and went to https://local.zooniverse.org:8080/?users=goplayoutside3/groups. I saw a request in the Network tab for `/api/memberships` and in the response I don't have any memberships yet. Next, I tried to create a group with the title "btsfan" and it was successful 👍 I can now click on the "btsfan" group to https://local.zooniverse.org:8080/?groups=1326953.

Would you like me to try "goplayoutside" as a group title again? That string is only part of my username though, so I'm also confused why there would be a conflict.

**Comment by eatyourgreens** [comment]
Re. `useEffect`, effects shouldn’t be used to set component state from props either. I find myself referring to [You Might Not Need An Effect](https://react.dev/learn/you-might-not-need-an-effect) a lot when I’m writing React.

Also, it maybe says something about the usability of a framework if you have to publish a page that tells people how not to use it. 🤨

**Comment by mcbouslog** [comment]
@goplayoutside3 - that's promising the dev app didn't error initially and also good to hear you were able to create and access a group! 😄 

Hmm, I'm not sure about trying 'goplayoutside' again. I'm curious! So maybe? But if as I expect it will errors again I'm not sure what next steps would be. The actual/planned create user group modal will have proper validation and error handling, but these changes are still just for initial dev purposes.

**Review by goplayoutside3 — APPROVED** [review]
I was able to great another group with the title "goplayoutside". The inability to create a group when testing earlier may have been caused by myself not being truly logged in to the dev app. For instance, I can still navigate to https://local.zooniverse.org:8080/?users=goplayoutside3/groups and click "Create Group" even if I'm logged out. Now that I can load the app locally and sign-in without any errors, I think this looks good!

**Comment by mcbouslog** [comment]
That's great! That's prob what happened - signed out, but input was still there looking like it should work. Sorry this is all still a little hacky, but I think will start coming together now and I'll continue to chip away at the parts like that (still see user group create input when signed out) in subsequent PRs. Thanks!

**Pull request merged**
