### PR TITLE
Use withArgs for spies

### PR DESCRIPTION
**Pull request by eatyourgreens**
Use withArgs to create specific spies in tests, rather than using calledOnceWith.

Package:
app-project

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
So I expected this to break the tests, as per the same change in #908, but it doesn't. 🤔

**Comment by srallen** [comment]
There's some ambiguity with the meaning of `calledOnceWith` and it seems that using `withArgs` is the more clear option of what we're intending to test? https://github.com/sinonjs/sinon/issues/1200

**Comment by eatyourgreens** [comment]
I hadn’t thought of that. 

Today I found that the pattern here will fail with something like `expected spy to be called once but it was called 0 times` whereas `calledOnceWith` will list the expected args and actual args when it fails. 

That can be much more helpful when debugging failing tests, so I’m happy to close this without merging if that’s preferred.

**Comment by eatyourgreens** [comment]
On ambiguity, if I call a function with`(1, 2)` then `calledOnceWith(1)` will pass but `withArgs(1)` might fail the test because it looks for an exact match.

**Pull request merged**
