### PR TITLE
Updated description of the workflow resource updates

### PR DESCRIPTION
**Pull request by srallen**
Package: lib-classifier related proposal

Related #123, This updates the ADR-5 proposal with a more detailed description of precisely how steps will be implemented on the workflow resource. 

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
We should probably include a sample of how sub-tasks are represented in the backend currently:

```
{
  "id": "1234",
  "display_name": "Combo task test",
  "tasks": {
    "T0": {
      "help": "Main task help text",
      "type": "drawing",
      "tools": [
        {
          "type": "point",
          "color": "#00ff00",
          "label": "Tool name",
          "details": [
            {
              "help": "Sub task 1 help",
              "type": "single",
              "answers": [
                {
                  "label": "Bar"
                },
                {
                  "label": "Baz"
                }
              ],
              "question": "Foo?"
            }
          ]
        }
      ],
      "instruction": "Explain what to draw."
    }
  },
  "first_task": "T0",
  "prioritized": false,
  "grouped": false,
  "pairwise": false,
  "configuration": { },
  ...
}
```

**Comment by srallen** [comment]
I've updated the context section to include that combo task example as well as updated the consequences section to include the request for the new steps property as well as what is going to be involved with storing the map type in json.

**Comment by srallen** [comment]
@rogerhutchings and @eatyourgreens I think this is close for being ready for final review. I think we should specify how we'll store steps in the database. Right now I have listed these options:

> Use a javascript helper library that has full support for map to [serialize](https://github.com/sonnyp/JSON8/tree/master/packages/json8#ooserialize) it as an object (maps are a sub-class of objects) and JSON [parse](https://github.com/sonnyp/JSON8/tree/master/packages/json8#ooparse) back to a map. This would probably be preferred since it would make sure our serialization and parsing is consistent and the keys we are using are strings, so it would be a straight forward conversion to a standard object.

I think we should go with the JSON8 library. I don't see any reason to DIY here.

**Comment by srallen** [comment]
I made a note that we will try the library first for storing the data.

**Pull request merged**
