### PR TITLE
Add overflowAnchor none to Choice component

### PR DESCRIPTION
**Pull request by mcbouslog**
Package:
- lib-classifier

Describe your changes:
- add `overflowAnchor: none` to Choice component

Notes
- Choice component scrolls to top on question answer
- ^ noted in Chrome and Firefox

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by mcbouslog** [comment]
Here's a gif of the behavior including the focused element, noting the input stays focused, but the component still scrolls to the top:
survey-scroll-issue

**Comment by srallen** [comment]
@mcbouslog I think what's happening here is indeed a focus bug with `Drop` or perhaps with the portal implementation underneath, actually, so adding the CSS I suggested isn't going to fix it.

I watched the dev tools evaluate `document.activeElement` and occasionally when clicking one of the inputs, I saw the focus go from one input, the div for the react portal, then back to input I did click. It didn't consistently show that this is happening in the eval, but would perhaps cause the the scroll to top issue?

What's weird is that if I console logged the active element in say the SurveyTask component, I always consistently saw what you'd expect the active element should be: the various inputs that you can click.

However, to confirm the flash I saw in the dev tools evaluator, I changed the eval to be `console.log(document.activeElement)` (I don't recommend leaving this in place) and clicked around on the inputs and caught it:

Screen Shot 2021-06-08 at 7 27 42 PM

Given this strange behavior, I think the best course of action would be to remove the `Drop` and just render the `Box` of the choice inline.

**Comment by eatyourgreens** [comment]
Maybe try passing `trapFocus: false` to the `Drop`?

**Comment by mcbouslog** [comment]
> Maybe try passing `trapFocus={false}` to the `Drop`?

Unfortunately still no luck. I'll try mocking something up in a CodeSandBox to share with the Grommet team, or at minimum clarify what's going on internally.

**Pull request closed without merging**
